import type { IncidentFeature, IncidentScenarioStep } from "./types.js";

export const INCIDENT_SOURCE_ID = "incident-ops";
export const INCIDENT_LAYER_ID = "incident-points";

export const HONOLULU_CENTER: readonly [number, number] = [-157.8583, 21.3069];

export const INITIAL_INCIDENTS: readonly IncidentFeature[] = [
  {
    id: "INC-1001",
    title: "Harbor fuel sheen",
    type: "Environmental",
    severity: "critical",
    status: "open",
    assignedTo: "Hazmat 3",
    updatedAt: "2026-05-05T18:00:00.000Z",
    reportedAt: "2026-05-05T17:34:00.000Z",
    coordinate: [-157.8722, 21.3074],
    etaMinutes: 8,
    affectedAssets: 7,
    summary: "Fuel sheen detected near Pier 2 with harbor patrol holding a containment perimeter.",
    relatedRecords: [
      { id: "CASE-7781", label: "Environmental case", status: "Active" },
      { id: "UNIT-HZ3", label: "Hazmat 3 assignment", status: "Enroute" },
    ],
    attachments: [
      { id: "ATT-2001", name: "Pier 2 drone still", kind: "image" },
      { id: "ATT-2002", name: "Initial water sample", kind: "lab" },
    ],
  },
  {
    id: "INC-1002",
    title: "Kakaako grid outage",
    type: "Utilities",
    severity: "high",
    status: "assigned",
    assignedTo: "Utility Liaison",
    updatedAt: "2026-05-05T17:55:00.000Z",
    reportedAt: "2026-05-05T17:20:00.000Z",
    coordinate: [-157.8558, 21.2994],
    etaMinutes: 14,
    affectedAssets: 12,
    summary: "Partial feeder outage affecting signals and two public-safety facilities.",
    relatedRecords: [
      { id: "CASE-7782", label: "Utility ticket", status: "Assigned" },
      { id: "ASSET-412", label: "Kakaako feeder", status: "Impacted" },
    ],
    attachments: [{ id: "ATT-2010", name: "Feeder telemetry extract", kind: "table" }],
  },
  {
    id: "INC-1003",
    title: "Ala Moana signal failure",
    type: "Traffic",
    severity: "medium",
    status: "monitoring",
    assignedTo: "Traffic 1",
    updatedAt: "2026-05-05T17:48:00.000Z",
    reportedAt: "2026-05-05T17:02:00.000Z",
    coordinate: [-157.8444, 21.2917],
    etaMinutes: 22,
    affectedAssets: 3,
    summary: "Signal timing fault is producing congestion at the mall access road.",
    relatedRecords: [{ id: "CASE-7783", label: "Traffic control log", status: "Monitoring" }],
    attachments: [{ id: "ATT-2020", name: "Intersection camera clip", kind: "video" }],
  },
  {
    id: "INC-1004",
    title: "Waikiki flood report",
    type: "Flooding",
    severity: "high",
    status: "open",
    assignedTo: "Field Ops 2",
    updatedAt: "2026-05-05T17:41:00.000Z",
    reportedAt: "2026-05-05T16:58:00.000Z",
    coordinate: [-157.8261, 21.2796],
    etaMinutes: 18,
    affectedAssets: 5,
    summary: "Street flooding reported near Kuhio Avenue after a blocked drain alarm.",
    relatedRecords: [
      { id: "CASE-7784", label: "Drainage work order", status: "Open" },
      { id: "ASSET-988", label: "Kuhio drain sensor", status: "Alarm" },
    ],
    attachments: [{ id: "ATT-2030", name: "Drain sensor trace", kind: "chart" }],
  },
  {
    id: "INC-1005",
    title: "Airport logistics delay",
    type: "Logistics",
    severity: "low",
    status: "assigned",
    assignedTo: "Logistics Desk",
    updatedAt: "2026-05-05T17:36:00.000Z",
    reportedAt: "2026-05-05T16:45:00.000Z",
    coordinate: [-157.9211, 21.3187],
    etaMinutes: 30,
    affectedAssets: 2,
    summary: "Staging shipment delayed at airport cargo gate with one response kit pending release.",
    relatedRecords: [{ id: "CASE-7785", label: "Cargo hold note", status: "Assigned" }],
    attachments: [{ id: "ATT-2040", name: "Cargo manifest", kind: "document" }],
  },
  {
    id: "DEMO-EDIT-0001",
    title: "Isolated demo coordination record",
    type: "Exercise",
    severity: "medium",
    status: "assigned",
    assignedTo: "Demo Operations",
    updatedAt: "2026-05-05T18:00:00.000Z",
    reportedAt: "2026-05-05T17:59:00.000Z",
    coordinate: [-157.8619, 21.3047],
    etaMinutes: 12,
    affectedAssets: 0,
    summary: "Dedicated resettable record for optimistic-concurrency and realtime reconciliation demonstrations.",
    relatedRecords: [{ id: "DEMO-SANDBOX", label: "Isolated demo-edit profile", status: "Resettable" }],
    attachments: [],
    revision: 1,
    safeDemoRecord: true,
  },
];

export const INCIDENT_SCENARIO_STEPS: readonly IncidentScenarioStep[] = [
  {
    label: "Escalate outage",
    description: "Kakaako outage escalates to critical after the facility backup window shrinks.",
    kind: "upsert",
    incident: {
      ...INITIAL_INCIDENTS[1],
      severity: "critical",
      status: "open",
      assignedTo: "Utility Strike Team",
      etaMinutes: 6,
      affectedAssets: 16,
      updatedAt: "2026-05-05T18:02:20.000Z",
      summary: "Backup power window dropped below ten minutes; strike team moved to priority response.",
      relatedRecords: [
        ...INITIAL_INCIDENTS[1].relatedRecords,
        { id: "UNIT-UST", label: "Utility strike team", status: "Dispatched" },
      ],
    },
  },
  {
    label: "Create brush response",
    description: "New field report arrives east of Waikiki.",
    kind: "upsert",
    incident: {
      id: "INC-1006",
      title: "Diamond Head brush response",
      type: "Fire",
      severity: "high",
      status: "assigned",
      assignedTo: "Brush 4",
      updatedAt: "2026-05-05T18:03:10.000Z",
      reportedAt: "2026-05-05T18:01:40.000Z",
      coordinate: [-157.833, 21.286],
      etaMinutes: 9,
      affectedAssets: 4,
      summary: "Brush response opened after smoke report along the Diamond Head access road.",
      relatedRecords: [
        { id: "CASE-7790", label: "Fire response case", status: "Assigned" },
        { id: "UNIT-B4", label: "Brush 4 assignment", status: "Enroute" },
      ],
      attachments: [{ id: "ATT-2050", name: "Caller geotag", kind: "location" }],
    },
  },
  {
    label: "Resolve signal failure",
    description: "Traffic crew clears the signal controller fault.",
    kind: "upsert",
    incident: {
      ...INITIAL_INCIDENTS[2],
      severity: "low",
      status: "resolved",
      assignedTo: "Traffic 1",
      etaMinutes: 0,
      affectedAssets: 0,
      updatedAt: "2026-05-05T18:04:00.000Z",
      summary: "Controller fault cleared and corridor timing returned to normal operations.",
      relatedRecords: [
        ...INITIAL_INCIDENTS[2].relatedRecords,
        { id: "CLOSE-1003", label: "Closure note", status: "Complete" },
      ],
    },
  },
  {
    label: "Monitor harbor",
    description: "Harbor incident moves from open response to monitoring.",
    kind: "upsert",
    incident: {
      ...INITIAL_INCIDENTS[0],
      status: "monitoring",
      assignedTo: "Harbor Watch",
      etaMinutes: 0,
      updatedAt: "2026-05-05T18:05:30.000Z",
      summary: "Containment boom is placed; harbor watch is monitoring drift and sample results.",
      relatedRecords: [
        ...INITIAL_INCIDENTS[0].relatedRecords,
        { id: "BOOM-17", label: "Containment boom", status: "Placed" },
      ],
    },
  },
  {
    label: "Archive logistics",
    description: "Resolved logistics delay is archived from the active feed.",
    kind: "delete",
    id: "INC-1005",
  },
];
