import { createHonuaCacheState } from "@honua/sdk-js/honua";

import type { BuilderDataset } from "./types.js";

const extent = {
  xmin: -157.925,
  ymin: 21.285,
  xmax: -157.79,
  ymax: 21.345,
  spatialReference: { wkid: 4326 },
};

export function createFixtureAiSpatialAppBuilderDataset(): BuilderDataset {
  return {
    workspaceId: "honua-ai-spatial-builder-fixture",
    resultSourceId: "honua-cloud:ai-builder-results",
    generatedAt: "2026-05-05T18:30:00.000Z",
    sources: [
      {
        id: "honua-cloud:parcels",
        title: "Honolulu parcels",
        fields: ["parcelUse", "floodZone", "builtYear", "assessedValue"],
        capabilities: ["query", "intersects", "within-distance", "bbox", "statistics"],
        capabilityState: "available",
        cache: createHonuaCacheState({
          scope: "metadata",
          status: "hit",
          keyFingerprint: "parcels-schema-v4",
          ttlMs: 86_400_000,
        }),
      },
      {
        id: "honua-cloud:fire-stations",
        title: "Fire stations",
        fields: ["stationName", "stationType"],
        capabilities: ["query", "intersects", "bbox"],
        capabilityState: "degraded",
        cache: createHonuaCacheState({
          scope: "metadata",
          status: "stale",
          keyFingerprint: "fire-stations-schema-v2",
          ttlMs: 3_600_000,
        }),
      },
      {
        id: "honua-cloud:live-permits",
        title: "Live permits",
        fields: ["permitType", "updatedAt"],
        capabilities: ["query"],
        capabilityState: "unsupported",
        cache: createHonuaCacheState({ scope: "metadata", status: "miss", keyFingerprint: "live-permits" }),
      },
    ],
    capabilityNotes: [
      {
        id: "metadata-cache",
        title: "Metadata cache",
        state: "available",
        detail: "Source schema and capability discovery use cacheable metadata flows.",
      },
      {
        id: "distance-index",
        title: "Distance predicates",
        state: "degraded",
        detail: "Fire station distance uses fixture precomputed distances when cloud distance indexes are absent.",
      },
      {
        id: "live-delta",
        title: "Realtime deltas",
        state: "unsupported",
        detail: "Live permit layers are excluded because the fixture does not advertise a live-delta contract.",
      },
    ],
    prompts: [
      {
        id: "parcels-flood",
        prompt:
          "Show parcels within 500m of fire stations built before 1970, grouped by flood zone, with a map, table, and chart.",
        intent: "distance parcel query grouped by flood zone",
        requiresClarification: {
          id: "flood-zone-source",
          question: "Use FEMA flood zones or local drainage zones for grouping?",
          choices: [
            { id: "fema", label: "FEMA flood zones", resolves: { grouping: "floodZone" } },
            { id: "drainage", label: "Local drainage zones", resolves: { grouping: "drainageZone" } },
          ],
        },
        draft: {
          id: "draft-parcels-flood",
          title: "Pre-1970 parcels near fire stations by flood zone",
          sourceIds: ["honua-cloud:parcels", "honua-cloud:fire-stations"],
          spatialPredicate: "within-distance",
          filters: {
            builtYear: { field: "builtYear", operator: "<", value: 1970 },
          },
          extent,
          grouping: ["floodZone"],
          aggregation: {
            groupBy: ["floodZone"],
            metrics: [{ fn: "sum", field: "assessedValue", alias: "assessedValue" }],
          },
          views: ["map", "table", "chart", "filter", "detail"],
          warnings: ["Fire station distance uses fixture precomputed distances in degraded cloud mode."],
          cacheNotes: [
            "Metadata/schema cache hit for parcels.",
            "Spatial result query is not cached until apply materializes a content-hash artifact.",
          ],
          estimatedCost: "$0.14 fixture credits",
          estimatedDuration: "8s",
        },
      },
      {
        id: "station-distance",
        prompt: "Find commercial parcels within 300 meters of fire stations.",
        intent: "within-distance commercial parcel filter",
        draft: {
          id: "draft-commercial-distance",
          title: "Commercial parcels within 300m of fire stations",
          sourceIds: ["honua-cloud:parcels", "honua-cloud:fire-stations"],
          spatialPredicate: "within-distance",
          filters: {
            parcelUse: { field: "parcelUse", operator: "=", value: "commercial" },
            distanceMeters: { field: "distanceMeters", operator: "<=", value: 300 },
          },
          extent,
          grouping: ["stationName"],
          views: ["map", "table", "filter", "detail"],
          warnings: [],
          cacheNotes: ["Schema cache reused; result rows require fresh execution."],
          estimatedCost: "$0.07 fixture credits",
          estimatedDuration: "5s",
        },
      },
      {
        id: "spatial-join",
        prompt: "Join parcels to nearby fire stations and summarize count by flood zone.",
        intent: "spatial join and grouped aggregation",
        draft: {
          id: "draft-spatial-join",
          title: "Parcel to station spatial join by flood zone",
          sourceIds: ["honua-cloud:parcels", "honua-cloud:fire-stations"],
          spatialPredicate: "spatial-join",
          filters: {},
          extent,
          grouping: ["floodZone"],
          aggregation: { groupBy: ["floodZone"], metrics: [{ fn: "count", field: "id", alias: "parcelCount" }] },
          views: ["map", "table", "chart", "filter"],
          warnings: ["Join cardinality is fixture bounded to 25 rows."],
          cacheNotes: ["Join plan is deterministic; joined result artifacts are content-hash cached after apply."],
          estimatedCost: "$0.11 fixture credits",
          estimatedDuration: "7s",
        },
      },
      {
        id: "bbox-filter",
        prompt: "Show only the downtown extent and keep residential parcels in a map and table.",
        intent: "bbox filtered map table",
        draft: {
          id: "draft-downtown-residential",
          title: "Downtown residential parcel extent",
          sourceIds: ["honua-cloud:parcels"],
          spatialPredicate: "bbox",
          filters: {
            parcelUse: { field: "parcelUse", operator: "=", value: "residential" },
          },
          extent: { xmin: -157.865, ymin: 21.298, xmax: -157.835, ymax: 21.32, spatialReference: { wkid: 4326 } },
          grouping: [],
          views: ["map", "table", "filter", "detail"],
          warnings: [],
          cacheNotes: ["BBOX query is debounced and not blindly cached."],
          estimatedCost: "$0.03 fixture credits",
          estimatedDuration: "3s",
        },
      },
      {
        id: "grouped-chart",
        prompt: "Chart assessed value by flood zone for older parcels.",
        intent: "grouping and aggregation chart",
        draft: {
          id: "draft-value-chart",
          title: "Assessed value by flood zone for older parcels",
          sourceIds: ["honua-cloud:parcels"],
          spatialPredicate: "intersects",
          filters: {
            builtYear: { field: "builtYear", operator: "<", value: 1980 },
          },
          extent,
          grouping: ["floodZone"],
          aggregation: {
            groupBy: ["floodZone"],
            metrics: [{ fn: "sum", field: "assessedValue", alias: "assessedValue" }],
          },
          views: ["table", "chart", "filter"],
          warnings: ["Statistics are fixture-side when the cloud catalog reports degraded aggregation."],
          cacheNotes: ["Aggregation metadata is cacheable; mutable result sets are materialized before reuse."],
          estimatedCost: "$0.05 fixture credits",
          estimatedDuration: "4s",
        },
      },
    ],
    features: [
      feature(
        "parcel-1001",
        "Kalihi warehouse parcel",
        "commercial",
        "AE",
        "Station 4",
        1958,
        220,
        1_200_000,
        -157.875,
        21.325,
      ),
      feature(
        "parcel-1002",
        "Iwilei apartment block",
        "residential",
        "X",
        "Station 1",
        1964,
        470,
        870_000,
        -157.858,
        21.315,
      ),
      feature(
        "parcel-1003",
        "Downtown mixed-use lot",
        "commercial",
        "AE",
        "Station 1",
        1948,
        160,
        1_780_000,
        -157.852,
        21.309,
      ),
      feature(
        "parcel-1004",
        "Ala Moana residential tower",
        "residential",
        "VE",
        "Station 2",
        1978,
        610,
        2_100_000,
        -157.842,
        21.295,
      ),
      feature("parcel-1005", "Kakaako civic parcel", "civic", "AE", "Station 2", 1968, 310, 990_000, -157.846, 21.302),
      feature(
        "parcel-1006",
        "Airport logistics parcel",
        "industrial",
        "X",
        "Station 9",
        1962,
        290,
        1_430_000,
        -157.915,
        21.334,
      ),
    ],
  };
}

function feature(
  id: string,
  title: string,
  parcelUse: string,
  floodZone: string,
  stationName: string,
  builtYear: number,
  distanceMeters: number,
  assessedValue: number,
  x: number,
  y: number,
) {
  return {
    id,
    sourceId: "honua-cloud:ai-builder-results",
    title,
    parcelUse,
    floodZone,
    stationName,
    builtYear,
    distanceMeters,
    assessedValue,
    x,
    y,
    attributes: { id, title, parcelUse, floodZone, stationName, builtYear, distanceMeters, assessedValue },
  };
}
