import type { HonuaExtent } from "@honua/sdk-js/honua";

import { CREW_SOURCE_ID, INCIDENT_SOURCE_ID } from "./types.js";
import type {
  UnifiedOpsFeature,
  UnifiedOpsMapPreset,
  UnifiedOpsScenarioStep,
  UnifiedOpsSourceMetadata,
} from "./types.js";

export const OPS_SOURCE_IDS = [INCIDENT_SOURCE_ID, CREW_SOURCE_ID] as const;

export const DEFAULT_WORKSPACE_EXTENT: HonuaExtent = {
  xmin: -157.93,
  ymin: 21.27,
  xmax: -157.81,
  ymax: 21.34,
  spatialReference: { wkid: 4326 },
};

export const URBAN_CORE_EXTENT: HonuaExtent = {
  xmin: -157.88,
  ymin: 21.285,
  xmax: -157.835,
  ymax: 21.315,
  spatialReference: { wkid: 4326 },
};

export const AIRPORT_EXTENT: HonuaExtent = {
  xmin: -157.94,
  ymin: 21.3,
  xmax: -157.895,
  ymax: 21.335,
  spatialReference: { wkid: 4326 },
};

export const MAP_PRESETS: readonly UnifiedOpsMapPreset[] = [
  { id: "island", label: "Island", extent: DEFAULT_WORKSPACE_EXTENT },
  { id: "urban-core", label: "Urban Core", extent: URBAN_CORE_EXTENT },
  { id: "airport", label: "Airport", extent: AIRPORT_EXTENT },
];

export const INITIAL_UNIFIED_OPS_FEATURES: readonly UnifiedOpsFeature[] = [
  {
    id: "INC-2001",
    sourceId: INCIDENT_SOURCE_ID,
    kind: "incident",
    title: "Harbor fuel sheen",
    type: "Environmental",
    severity: "critical",
    status: "open",
    district: "Harbor",
    coordinate: [-157.8722, 21.3074],
    updatedAt: "2026-05-05T18:00:00.000Z",
    etaMinutes: 8,
    impactScore: 91,
    assignment: "Hazmat 3",
    summary: "Fuel sheen detected near Pier 2 with harbor patrol holding a containment perimeter.",
    relatedIds: ["CASE-7781", "UNIT-HZ3"],
    attachments: ["Pier 2 drone still", "Initial water sample"],
  },
  {
    id: "INC-2002",
    sourceId: INCIDENT_SOURCE_ID,
    kind: "incident",
    title: "Kakaako grid outage",
    type: "Utilities",
    severity: "high",
    status: "assigned",
    district: "Urban Core",
    coordinate: [-157.8558, 21.2994],
    updatedAt: "2026-05-05T17:55:00.000Z",
    etaMinutes: 14,
    impactScore: 78,
    assignment: "Utility Liaison",
    summary: "Partial feeder outage affecting signals and two public-safety facilities.",
    relatedIds: ["CASE-7782", "ASSET-412"],
    attachments: ["Feeder telemetry extract"],
  },
  {
    id: "INC-2003",
    sourceId: INCIDENT_SOURCE_ID,
    kind: "incident",
    title: "Ala Moana signal failure",
    type: "Traffic",
    severity: "medium",
    status: "monitoring",
    district: "Urban Core",
    coordinate: [-157.8444, 21.2917],
    updatedAt: "2026-05-05T17:48:00.000Z",
    etaMinutes: 22,
    impactScore: 42,
    assignment: "Traffic 1",
    summary: "Signal timing fault is producing congestion at the mall access road.",
    relatedIds: ["CASE-7783"],
    attachments: ["Intersection camera clip"],
  },
  {
    id: "INC-2004",
    sourceId: INCIDENT_SOURCE_ID,
    kind: "incident",
    title: "Waikiki flood report",
    type: "Flooding",
    severity: "high",
    status: "open",
    district: "Waikiki",
    coordinate: [-157.8261, 21.2796],
    updatedAt: "2026-05-05T17:41:00.000Z",
    etaMinutes: 18,
    impactScore: 64,
    assignment: "Field Ops 2",
    summary: "Street flooding reported near Kuhio Avenue after a blocked drain alarm.",
    relatedIds: ["CASE-7784", "ASSET-988"],
    attachments: ["Drain sensor trace"],
  },
  {
    id: "CREW-31",
    sourceId: CREW_SOURCE_ID,
    kind: "crew",
    title: "Hazmat 3",
    type: "Hazmat",
    severity: "medium",
    status: "enroute",
    district: "Harbor",
    coordinate: [-157.868, 21.304],
    updatedAt: "2026-05-05T17:59:00.000Z",
    etaMinutes: 4,
    assignment: "INC-2001",
    summary: "Hazmat response unit moving to Pier 2 containment perimeter.",
    relatedIds: ["UNIT-HZ3", "CASE-7781"],
    attachments: ["Unit manifest"],
  },
  {
    id: "CREW-42",
    sourceId: CREW_SOURCE_ID,
    kind: "crew",
    title: "Field Ops 2",
    type: "Field Ops",
    severity: "low",
    status: "available",
    district: "Waikiki",
    coordinate: [-157.8335, 21.2828],
    updatedAt: "2026-05-05T17:57:00.000Z",
    etaMinutes: 6,
    assignment: "INC-2004",
    summary: "Field crew staged near Waikiki with storm drain equipment.",
    relatedIds: ["UNIT-F2", "CASE-7784"],
    attachments: ["Equipment checklist"],
  },
  {
    id: "CREW-55",
    sourceId: CREW_SOURCE_ID,
    kind: "crew",
    title: "Logistics Desk",
    type: "Logistics",
    severity: "low",
    status: "staged",
    district: "Airport",
    coordinate: [-157.918, 21.318],
    updatedAt: "2026-05-05T17:52:00.000Z",
    etaMinutes: 12,
    summary: "Airport logistics desk is staged for response-kit release.",
    relatedIds: ["UNIT-LD", "ASSET-KIT-14"],
    attachments: ["Cargo manifest"],
  },
];

export const INITIAL_SOURCE_METADATA: Record<string, UnifiedOpsSourceMetadata> = {
  [INCIDENT_SOURCE_ID]: {
    title: "Incident operations",
    protocol: "ogc-features",
    active: true,
    cache: {
      status: "hit",
      updatedAt: Date.parse("2026-05-05T17:45:00.000Z"),
      ttlMs: 900_000,
    },
    diagnostics: ["Schema cache hit", "Renderer cache hit", "Realtime cursor available"],
  },
  [CREW_SOURCE_ID]: {
    title: "Response crews",
    protocol: "geoservices-feature-service",
    active: true,
    cache: {
      status: "hit",
      updatedAt: Date.parse("2026-05-05T17:46:00.000Z"),
      ttlMs: 900_000,
    },
    diagnostics: ["Layer metadata cache hit", "Domain cache hit", "Crew assignment index warmed"],
  },
};

export const UNIFIED_OPS_SCENARIO_STEPS: readonly UnifiedOpsScenarioStep[] = [
  {
    label: "Escalate outage",
    description: "Kakaako outage escalates to critical after the backup power window shrinks.",
    event: {
      type: "upsert",
      feature: {
        ...INITIAL_UNIFIED_OPS_FEATURES[1],
        severity: "critical",
        status: "open",
        etaMinutes: 6,
        impactScore: 88,
        assignment: "Utility Strike Team",
        updatedAt: "2026-05-05T18:02:20.000Z",
        summary: "Backup power window dropped below ten minutes; strike team moved to priority response.",
        relatedIds: ["CASE-7782", "ASSET-412", "UNIT-UST"],
      },
    },
  },
  {
    label: "Dispatch urban crew",
    description: "A utility strike team appears in the live crew source.",
    event: {
      type: "upsert",
      feature: {
        id: "CREW-77",
        sourceId: CREW_SOURCE_ID,
        kind: "crew",
        title: "Utility Strike Team",
        type: "Utilities",
        severity: "medium",
        status: "enroute",
        district: "Urban Core",
        coordinate: [-157.8588, 21.302],
        updatedAt: "2026-05-05T18:02:35.000Z",
        etaMinutes: 5,
        assignment: "INC-2002",
        summary: "Strike team dispatched to the Kakaako outage after escalation.",
        relatedIds: ["UNIT-UST", "CASE-7782"],
        attachments: ["Dispatch packet"],
      },
    },
  },
  {
    label: "Resolve signal failure",
    description: "Traffic crew clears the signal controller fault.",
    event: {
      type: "upsert",
      feature: {
        ...INITIAL_UNIFIED_OPS_FEATURES[2],
        severity: "low",
        status: "resolved",
        etaMinutes: 0,
        impactScore: 8,
        updatedAt: "2026-05-05T18:04:00.000Z",
        summary: "Controller fault cleared and corridor timing returned to normal operations.",
        relatedIds: ["CASE-7783", "CLOSE-2003"],
      },
    },
  },
  {
    label: "Archive staged logistics",
    description: "The airport logistics crew is archived from the active feed.",
    event: {
      type: "delete",
      sourceId: CREW_SOURCE_ID,
      id: "CREW-55",
    },
  },
];
