/**
 * Shared client contract — canonical types and source factories that all
 * protocol adapters speak. Re-exported from `@honua/sdk-js/contract`.
 *
 * The runtime classes in `src/core/surfaces.ts` remain the implementation;
 * this module is the protocol-neutral vocabulary layered over them. See
 * `docs/shared-client-contract.md` for the full design.
 *
 * @module
 */

export type {
  AdapterFor,
  AdapterKind,
  AdapterTypeMap,
  AggregationFn,
  AggregationMetric,
  AggregationSpec,
  AttachmentAdd,
  AttachmentApi,
  AttachmentDelete,
  AttachmentEditOutcome,
  AttachmentGroup,
  AttachmentInfo,
  AttachmentQuery,
  AttachmentUpdate,
  CanonicalFeature,
  Capabilities,
  Capability,
  CapabilityPolicy,
  CreateDatasetOptions,
  Dataset,
  DatasetId,
  DegradedReason,
  EditEnvelope,
  EditOutcome,
  EditResult,
  FeatureId,
  MapBinding,
  PaginationSpec,
  Protocol,
  Query,
  RelatedGroup,
  RelatedQuery,
  RelatedResult,
  ResolveSourceContext,
  Result,
  SortSpec,
  Source,
  SourceDescriptor,
  SourceId,
  SourceLocator,
  SourceResolver,
  SourceSchema,
} from "./types.js";

export type {
  SpatialAggregationCacheMetadata,
  SpatialAggregationCategoryBucket,
  SpatialAggregationCategorySummarySpec,
  SpatialAggregationCategoryValue,
  SpatialAggregationCell,
  SpatialAggregationCellGeometry,
  SpatialAggregationContractFixture,
  SpatialAggregationCountSummarySpec,
  SpatialAggregationCountValue,
  SpatialAggregationDomainValue,
  SpatialAggregationGroupByMetadata,
  SpatialAggregationGroupBySpec,
  SpatialAggregationGroupedSummary,
  SpatialAggregationHistogramBucket,
  SpatialAggregationHistogramSummarySpec,
  SpatialAggregationHistogramValue,
  SpatialAggregationInclude,
  SpatialAggregationIndexModelMetadata,
  SpatialAggregationIndexSelection,
  SpatialAggregationIndexState,
  SpatialAggregationMetadata,
  SpatialAggregationMetricKind,
  SpatialAggregationMetricSummarySpec,
  SpatialAggregationMetricValue,
  SpatialAggregationPageInfo,
  SpatialAggregationPageRequest,
  SpatialAggregationProgressRefinement,
  SpatialAggregationProgressStatus,
  SpatialAggregationProgressiveState,
  SpatialAggregationRangeBucketSpec,
  SpatialAggregationRangeBucketValue,
  SpatialAggregationRangeSummarySpec,
  SpatialAggregationRangeValue,
  SpatialAggregationRequest,
  SpatialAggregationResolutionInput,
  SpatialAggregationResult,
  SpatialAggregationSummaryBag,
  SpatialAggregationSummaryBase,
  SpatialAggregationSummaryKind,
  SpatialAggregationSummaryMetadata,
  SpatialAggregationSummarySpec,
  SpatialAggregationSummaryValue,
  SpatialAggregationValidationIssue,
  SpatialAggregationValueType,
  SpatialAggregationViewport,
  SpatialAggregationWidgetKind,
  SpatialAggregationWidgetMetadata,
} from "./spatial-aggregation.js";

export {
  CAPABILITIES,
  PROTOCOL_DEFAULT_CAPABILITIES,
  PROTOCOLS,
  capabilities,
  intersectCapabilities,
  unionCapabilities,
} from "./types.js";

export { EditWorkflowSession, createEditSession, normalizeEditWorkflowFailures } from "./edit-session.js";
export type {
  CreateEditSessionOptions,
  EditAttachmentMutation,
  EditAttachmentMutationOutcome,
  EditFieldDomain,
  EditFieldDomainCodedValue,
  EditWorkflowCapabilityState,
  EditWorkflowCapabilitySummary,
  EditWorkflowConflictInfo,
  EditWorkflowConflictState,
  EditWorkflowFailure,
  EditWorkflowFailureKind,
  EditWorkflowField,
  EditWorkflowKind,
  EditWorkflowMetadata,
  EditWorkflowMetadataOptions,
  EditWorkflowOperation,
  EditWorkflowOptimisticHooks,
  EditWorkflowRelationship,
  EditWorkflowSnapshot,
  EditWorkflowStatus,
  EditWorkflowSubmitResult,
  EditWorkflowValidationError,
  EditWorkflowValidationResult,
  NormalizeEditWorkflowFailuresOptions,
} from "./edit-session.js";

export {
  SPATIAL_AGGREGATION_CAPABILITY,
  SPATIAL_AGGREGATION_METADATA_SCHEMA_VERSION,
  SPATIAL_AGGREGATION_SCHEMA_VERSION,
  assertValidSpatialAggregationRequest,
  isSpatialAggregationComplete,
  spatialAggregationProgress,
  spatialAggregationSummaryKindRequiresField,
  spatialAggregationWidgets,
  validateSpatialAggregationRequest,
} from "./spatial-aggregation.js";

export {
  ALL_CAPABILITIES,
  FIRST_PARTY_PROTOCOLS,
  createDataset,
  geoServicesFeatureSource,
  geoServicesGPServiceSource,
  geoServicesGeometryServiceSource,
  geoServicesImageSource,
  geoServicesMapServiceSource,
  odataSource,
  ogcFeaturesSource,
  ogcTilesSource,
  ogcMapsSource,
  stacSearchSource,
  wfsSource,
  wmsSource,
  wmtsSource,
} from "./source.js";

export type {
  IJobRun,
  JobError,
  JobProgress,
  JobResult,
  JobSnapshot,
  JobSnapshotListener,
  JobStatus,
} from "./jobs.js";
export { isJobTerminal } from "./jobs.js";
