/**
 * Shared client contract — canonical types and source factories that all
 * protocol adapters speak. Re-exported from `@honua/sdk-js/contract`.
 *
 * The runtime classes in `src/core/surfaces.ts` remain the implementation;
 * this module is the protocol-neutral vocabulary layered over them. See
 * `docs/shared-client-contract.md` for the full design.
 *
 * @module
 */

export type {
  AdapterFor,
  AdapterKind,
  AdapterTypeMap,
  AggregationFn,
  AggregationHistogramBucketAliases,
  AggregationHistogramBucketSpec,
  AggregationMetric,
  AggregationSpec,
  AggregationTimeIntervalSpec,
  AggregationTimeIntervalUnit,
  AggregationTimeSeriesAliases,
  AggregationTimeSeriesSpec,
  AttachmentAdd,
  AttachmentApi,
  AttachmentDelete,
  AttachmentEditOutcome,
  AttachmentGroup,
  AttachmentInfo,
  AttachmentQuery,
  AttachmentUpdate,
  CanonicalFeature,
  Capabilities,
  Capability,
  CapabilityPolicy,
  CreateDatasetOptions,
  Dataset,
  DatasetId,
  DegradedReason,
  EditEnvelope,
  EditOutcome,
  EditResult,
  FeatureId,
  MapBinding,
  PaginationSpec,
  Protocol,
  Query,
  RelatedGroup,
  RelatedQuery,
  RelatedResult,
  ResolveSourceContext,
  Result,
  SortSpec,
  Source,
  SourceAnalyticsCapabilities,
  SourceDescriptor,
  SourceFreshnessContract,
  SourceHistogramCapabilityMetadata,
  SourceId,
  SourceLocator,
  SourceResolver,
  SourceSchema,
  SourceTimeSeriesCapabilityMetadata,
} from "./types.js";

export type {
  SpatialAggregationCacheMetadata,
  SpatialAggregationCategoryBucket,
  SpatialAggregationCategorySummarySpec,
  SpatialAggregationCategoryValue,
  SpatialAggregationCell,
  SpatialAggregationCellGeometry,
  SpatialAggregationContractFixture,
  SpatialAggregationCountSummarySpec,
  SpatialAggregationCountValue,
  SpatialAggregationDomainValue,
  SpatialAggregationGroupByMetadata,
  SpatialAggregationGroupBySpec,
  SpatialAggregationGroupedSummary,
  SpatialAggregationHistogramBucket,
  SpatialAggregationHistogramSummarySpec,
  SpatialAggregationHistogramValue,
  SpatialAggregationInclude,
  SpatialAggregationIndexModelMetadata,
  SpatialAggregationIndexCoverageMetadata,
  SpatialAggregationIndexSelection,
  SpatialAggregationIndexState,
  SpatialAggregationMetadata,
  SpatialAggregationMetricKind,
  SpatialAggregationMetricSummarySpec,
  SpatialAggregationMetricValue,
  SpatialAggregationPageInfo,
  SpatialAggregationPageRequest,
  SpatialAggregationProgressRefinement,
  SpatialAggregationProgressStatus,
  SpatialAggregationProgressiveState,
  SpatialAggregationRangeBucketSpec,
  SpatialAggregationRangeBucketValue,
  SpatialAggregationRangeSummarySpec,
  SpatialAggregationRangeValue,
  SpatialAggregationRequest,
  SpatialAggregationResolutionInput,
  SpatialAggregationResult,
  SpatialAggregationResolvedWidgetSummary,
  SpatialAggregationSummaryBag,
  SpatialAggregationSummaryBase,
  SpatialAggregationSummaryKind,
  SpatialAggregationSummaryMetadata,
  SpatialAggregationSummarySpec,
  SpatialAggregationSummaryValue,
  SpatialAggregationValidationIssue,
  SpatialAggregationValueType,
  SpatialAggregationViewport,
  SpatialAggregationWidgetKind,
  SpatialAggregationWidgetMetadata,
  SpatialAggregationWidgetSummarySource,
} from "./spatial-aggregation.js";

export {
  CAPABILITIES,
  PROTOCOL_DEFAULT_CAPABILITIES,
  PROTOCOLS,
  capabilities,
  intersectCapabilities,
  unionCapabilities,
} from "./types.js";

export {
  ANALYTICS_SOURCE_SCHEMA_VERSION,
  analyticsSourceDegradedReason,
  analyticsSourceId,
  assessAnalyticsSourcePushdown,
  buildAnalyticsSourceCacheKey,
  defineIndexedSpatialSource,
  defineWarehouseQuerySource,
  defineWarehouseTableSource,
  defineWarehouseTilesetSource,
  isAnalyticsSourceDescriptor,
  normalizeAnalyticsSourceDescriptor,
} from "./analytics-sources.js";
export type {
  AnalyticsIndexCoverageDescriptor,
  AnalyticsIndexCoverageKind,
  AnalyticsIndexDescriptor,
  AnalyticsIndexHierarchy,
  AnalyticsSourceCacheIdentity,
  AnalyticsSourceCacheKeyOptions,
  AnalyticsSourceCachePolicy,
  AnalyticsSourceCapabilityMetadata,
  AnalyticsSourceDescriptor,
  AnalyticsSourceDescriptorBase,
  AnalyticsSourceFallbackMode,
  AnalyticsSourceFallbackPolicy,
  AnalyticsSourceKind,
  AnalyticsSourceProtocolEscapeHatch,
  AnalyticsSourcePushdownAssessment,
  AnalyticsSourcePushdownCapability,
  AnalyticsSourceRelationDescriptor,
  AnalyticsSourceSchemaVersion,
  AnalyticsSourceSqlDescriptor,
  AnalyticsSourceTilesetDescriptor,
  AnalyticsWarehouseProvider,
  IndexedSpatialSourceDescriptor,
  WarehouseQuerySourceDescriptor,
  WarehouseTableSourceDescriptor,
  WarehouseTilesetSourceDescriptor,
} from "./analytics-sources.js";

export type {
  WidgetCategoriesRequest,
  WidgetCategoriesResult,
  WidgetCategoryBucket,
  WidgetCountRequest,
  WidgetCountResult,
  WidgetFormulaRequest,
  WidgetFormulaResult,
  WidgetHistogramBin,
  WidgetHistogramRequest,
  WidgetHistogramResult,
  WidgetRangeRequest,
  WidgetRangeResult,
  WidgetSource,
  WidgetSourceCacheHints,
  WidgetSourceCacheMetadata,
  WidgetSourceExecutionMode,
  WidgetSourceFilterClause,
  WidgetSourceFreshnessContract,
  WidgetSourceModelKind,
  WidgetSourceOptions,
  WidgetSourceOrderBy,
  WidgetSourceProjection,
  WidgetSourceRequestBase,
  WidgetSourceResponseBase,
  WidgetSourceSchemaVersion,
  WidgetSourceValue,
  WidgetTimeSeriesBucket,
  WidgetTimeSeriesInterval,
  WidgetTimeSeriesIntervalUnit,
  WidgetTimeSeriesRequest,
  WidgetTimeSeriesResult,
  WidgetTopValueBucket,
  WidgetTopValuesRequest,
  WidgetTopValuesResult,
} from "./widget-source.js";
export { WIDGET_SOURCE_SCHEMA_VERSION, createWidgetSource, widgetSource } from "./widget-source.js";

export { EditWorkflowSession, createEditSession, normalizeEditWorkflowFailures } from "./edit-session.js";
export type {
  CreateEditSessionOptions,
  EditAttachmentMutation,
  EditAttachmentMutationOutcome,
  EditFieldDomain,
  EditFieldDomainCodedValue,
  EditWorkflowCapabilityState,
  EditWorkflowCapabilitySummary,
  EditWorkflowConflictInfo,
  EditWorkflowConflictState,
  EditWorkflowFailure,
  EditWorkflowFailureKind,
  EditWorkflowField,
  EditWorkflowKind,
  EditWorkflowMetadata,
  EditWorkflowMetadataOptions,
  EditWorkflowOperation,
  EditWorkflowOptimisticHooks,
  EditWorkflowRelationship,
  EditWorkflowSnapshot,
  EditWorkflowStatus,
  EditWorkflowSubmitResult,
  EditWorkflowValidationError,
  EditWorkflowValidationResult,
  NormalizeEditWorkflowFailuresOptions,
} from "./edit-session.js";
export { EditSketchWorkflowModel, createEditSketchWorkflow } from "./edit-sketch.js";
export type {
  EditAnnotationPersistenceHook,
  EditAnnotationPersistenceSnapshot,
  EditAnnotationPersistenceState,
  EditSketchCapabilityState,
  EditSketchStatus,
  EditSketchTool,
  EditSketchToolCapability,
  EditSketchToolCapabilityInput,
  EditSketchUndoSnapshot,
  EditSketchWorkflowOptions,
  EditSketchWorkflowSnapshot,
} from "./edit-sketch.js";

export {
  FEATURE_SERVER_H3_SPATIAL_AGGREGATION_INDEX_MODEL_ID,
  SPATIAL_AGGREGATION_CAPABILITY,
  SPATIAL_AGGREGATION_METADATA_SCHEMA_VERSION,
  SPATIAL_AGGREGATION_SCHEMA_VERSION,
  assertFeatureServerH3SpatialAggregationRequest,
  assertValidSpatialAggregationRequest,
  isSpatialAggregationComplete,
  resolveSpatialAggregationWidgetSummary,
  spatialAggregationProgress,
  spatialAggregationSummaryKindSupportedByFeatureServerH3,
  spatialAggregationSummaryKindRequiresField,
  spatialAggregationWidgets,
  validateFeatureServerH3SpatialAggregationRequest,
  validateSpatialAggregationRequest,
} from "./spatial-aggregation.js";

export {
  QUERY_TILE_SERVER_CONTRACT_VERSION,
  QUERY_TILE_SERVER_FEATURE_DETAIL_ROUTE_TEMPLATE,
  QUERY_TILE_SERVER_RESPONSE_HEADERS,
  QUERY_TILE_SERVER_ROUTE_PREFIX,
  QUERY_TILE_SERVER_SOURCE_ROUTE_TEMPLATE,
  QUERY_TILE_SERVER_TILEJSON_ROUTE_TEMPLATE,
  QUERY_TILE_SERVER_TILE_ROUTE_TEMPLATE,
  buildQueryTileCacheKey,
  buildQueryTileFeatureDetailQuery,
  buildQueryTileServerPath,
  buildQueryTileServerUrl,
  defineQueryTileSource,
  loadQueryTileFeatureDetail,
  mapQueryTileFeatureIdentity,
  normalizeQueryTileKey,
  normalizeQueryTileSourceDescriptor,
  parseQueryTileFeatureDetailResponse,
  parseQueryTileJson,
  parseQueryTileServerErrorResponse,
  queryTileServerRequestParamsFromDescriptor,
  queryTileKeyString,
  stableJson,
} from "./tiles.js";
export type {
  DefineQueryTileSourceOptions,
  QueryTileCacheIdentityDescriptor,
  QueryTileCacheKeyOptions,
  QueryTileCachePolicy,
  QueryTileEndpointDescriptor,
  QueryTileFallbackMode,
  QueryTileFallbackPolicy,
  QueryTileFeatureDetailOptions,
  QueryTileFeatureIdentityContext,
  QueryTileFeatureIdentityDescriptor,
  QueryTileFeatureIdentityMapper,
  QueryTileFeatureIdentityTarget,
  QueryTileFormat,
  QueryTileFeatureDetailResponse,
  QueryTileJson,
  QueryTileJsonVectorLayer,
  QueryTileKey,
  QueryTileKeyInput,
  QueryTileProjectionDescriptor,
  QueryTileScheme,
  QueryTileServerCachePolicyDescriptor,
  QueryTileServerCacheValidators,
  QueryTileServerContractFixture,
  QueryTileServerDegradation,
  QueryTileServerDegradationCode,
  QueryTileServerDegradationSeverity,
  QueryTileServerError,
  QueryTileServerErrorCode,
  QueryTileServerErrorResponse,
  QueryTileServerFeatureIdentityDescriptor,
  QueryTileServerLimitDescriptor,
  QueryTileServerRequestParameters,
  QueryTileServerRouteKind,
  QueryTileServerRouteOptions,
  QueryTileServerTileJsonMetadata,
  QueryTileSpatialReference,
  QueryTileSpatialReferenceDescriptor,
  QueryTileExtentDescriptor,
  QueryTileSourceDescriptor,
} from "./tiles.js";

export {
  ALL_CAPABILITIES,
  FIRST_PARTY_PROTOCOLS,
  createDataset,
  geoServicesFeatureSource,
  geoServicesGPServiceSource,
  geoServicesGeometryServiceSource,
  geoServicesImageSource,
  geoServicesMapServiceSource,
  odataSource,
  ogcFeaturesSource,
  ogcTilesSource,
  ogcMapsSource,
  ogcRecordsSource,
  stacSearchSource,
  wfsSource,
  wmsSource,
  wmtsSource,
} from "./source.js";

export type {
  IJobRun,
  JobError,
  JobProgress,
  JobResult,
  JobSnapshot,
  JobSnapshotListener,
  JobStatus,
} from "./jobs.js";
export { isJobTerminal } from "./jobs.js";
