/**
 * `@honua/sdk-js/query-planner` — deterministic query IR, explain plans, and
 * bounded execution for the protocol-neutral contract.
 *
 * Planning is synchronous and side-effect free: it uses a caller-supplied
 * descriptor/capability snapshot and never fetches metadata or result rows.
 * Execution is separate and validates the accepted fingerprint and source
 * context before invoking a `Source`.
 *
 * @experimental
 * @packageDocumentation
 */

export { canonicalStringify, sha256, toJsonValue } from "./canonical.js";
export { columnarBatchIdentityFromPlan } from "./columnar-plan.js";
export type { ColumnarBatchIdentityFromPlanOptions } from "./columnar-plan.js";
export {
  COLUMNAR_REPRESENTATION_ENCODINGS,
  COLUMNAR_REPRESENTATION_MIN_BYTES,
  COLUMNAR_REPRESENTATION_MIN_ROWS,
  createQueryPlanRepresentationDecision,
  isColumnarRepresentationEncoding,
} from "./representation.js";
export { compileDuckDbQuery, compileDuckDbQueryV2, compileSemanticDuckDbQuery } from "./duckdb.js";
export { executeQueryPlan } from "./executor.js";
export { compileGeoServicesQuery, compileSemanticGeoServicesQuery } from "./geoservices.js";
export { compileGrpcQuery, compileSemanticGrpcQuery } from "./grpc.js";
export { compileOgcApiFeaturesQuery, compileSemanticOgcApiFeaturesQuery } from "./ogc-features.js";
export { odataProtocolModule } from "./odata-protocol-module.js";
export type {
  OdataProtocolExecutionQuery,
  OdataProtocolModule,
  OdataProtocolQueryBinding,
} from "./odata-protocol-module.js";
export { compileOdataQuery } from "./odata-v1.js";
export { compileSemanticOdataQuery } from "./odata.js";
export { HonuaWfsProtocolError, wfsProtocolModule } from "./wfs-protocol-module.js";
export type {
  WfsProtocolErrorReason,
  WfsProtocolExecutionQuery,
  WfsProtocolModule,
  WfsProtocolQueryBinding,
} from "./wfs-protocol-module.js";
export { compileWfsQuery } from "./wfs-v1.js";
export { compileSemanticWfsQuery } from "./wfs.js";
export {
  canonicalizeQuery,
  createGeoParquetQueryIr,
  createQueryIr,
  hashQueryIr,
  queryFromCanonical,
} from "./ir.js";
export {
  explainQuery,
  hashQueryPlan,
  migrateGeoParquetQueryPlanV1,
  parseQueryPlan,
  queryPlanCacheKey,
  serializeQueryPlan,
} from "./planner.js";
export {
  QUERY_RESOURCE_HANDLE_KIND,
  QUERY_RESOURCE_HANDLE_VERSION,
  createGeoParquetResourceHandle,
  createGeoParquetResourceRegistry,
  hashGeoParquetResourceHandle,
  parseGeoParquetResourceHandle,
  resolveGeoParquetResource,
} from "./resource.js";
export {
  SEMANTIC_QUERY_CANONICAL_KIND,
  SEMANTIC_QUERY_CANONICAL_VERSION,
  SEMANTIC_QUERY_HASH_DOMAIN,
  canonicalSemanticQueryBytes,
  hashSemanticQuery,
  serializeCanonicalSemanticQuery,
} from "./semantic-canonical.js";
export { legacyWhereToNativeFilter } from "./semantic-compat.js";
export type {
  SemanticCompilationResult,
  SemanticCompilerDiagnostic,
  SemanticCompilerFidelity,
  SemanticCompilerLoss,
  SemanticCompilerUnsupportedCode,
  SemanticSqlParameter,
} from "./semantic-compiler.js";
export type { SemanticCompilerFieldMapping } from "./semantic-literals.js";
export { semanticFilterFromCql2Json, semanticFilterToCql2Json } from "./cql2-json.js";
export {
  MAX_SEMANTIC_QUERY_BYTES,
  MAX_SEMANTIC_QUERY_COLLECTION_ITEMS,
  MAX_SEMANTIC_QUERY_DEPTH,
  MAX_SEMANTIC_QUERY_NODES,
  MAX_SEMANTIC_QUERY_TEXT_BYTES,
  createSemanticQueryBuilder,
  defineSemanticQuery,
  defineSpatialNode,
  parseSemanticQuery,
  temporalLiteral,
} from "./semantic.js";
export type { SemanticQueryBuilder } from "./semantic.js";
export type {
  AggregateMetric,
  BuiltInNativeDialect,
  CanonicalSemanticQueryOptions,
  Cql2JsonExpression,
  Cql2JsonInterchangeOptions,
  ComparisonNode,
  CountMetric,
  DistanceOperand,
  DistanceSpatialPredicate,
  DistanceUnit,
  EqualityOperator,
  ExtremumMetric,
  FieldName,
  FirstPageRequest,
  GeometryFieldName,
  GeometryProjectionFor,
  GroupableFieldName,
  ListNode,
  LegacyWhereDialectFor,
  LegacyWhereProtocol,
  LiteralNode,
  NativeDialectFor,
  NativeFilter,
  NativePayloadFor,
  NullNode,
  NumericFieldName,
  NumericMetric,
  OffsetPageRequest,
  OrderableFieldName,
  OrderedComparisonOperator,
  OutputCrsFor,
  ParseSemanticQueryOptions,
  PatternNode,
  PropertyNode,
  QueryFilter,
  QueryLiteral,
  RangeNode,
  ScalarFieldName,
  SemanticAggregateQuery,
  SemanticFeatureQuery,
  SemanticFilter,
  SemanticPageRequest,
  SemanticQuery,
  SemanticSort,
  SourceSpatiality,
  SpatialNode,
  SpatialPredicate,
  SpatialityForSchema,
  StringFieldName,
  TemporalFieldName,
  TemporalLiteralNode,
  TemporalNode,
  TemporalPredicate,
  TemporalValue,
  TopologicalSpatialPredicate,
} from "./semantic-types.js";
export type {
  SemanticOdataCompileOptions,
  SemanticOdataCompiledQueryV1,
  SemanticOdataOutputGeometry,
  SemanticOdataSourceIdentity,
  SemanticOdataSpatialFunction,
} from "./odata.js";
export type {
  SemanticDuckDbCompileOptions,
  SemanticDuckDbCompiledQueryV1,
  SemanticDuckDbGeometrySource,
  SemanticDuckDbOutputGeometry,
  SemanticDuckDbSpatialCompilation,
} from "./duckdb.js";
export type {
  SemanticGeoServicesCompileOptions,
  SemanticGeoServicesCompiledQueryV1,
  SemanticGeoServicesGeometry,
  SemanticGeoServicesProtocol,
  SemanticGeoServicesSourceIdentity,
  SemanticGeoServicesSpatialReference,
  SemanticGeoServicesSpatialRelationship,
} from "./geoservices.js";
export type {
  SemanticGrpcCompileOptions,
  SemanticGrpcCompiledQueryV1,
  SemanticGrpcCoordinate,
  SemanticGrpcCoordinateSequence,
  SemanticGrpcGeometry,
  SemanticGrpcSourceIdentity,
  SemanticGrpcSpatialReference,
  SemanticGrpcSpatialRelationship,
} from "./grpc.js";
export type {
  Cql2FilterLanguage,
  OgcApiFeaturesFilterConformanceEvidence,
  SemanticOgcApiFeaturesCompileOptions,
  SemanticOgcApiFeaturesCompiledQueryV1,
  SemanticOgcApiFeaturesSourceIdentity,
} from "./ogc-features.js";
export type {
  SemanticWfsCompileOptions,
  SemanticWfsCompiledQueryV1,
  SemanticWfsSourceIdentity,
  Wfs20FilterCapabilitiesEvidence,
} from "./wfs.js";
export {
  COLUMNAR_WORKER_CANCEL_KIND,
  COLUMNAR_WORKER_ERROR_KIND,
  COLUMNAR_WORKER_PROGRESS_KIND,
  COLUMNAR_WORKER_PROTOCOL_VERSION,
  COLUMNAR_WORKER_REQUEST_KIND,
  COLUMNAR_WORKER_RESULT_KIND,
  ColumnarBatchLease,
  DEFAULT_GEOARROW_AGGREGATE_MAX_GROUPS,
  DEFAULT_GEOARROW_AGGREGATE_YIELD_ROWS,
  GEOARROW_AGGREGATE_ABORT_CHECK_ROWS,
  GEOARROW_AGGREGATE_MAX_GRID_CELL_INDEX,
  GEOARROW_SPEC_VERSION,
  HONUA_GEOARROW_AGGREGATE_LAYOUT_VERSION,
  HONUA_GEOARROW_LAYOUT_VERSION,
  HonuaGeoArrowError,
  HonuaColumnarWorkerError,
  createColumnarBatch,
  createColumnarWorkerSession,
  createGeoArrowAggregateOperation,
  createGeoArrowBatch,
  createGeoArrowReprojectOperation,
  readGeoArrowAggregateBatch,
  deserializeGeoArrowBatch,
  decodeGeoArrowBatch,
  fromApacheArrowRecordBatch,
  inspectGeoArrowBatch,
  inspectColumnarBatch,
  leaseColumnarBatch,
  loadApacheArrow,
  startColumnarWorkerHost,
  serializeGeoArrowBatch,
  toApacheArrowRecordBatch,
} from "../columnar/index.js";
export {
  COLUMNAR_PATCH_ABORT_CHECK_ROWS,
  COLUMNAR_PATCH_KIND,
  COLUMNAR_PATCH_VERSION,
  DEFAULT_COLUMNAR_PATCH_MAX_CAPACITY_UTILIZATION,
  DEFAULT_COLUMNAR_PATCH_MAX_OPERATIONS,
  DEFAULT_COLUMNAR_PATCH_MAX_TOMBSTONE_OVERLAY_BYTES,
  DEFAULT_COLUMNAR_PATCH_MAX_TOMBSTONE_RATIO,
  DEFAULT_COLUMNAR_PATCH_MAX_VERTEX_GROWTH_RATIO,
  HONUA_COLUMNAR_PATCH_LAYOUT_VERSION,
  HonuaColumnarPatchError,
  applyColumnarPatch,
  columnarPatchLiveMask,
  createColumnarPatch,
  createColumnarPatchOperation,
  createPatchableGeoArrowBatch,
  decodePatchedGeoArrowBatch,
  inspectColumnarPatchState,
} from "../columnar/index.js";
export type {
  ApplyColumnarPatchOptions,
  ApplyColumnarPatchOutcomeV1,
  ColumnarPatchAppendV1,
  ColumnarPatchAppliedInPlaceV1,
  ColumnarPatchCapacityV1,
  ColumnarPatchCursorV1,
  ColumnarPatchDeleteV1,
  ColumnarPatchGeometry,
  ColumnarPatchMetricsV1,
  ColumnarPatchOperationV1,
  ColumnarPatchRebuildOptions,
  ColumnarPatchRebuildReason,
  ColumnarPatchRebuiltV1,
  ColumnarPatchRejectedV1,
  ColumnarPatchRejectionCode,
  ColumnarPatchReserveV1,
  ColumnarPatchStateV1,
  ColumnarPatchThresholds,
  ColumnarPatchUpdateV1,
  ColumnarPatchV1,
  CreateColumnarPatchInput,
  CreateColumnarPatchOperationOptions,
  CreatePatchableGeoArrowBatchOptions,
  CreatedPatchableGeoArrowBatch,
  DecodedPatchedGeoArrowBatch,
  PatchableGeoArrowBatchMetrics,
} from "../columnar/index.js";
export {
  COLUMNAR_BATCH_CACHE_CONFORMANCE_CASES,
  DEFAULT_COLUMNAR_BATCH_CACHE_MAX_AGE_MS,
  DEFAULT_COLUMNAR_BATCH_CACHE_MAX_RECORDS,
  DEFAULT_COLUMNAR_BATCH_CACHE_QUOTA_BYTES,
  GEOARROW_ENVELOPE_MIGRATIONS,
  HONUA_COLUMNAR_BATCH_CACHE_CONFORMANCE_KIND,
  HONUA_COLUMNAR_BATCH_CACHE_CONFORMANCE_VERSION,
  HONUA_COLUMNAR_BATCH_CACHE_FORMAT,
  HONUA_GEOARROW_ENVELOPE_KIND,
  HONUA_GEOARROW_ENVELOPE_VERSION,
  MAX_COLUMNAR_BATCH_CACHE_MAX_AGE_MS,
  MAX_COLUMNAR_BATCH_CACHE_MAX_RECORDS,
  MAX_COLUMNAR_BATCH_CACHE_QUOTA_BYTES,
  columnarAuthorizationScopeDigest,
  columnarBatchCacheFixtureBatch,
  columnarBatchCacheFixtureIdentity,
  columnarBatchCacheKey,
  columnarBatchCacheLegacyEntry,
  columnarBatchCacheOrderingDigest,
  createColumnarBatchCache,
  createIndexedDbColumnarBatchCacheStorage,
  createMemoryColumnarBatchCacheStorage,
  planColumnarBatchCacheAdmission,
  planGeoArrowEnvelopeMigration,
  readableGeoArrowEnvelopeVersions,
  runColumnarBatchCacheConformance,
} from "../columnar/index.js";
export type {
  ColumnarBatchCacheAdmissionV1,
  ColumnarBatchCacheConformanceCaseResultV1,
  ColumnarBatchCacheConformanceOptions,
  ColumnarBatchCacheConformanceReportV1,
  ColumnarBatchCacheDiagnosticV1,
  ColumnarBatchCacheEntryV1,
  ColumnarBatchCacheFreshnessV1,
  ColumnarBatchCacheHandle,
  ColumnarBatchCacheMissReason,
  ColumnarBatchCacheOptions,
  ColumnarBatchCacheReadOptions,
  ColumnarBatchCacheReadV1,
  ColumnarBatchCacheRecordV1,
  ColumnarBatchCacheRefusalReason,
  ColumnarBatchCacheStaleReason,
  ColumnarBatchCacheStorage,
  ColumnarBatchCacheWriteOptions,
  ColumnarBatchCacheWriteV1,
  ColumnarTelemetry,
  ColumnarTelemetryIdentityV1,
  ColumnarTelemetryKind,
  ColumnarTelemetryOptions,
  ColumnarTelemetrySpan,
  ColumnarTelemetrySpanResult,
  GeoArrowEnvelopeMigrationPlanV1,
  GeoArrowEnvelopeMigrationRefusal,
  GeoArrowEnvelopeMigrationV1,
  IndexedDbColumnarBatchCacheStorageOptions,
} from "../columnar/index.js";
export {
  COLUMNAR_BATCH_KIND,
  COLUMNAR_BATCH_VERSION,
  COLUMNAR_TRANSFER_KIND,
  DEFAULT_COLUMNAR_BATCH_MAX_BACKING_BYTES,
  DEFAULT_COLUMNAR_BATCH_MAX_BUFFER_VIEWS,
  DEFAULT_COLUMNAR_BATCH_MAX_METADATA_ENTRIES,
  DEFAULT_COLUMNAR_BATCH_MAX_ROWS,
  DEFAULT_COLUMNAR_BATCH_MAX_SCHEMA_NODES,
  DEFAULT_COLUMNAR_BATCH_MAX_STRING_BYTES,
  HonuaColumnarTransferError,
} from "../columnar/index.js";
export type {
  ApacheArrowAdapterMetrics,
  ApacheArrowAdapterOptions,
  ApacheArrowDataLike,
  ApacheArrowFieldLike,
  ApacheArrowModuleImporter,
  ApacheArrowModuleLike,
  ApacheArrowRecordBatchLike,
  ApacheArrowRecordBatchResult,
  ApacheArrowTypeLike,
  ApacheArrowVectorLike,
  ColumnarBatchLeaseState,
  ColumnarBatchIdentityV1,
  ColumnarBatchLimits,
  ColumnarBatchMetrics,
  ColumnarBatchV1,
  ColumnarBufferRole,
  ColumnarBufferV1,
  ColumnarFieldV1,
  ColumnarFreshnessV1,
  ColumnarOrderingKeyV1,
  ColumnarOrderingV1,
  ColumnarSchemaV1,
  ColumnarTransferErrorCode,
  ColumnarTransferMessageV1,
  ColumnarTransferOptions,
  ColumnarTransferReceipt,
  ColumnarTransferTarget,
  ColumnarTypeV1,
  CreateColumnarBatchInput,
  ColumnarWorkerCancelV1,
  ColumnarWorkerErrorCode,
  ColumnarWorkerErrorV1,
  ColumnarWorkerExecutionProgress,
  ColumnarWorkerExecutionResult,
  ColumnarWorkerFactory,
  ColumnarWorkerFaultEvent,
  ColumnarWorkerHost,
  ColumnarWorkerMessageEvent,
  ColumnarWorkerOperation,
  ColumnarWorkerOperationContext,
  ColumnarWorkerProgressV1,
  ColumnarWorkerRequestV1,
  ColumnarWorkerResultV1,
  ColumnarWorkerSession,
  ColumnarWorkerSessionState,
  ColumnarWorkerStreamOrdering,
  ColumnarWorkerTransport,
  CreateColumnarWorkerSessionOptions,
  ExecuteColumnarWorkerOperationOptions,
  CreateGeoArrowAggregateOperationOptions,
  CreateGeoArrowBatchInput,
  CreateGeoArrowReprojectOperationOptions,
  CreatedGeoArrowBatch,
  GeoArrowAggregateDictionaryGroupSpec,
  GeoArrowAggregateGridGroupSpec,
  GeoArrowAggregateGroupSpec,
  GeoArrowAggregateMetricKind,
  GeoArrowAggregateMetricSpec,
  GeoArrowAggregateNullKeyPolicy,
  GeoArrowAggregateNumericColumn,
  GeoArrowAggregateResult,
  GeoArrowAggregateRow,
  GeoArrowAggregateSource,
  GeoArrowAggregateTemporalGroupSpec,
  GeoArrowAggregateTruncationUnit,
  GeoArrowBatchSerializationResult,
  DecodedGeoArrowBatch,
  DecodedGeoArrowRow,
  GeoArrowBatchInspection,
  GeoArrowConversionLimits,
  GeoArrowConversionMetrics,
  GeoArrowSerializationMetrics,
  GeoArrowSerializationOptions,
  GeoArrowCoordinateLayout,
  GeoArrowCrs,
  GeoArrowDictionaryBuffers,
  GeoArrowDictionaryColumnInput,
  GeoArrowDimensions,
  GeoArrowEdges,
  GeoArrowFeatureIdColumnInput,
  GeoArrowGeometryBuffers,
  GeoArrowGeometryColumnInput,
  GeoArrowGeometryKind,
  GeoArrowLineString,
  GeoArrowLineStringColumnInput,
  GeoArrowPoint,
  GeoArrowPointColumnInput,
  GeoArrowPolygon,
  GeoArrowPolygonColumnInput,
  GeoArrowPosition,
  GeoArrowTemporalBuffers,
  GeoArrowTemporalColumnInput,
  GeoArrowTimestampUnit,
  FromApacheArrowRecordBatchOptions,
  GeoArrowBatchFromApacheResult,
  HonuaGeoArrowErrorCode,
  LoadApacheArrowOptions,
  StartColumnarWorkerHostOptions,
} from "../columnar/index.js";
export {
  HonuaQueryPlanExecutionError,
  HonuaQueryPlanningError,
  MAX_LOCAL_MATERIALIZATION_ROWS,
  QUERY_IR_KIND,
  QUERY_IR_VERSION,
  QUERY_PLAN_KIND,
  QUERY_PLAN_DIAGNOSTICS_VERSION,
  QUERY_PLANNER_VERSION,
  QUERY_PLAN_VERSION,
  QUERY_IR_V2_VERSION,
  QUERY_PLAN_V2_VERSION,
} from "./types.js";
export type {
  CanonicalQuery,
  CanonicalSpatialFilter,
  DuckDbCompiledQueryV1,
  DuckDbCompiledQueryV2,
  DuckDbGeometryEncoding,
  ExecuteQueryPlanOptions,
  ExplainGeoParquetQueryOptions,
  ExplainQueryOptions,
  GeoParquetEffectiveSchemaFieldV1,
  GeoParquetRemoteQueryPlanStepV2,
  GeoServicesCompiledQueryV1,
  GrpcCompiledQueryV1,
  GrpcSpatialRelationship,
  GrpcStatisticType,
  JsonPrimitive,
  JsonValue,
  LocalAggregatePlanStep,
  OgcApiFeaturesCompiledQueryV1,
  OdataCompiledQueryV1,
  OdataProtocolCompiledQueryV1,
  QueryExecutionPlan,
  QueryExecutionPlanV1,
  QueryExecutionPlanV2,
  QueryFallbackPolicy,
  QueryIrGeoparquetIdentity,
  QueryIrGeoparquetResourceIdentity,
  QueryIrSourceIdentity,
  QueryIrSourceIdentityV2,
  QueryIrV1,
  QueryIrV2,
  QueryPlanExecution,
  QueryPlanExecutionErrorCode,
  QueryPlanExecutor,
  QueryPlanningErrorCode,
  QueryPlanningEstimates,
  QueryPlanBoundConfidence,
  QueryPlanBoundSource,
  QueryPlanBoundsV1,
  QueryPlanCacheAction,
  QueryPlanCacheDecisionV1,
  QueryPlanCacheFreshness,
  QueryPlanCacheOptions,
  QueryPlanCachePolicy,
  QueryPlanDiscoveryContext,
  QueryPlanDiscoveryState,
  QueryPlanExecutionFailureReason,
  QueryPlanExecutionMode,
  QueryPlanFidelity,
  QueryPlanFidelityLoss,
  QueryPlanProvenanceV1,
  QueryPlanQuantityBound,
  QueryPlanRepresentation,
  QueryPlanRepresentationDecisionV1,
  QueryPlanRepresentationInputsV1,
  QueryPlanRepresentationReason,
  QueryPlanRepresentationRequest,
  QueryPlanStepProvenanceV1,
  QueryPlanValidatorInput,
  QueryPlanValidatorKind,
  QueryPlanValidityV1,
  QueryPlanWarning,
  QueryPlanWarningCode,
  RemoteCompiledQueryV1,
  QueryPlanStep,
  QueryPlanStepV2,
  RemoteQueryPlanStep,
  WfsCompiledQueryV1,
  WfsProtocolCompiledQueryV1,
} from "./types.js";
export type {
  CreateGeoParquetResourceHandleInput,
  GeoParquetResolverResourceReferenceV1,
  GeoParquetResourceHandleV1,
  GeoParquetResourceRegistry,
  GeoParquetResourceRegistryOptions,
  GeoParquetResourceResolutionContext,
  GeoParquetResourceResolver,
  RegisterGeoParquetResourceInput,
  ResolvedGeoParquetResource,
} from "./resource.js";
