/**
 * `@honua/sdk-js/scene-workspace` — framework-neutral 3D scene workspace state.
 *
 * @experimental This entrypoint is not yet covered by the SDK's semver contract
 *   — the surface may change in any minor release prior to `1.0.0`.
 * @module
 */

export {
  createSceneWorkspace,
  emptySceneWorkspaceState,
  reduceSceneWorkspaceState,
  sceneWorkspaceIntentFromAdapterEvent,
  selectSceneDiagnosticsByStatus,
  selectSceneEvidenceForFeature,
  selectScenePrimitivesByKind,
  selectSceneVisibleLayers,
} from "./workspace.js";
export {
  SCENE_STATE_SYNC_KIND,
  SCENE_STATE_SYNC_SLICES,
  SCENE_STATE_SYNC_VERSION,
  HonuaSceneStateSyncError,
  createSceneStateSynchronizer,
  defaultSceneStateSyncMappings,
} from "./state-sync.js";
export type {
  CreateSceneStateSynchronizerOptions,
  SceneStateSyncAttributionValue,
  SceneStateSyncDelivery,
  SceneStateSyncDiagnostic,
  SceneStateSyncDiagnosticCode,
  SceneStateSyncEnvelope,
  SceneStateSyncErrorCode,
  SceneStateSyncEvent,
  SceneStateSyncFidelity,
  SceneStateSyncIdentity,
  SceneStateSyncInput,
  SceneStateSyncMapping,
  SceneStateSyncMappings,
  SceneStateSyncOrigin,
  SceneStateSyncPort,
  SceneStateSyncRealtimeValue,
  SceneStateSyncRenderer,
  SceneStateSyncSlice,
  SceneStateSyncSnapshot,
  SceneStateSyncValueMap,
  SceneStateSynchronizer,
} from "./state-sync.js";
export {
  MAPLIBRE_SCENE_CAPABILITIES,
  RENDERER_WGS84_SPATIAL_CAPABILITIES,
  applyMapLibreScenePrimitives,
  createMapLibreSceneAdapter,
  createSceneRuntimeAdapter,
  diagnoseScenePrimitive,
  diagnoseScenePrimitives,
  summarizeDiagnosticStatus,
  toMapLibreExtrusionLayer,
  toMapLibreTerrainPatch,
} from "./primitives.js";
export {
  CESIUM_SCENE_CAPABILITIES,
  addCesium3DTileset,
  addCesiumImageryLayer,
  addCesiumModel,
  applyCameraStateToCesiumCamera,
  applyCesiumScenePrimitives,
  applyCesiumTerrain,
  applyHonua3DStyle,
  applyTilesetServerStyle,
  cameraStateToCesiumView,
  cesiumCameraToSceneState,
  createCesiumSceneAdapter,
  fetchHonua3DStyleSpec,
  honua3DStyleToCesiumStyleOptions,
  loadHonua3DStyle,
  modelLayerToCesiumPlacement,
  pickCesiumFeatureAttributes,
  readHonua3DStyleDescriptor,
  resolveCesiumModelScale,
  resolveHonua3DStyleUri,
  resolvePickedFeatureAttributes,
  setTilesetStyle,
} from "./cesium-adapter.js";
export {
  DEFAULT_SCENE_MOUNT_LAYER_LIMIT,
  HonuaCesiumSceneMountError,
  mountScenePrimitivesToCesium,
} from "./cesium-mount.js";
export type {
  ApplyMountedScenePrimitivesOptions,
  CesiumSceneMountErrorCode,
  CesiumSceneMountState,
  MountedCesiumScenePrimitives,
  MountedScenePrimitiveApplyResult,
  MountScenePrimitivesToCesiumOptions,
} from "./cesium-mount.js";
export type {
  AddCesium3DTilesetOptions,
  CesiumCameraLike,
  CesiumCameraView,
  CesiumHeadingPitchRollRadians,
  CesiumImageryLayerCollectionLike,
  CesiumImageryLayerLike,
  CesiumImageryProviderLike,
  CesiumLayerHandle,
  CesiumModelLike,
  CesiumModelPlacement,
  CesiumPrimitiveCollectionLike,
  CesiumSceneLike,
  CesiumSceneMaterializationOptions,
  CesiumSceneRuntimeTarget,
  CesiumTilesetLike,
  Honua3DStyleConditions,
  Honua3DStyleDescriptor,
  Honua3DStyleSpec,
} from "./cesium-adapter.js";
export {
  DEFAULT_CESIUM_ENTITY_LIMIT,
  HonuaCesiumEntityAdapterError,
  mountSourceToCesium,
  projectSourceToCesium,
} from "./source-to-cesium.js";
export type {
  CesiumEntityAdapterErrorCode,
  CesiumEntityCollectionTarget,
  CesiumEntityDiagnostic,
  CesiumEntityDiagnosticCode,
  CesiumEntityGeometry,
  CesiumEntityInterval,
  CesiumEntityProjection,
  CesiumEntityProjectionItem,
  CesiumEntityPositionSample,
  CesiumEntityRuntimeLoader,
  CesiumEntityRuntimeModule,
  CesiumEntityTimeOptions,
  CesiumEntityWorkflowState,
  MountedCesiumEntitySource,
  MountSourceToCesiumOptions,
  ProjectSourceToCesiumOptions,
} from "./source-to-cesium.js";
export {
  buildElevationProfilePath,
  buildLineOfSightBody,
  buildViewshedBody,
  formatMeasurementLabel,
  haversineMeters,
  measureScenePositions,
  pathLengthMeters,
  positionsToWktLineString,
  renderElevationProfilePolyline,
  renderLineOfSight,
  renderMeasurement,
  renderViewshed,
  requestElevationProfile,
  requestLineOfSight,
  requestViewshed,
  slantDistanceMeters,
  sphericalPolygonAreaSquareMeters,
} from "./analysis-widgets.js";
export type {
  CesiumEntityCollectionLike,
  ElevationProfileRequest,
  ElevationProfileResult,
  ElevationProfileSample,
  LineOfSightRequest,
  LineOfSightResult,
  SceneAnalysisCesiumModule,
  SceneAnalysisOverlay,
  SceneAnalysisPosition,
  SceneAnalysisRequestExecutor,
  SceneMeasurement,
  ViewshedRequest,
  ViewshedResult,
  ViewshedSample,
} from "./analysis-widgets.js";
export {
  getScene,
  listScenes,
  normalizeScene,
  resolveSceneTilesetUrl,
  sceneCameraPrimitive,
  sceneLayerStates,
  sceneTerrainPrimitive,
  sceneTilesetPrimitive,
  sceneToRuntimePrimitives,
  sceneViewpointBookmarks,
} from "./scene-discovery.js";
export type {
  HonuaScene,
  SceneDiscoveryRequestExecutor,
  SceneExtent3D,
  SceneViewpoint,
} from "./scene-discovery.js";
export { SceneView } from "./scene-view.js";
export type {
  SceneViewEvent,
  SceneViewEventListener,
  SceneViewOptions,
  SceneViewRequestExecutor,
} from "./scene-view.js";
export { SCENE_WORKSPACE_SLICES } from "./types.js";
export type {
  MapLibreExtrusionLayerSpecification,
  MapLibreSceneRuntimeTarget,
  MapLibreTerrainOptions,
  MapLibreTerrainPatch,
  MapLibreTerrainSourceSpecification,
  SceneCacheMetadata,
  SceneCameraPrimitive,
  SceneElevationSourcePrimitive,
  SceneElevationSourceProtocol,
  SceneExtrusionPrimitive,
  SceneExtrusionValue,
  SceneGroundPrimitive,
  SceneImageryLayerPrimitive,
  SceneImagerySourceProtocol,
  SceneLayerMetadataPrimitive,
  SceneModelFormat,
  SceneModelLayerPrimitive,
  ScenePointCloudShading,
  ScenePrimitiveApplyResult,
  ScenePrimitiveDiagnostic,
  ScenePrimitiveDiagnosticSeverity,
  ScenePrimitiveStatus,
  SceneRendererKind,
  SceneRuntimeAdapter,
  SceneRuntimeCapabilities,
  SceneRuntimePrimitive,
  SceneRuntimePrimitiveKind,
  SceneSpatialCapabilities,
  SceneSpatialFidelity,
  SceneSpatialReference,
} from "./primitives.js";
export type {
  SceneBookmark,
  SceneCameraState,
  SceneDetailState,
  SceneEvidenceReference,
  SceneLayerState,
  SceneRealtimeState,
  SceneTimelineState,
  SceneWorkspace,
  SceneWorkspaceAdapterEvent,
  SceneWorkspaceChangeEvent,
  SceneWorkspaceHistoryEntry,
  SceneWorkspaceIntent,
  SceneWorkspaceListener,
  SceneWorkspaceSlice,
  SceneWorkspaceSnapshot,
  SceneWorkspaceState,
  SceneWorkspaceUnsubscribe,
} from "./types.js";
