import { createHonuaCacheState } from "@honua/sdk-js/honua";

import type { RunnerDataset, RunnerFeature } from "./types.js";

const GENERATED_AT = "2026-05-07T18:30:00Z";
const SR = { wkid: 4326 };

export function createFixtureGeoprocessingDataset(): RunnerDataset {
  return {
    workspaceId: "honua-gp-job-runner-fixture",
    resultSourceId: "honua-cloud:gp-runner-results",
    generatedAt: GENERATED_AT,
    aois: [
      {
        id: "urban-core",
        title: "Urban core",
        extent: { xmin: -157.88, ymin: 21.28, xmax: -157.79, ymax: 21.34, spatialReference: SR },
        geometryLabel: "AOI polygon, 250 m buffer",
        areaSqKm: 19.8,
      },
      {
        id: "harbor-corridor",
        title: "Harbor corridor",
        extent: { xmin: -157.93, ymin: 21.29, xmax: -157.84, ymax: 21.37, spatialReference: SR },
        geometryLabel: "Route corridor, 400 m clip",
        areaSqKm: 24.4,
      },
      {
        id: "windward-shelters",
        title: "Windward shelters",
        extent: { xmin: -157.82, ymin: 21.37, xmax: -157.72, ymax: 21.47, spatialReference: SR },
        geometryLabel: "Shelter catchment, 1 km dissolve",
        areaSqKm: 31.2,
      },
    ],
    processes: [
      {
        id: "geometry-buffer",
        title: "Buffer AOI geometry",
        protocol: "GeometryServer",
        operation: "buffer",
        capabilityState: "available",
        cache: createHonuaCacheState({
          scope: "metadata",
          status: "hit",
          keyFingerprint: "geometry-buffer:v1",
          revalidatedAt: GENERATED_AT,
        }),
      },
      {
        id: "geometry-intersect",
        title: "Intersect input layers",
        protocol: "GeometryServer",
        operation: "intersect",
        capabilityState: "available",
        cache: createHonuaCacheState({
          scope: "metadata",
          status: "hit",
          keyFingerprint: "geometry-intersect:v1",
          revalidatedAt: GENERATED_AT,
        }),
      },
      {
        id: "gp-route-profile",
        title: "Route impact profile",
        protocol: "GPServer",
        operation: "submitJob",
        capabilityState: "degraded",
        cache: createHonuaCacheState({
          scope: "metadata",
          status: "stale",
          keyFingerprint: "gp-route-profile:v1",
          revalidatedAt: "2026-05-06T23:00:00Z",
        }),
      },
      {
        id: "ogc-materialize",
        title: "Materialize result layer",
        protocol: "OGC Processes",
        operation: "execute",
        capabilityState: "available",
        cache: createHonuaCacheState({
          scope: "metadata",
          status: "refreshed",
          keyFingerprint: "ogc-materialize:v1",
          revalidatedAt: GENERATED_AT,
        }),
      },
      {
        id: "network-allocation",
        title: "Network allocation solver",
        protocol: "GPServer",
        operation: "submitJob",
        capabilityState: "unsupported",
        requiresTicket: "honua-server seeded graph solver",
        cache: createHonuaCacheState({
          scope: "metadata",
          status: "miss",
          keyFingerprint: "network-allocation:v1",
        }),
      },
    ],
    plans: [
      {
        id: "buffer-overlay",
        title: "Buffer and intersect facilities",
        processIds: ["geometry-buffer", "geometry-intersect", "ogc-materialize"],
        description: "Buffer the active AOI, intersect facilities, and materialize a review layer.",
        materializes: true,
        estimatedDuration: "12-18 sec",
        capabilityState: "available",
        fixtureMode: "materialize-facilities",
        outputLayerTitle: "Buffered facility exposure",
      },
      {
        id: "route-profile",
        title: "Route impact profile",
        processIds: ["gp-route-profile", "ogc-materialize"],
        description: "Run a GPServer route profile and publish linked line/point results.",
        materializes: true,
        estimatedDuration: "20-35 sec",
        capabilityState: "degraded",
        fixtureMode: "route-profile",
        outputLayerTitle: "Route profile impact layer",
      },
      {
        id: "network-allocation",
        title: "Network allocation solver",
        processIds: ["network-allocation"],
        description: "Show an unsupported upstream capability without hiding the failed job state.",
        materializes: false,
        estimatedDuration: "Not available",
        capabilityState: "unsupported",
        fixtureMode: "unsupported-capability",
        outputLayerTitle: "Network allocation output",
      },
    ],
    inputSources: [
      {
        id: "honua-cloud:critical-facilities",
        title: "Critical facilities",
        type: "input-layer",
        cache: createHonuaCacheState({
          scope: "metadata",
          status: "hit",
          keyFingerprint: "critical-facilities:v3",
          revalidatedAt: GENERATED_AT,
        }),
        capabilities: ["query", "bbox", "geometry", "linked-view-sync"],
        capabilityState: "available",
      },
      {
        id: "honua-cloud:evacuation-routes",
        title: "Evacuation routes",
        type: "input-layer",
        cache: createHonuaCacheState({
          scope: "metadata",
          status: "stale",
          keyFingerprint: "evacuation-routes:v2",
          revalidatedAt: "2026-05-06T22:45:00Z",
        }),
        capabilities: ["query", "routing", "profile"],
        capabilityState: "degraded",
      },
    ],
    features: runnerFeatures(),
  };
}

function runnerFeatures(): RunnerFeature[] {
  return [
    feature(
      "facility-1001",
      "Iwilei electrical substation",
      "facility",
      "critical",
      "urban",
      96,
      34000,
      90,
      ["urban-core", "harbor-corridor"],
      -157.866,
      21.318,
    ),
    feature(
      "asset-1002",
      "Ala Moana pump station",
      "asset",
      "high",
      "urban",
      88,
      18000,
      130,
      ["urban-core"],
      -157.846,
      21.291,
    ),
    feature(
      "route-1003",
      "Nimitz outbound bottleneck",
      "route",
      "high",
      "harbor",
      82,
      52000,
      260,
      ["urban-core", "harbor-corridor"],
      -157.894,
      21.327,
    ),
    feature(
      "facility-1004",
      "Sand Island fuel terminal",
      "facility",
      "critical",
      "harbor",
      94,
      61000,
      180,
      ["harbor-corridor"],
      -157.887,
      21.307,
    ),
    feature(
      "shelter-1005",
      "Kaneohe high shelter",
      "shelter",
      "moderate",
      "windward",
      63,
      7200,
      410,
      ["windward-shelters"],
      -157.797,
      21.405,
    ),
    feature(
      "shelter-1006",
      "Kailua community hub",
      "shelter",
      "low",
      "windward",
      47,
      9800,
      760,
      ["windward-shelters"],
      -157.741,
      21.397,
    ),
  ];
}

function feature(
  id: string,
  title: string,
  category: RunnerFeature["category"],
  risk: RunnerFeature["risk"],
  zone: string,
  score: number,
  peopleServed: number,
  distanceMeters: number,
  aoiIds: readonly string[],
  x: number,
  y: number,
): RunnerFeature {
  return {
    id,
    title,
    category,
    risk,
    zone,
    score,
    peopleServed,
    distanceMeters,
    aoiIds,
    geometry: { x, y, spatialReference: SR },
  };
}
