import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { capabilityUnavailable } from "../capability.js";
import { jsonText } from "../helpers.js";

/**
 * `honua_docs_search` — answer a documentation question from the repository's
 * own versioned documentation corpus, with citations.
 *
 * The corpus is `llms-full.txt` (generated by `npm run docs:llms`), which
 * concatenates the documents indexed in `llms.txt` under `# File: <path>`
 * headers. Every hit therefore carries the exact source file it came from, and
 * the version block carries the release that documentation describes — derived
 * from `docs/versions.json` when it has been generated
 * (`npm run docs:versions:write`) and otherwise directly from `package.json` +
 * `.release-please-manifest.json`, the same authoritative pair
 * `scripts/docs-versions.mjs` uses. The policy those citations follow is
 * documented in `docs/documentation-versions.md`.
 *
 * This is a LOCAL tool: it reads committed files and never makes a network
 * request. When the corpus cannot be located (for example inside an installed
 * `@honua/mcp-server` that does not ship the corpus), it degrades the same way
 * every other surface-dependent tool does — a structured `available: false`
 * result with guidance, not a crash and not a misleading empty answer.
 */

const REPOSITORY = "honua-io/honua-sdk-js";
const SITE_URL = "https://honua-io.github.io/honua-sdk-js/";
const CORPUS_FILE = "llms-full.txt";
const MAX_EXCERPT_CHARS = 1200;
const EXCERPT_CONTEXT_LINES = 6;

export const schema = z.object({
  query: z
    .string()
    .min(2)
    .describe("Natural-language or keyword documentation question, e.g. 'how do I handle a capability error'"),
  limit: z.number().int().min(1).max(10).optional().describe("Maximum documents to return (default 3)"),
  pathPrefix: z
    .string()
    .optional()
    .describe("Restrict results to source files whose path starts with this value, e.g. 'docs/' or 'mcp/'"),
});

export type Input = z.infer<typeof schema>;

/** One document sliced out of the concatenated corpus. */
export interface CorpusDocument {
  file: string;
  title: string;
  body: string;
}

export interface DocsVersionCitation {
  package: string;
  version: string;
  channel: string;
  /** Whether the corpus text is trunk development documentation or a release snapshot. */
  documentationChannel: "development";
  policy: string;
  versionsManifest: string;
}

/**
 * Split `llms-full.txt` into its constituent documents. The generator emits
 * `# File: <path>` as the delimiter for each concatenated document.
 */
export function splitCorpus(corpus: string): CorpusDocument[] {
  const documents: CorpusDocument[] = [];
  const pattern = /^# File: (.+)$/gm;
  const matches = [...corpus.matchAll(pattern)];
  for (const [index, match] of matches.entries()) {
    const start = (match.index ?? 0) + match[0].length;
    const end = index + 1 < matches.length ? (matches[index + 1].index ?? corpus.length) : corpus.length;
    const body = corpus
      .slice(start, end)
      .replace(/\n-{3,}\s*$/, "")
      .trim();
    const heading = /^#\s+(.+)$/m.exec(body);
    documents.push({ file: match[1].trim(), title: heading?.[1]?.trim() ?? match[1].trim(), body });
  }
  return documents;
}

function terms(query: string): string[] {
  return [...new Set(query.toLowerCase().match(/[a-z0-9_./-]{2,}/g) ?? [])];
}

function countOccurrences(haystack: string, needle: string): number {
  let count = 0;
  let index = haystack.indexOf(needle);
  while (index !== -1) {
    count += 1;
    index = haystack.indexOf(needle, index + needle.length);
  }
  return count;
}

/** Deterministic lexical score: path and heading matches outweigh body matches. */
export function scoreDocument(document: CorpusDocument, queryTerms: readonly string[]): number {
  const file = document.file.toLowerCase();
  const body = document.body.toLowerCase();
  const headings = (document.body.match(/^#{1,4} .+$/gm) ?? []).join("\n").toLowerCase();
  let score = 0;
  let matched = 0;
  for (const term of queryTerms) {
    const inBody = countOccurrences(body, term);
    const inHeadings = countOccurrences(headings, term);
    const inPath = countOccurrences(file, term);
    if (inBody + inHeadings + inPath > 0) matched += 1;
    score += Math.min(inBody, 20) + inHeadings * 3 + inPath * 8;
  }
  // Require more than a single incidental term hit on multi-term queries.
  if (matched === 0) return 0;
  return score * matched;
}

/** The most relevant window of a document, trimmed to a token-friendly size. */
export function excerptFor(document: CorpusDocument, queryTerms: readonly string[]): string {
  const lines = document.body.split("\n");
  let bestLine = 0;
  let bestHits = 0;
  for (const [index, line] of lines.entries()) {
    const lower = line.toLowerCase();
    const hits = queryTerms.reduce((total, term) => total + countOccurrences(lower, term), 0);
    if (hits > bestHits) {
      bestHits = hits;
      bestLine = index;
    }
  }
  const start = Math.max(0, bestLine - EXCERPT_CONTEXT_LINES);
  const end = Math.min(lines.length, bestLine + EXCERPT_CONTEXT_LINES + 1);
  const excerpt = lines.slice(start, end).join("\n").trim();
  return excerpt.length > MAX_EXCERPT_CHARS ? `${excerpt.slice(0, MAX_EXCERPT_CHARS)}…` : excerpt;
}

/**
 * Locate the documentation root: the nearest ancestor directory holding
 * `llms-full.txt`, or an explicit `HONUA_DOCS_CORPUS_PATH` pointing at the
 * corpus file itself.
 */
export function resolveDocsRoot(env: NodeJS.ProcessEnv = process.env, from?: string): string | undefined {
  const override = env.HONUA_DOCS_CORPUS_PATH;
  if (override) {
    const resolved = path.resolve(override);
    return fs.existsSync(resolved) ? path.dirname(resolved) : undefined;
  }
  let dir = from ?? path.dirname(fileURLToPath(import.meta.url));
  for (let depth = 0; depth < 10; depth += 1) {
    if (fs.existsSync(path.join(dir, CORPUS_FILE))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return undefined;
}

function readJson(file: string): Record<string, unknown> | undefined {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8")) as Record<string, unknown>;
  } catch {
    return undefined;
  }
}

function channelOf(version: string): string {
  const prerelease = version.split("-", 2)[1];
  return prerelease ? prerelease.split(".", 1)[0] : "stable";
}

/**
 * The release the corpus documents, from the same authoritative sources as
 * `scripts/docs-versions.mjs`. Prefers the generated `docs/versions.json` and
 * falls back to `package.json` + `.release-please-manifest.json`.
 */
export function resolveDocsVersion(root: string): DocsVersionCitation | undefined {
  const generated = readJson(path.join(root, "docs", "versions.json"));
  const packageName = typeof generated?.package === "string" ? generated.package : "@honua/sdk-js";
  const citation = (version: string): DocsVersionCitation => ({
    package: packageName,
    version,
    channel: channelOf(version),
    documentationChannel: "development",
    policy: "docs/documentation-versions.md",
    versionsManifest: `${SITE_URL}versions.json`,
  });

  if (typeof generated?.latestRelease === "string") return citation(generated.latestRelease);

  const pkg = readJson(path.join(root, "package.json"));
  const manifest = readJson(path.join(root, ".release-please-manifest.json"));
  const version = typeof pkg?.version === "string" ? pkg.version : undefined;
  const manifestVersion = typeof manifest?.["."] === "string" ? (manifest["."] as string) : undefined;
  if (!version || !manifestVersion || version !== manifestVersion) return undefined;
  return citation(version);
}

function sourceUrl(file: string): string {
  return `https://github.com/${REPOSITORY}/blob/trunk/${file}`;
}

export async function execute(_client: unknown, input: Input) {
  const root = resolveDocsRoot();
  if (!root) {
    return capabilityUnavailable(
      "Honua documentation corpus",
      `${CORPUS_FILE} was not found in this installation or any parent directory`,
      "Run `npm run docs:llms` in a honua-sdk-js checkout, or point HONUA_DOCS_CORPUS_PATH at a generated llms-full.txt.",
    );
  }

  const version = resolveDocsVersion(root);
  if (!version) {
    return capabilityUnavailable(
      "Honua documentation versions",
      "package.json and .release-please-manifest.json disagree or are unavailable, so no release can be cited",
      "Run `npm run docs:versions:write` in a honua-sdk-js checkout so documentation answers can cite a release.",
    );
  }

  const documents = splitCorpus(fs.readFileSync(path.join(root, CORPUS_FILE), "utf8"));
  const queryTerms = terms(input.query);
  const prefix = input.pathPrefix?.toLowerCase();

  const results = documents
    .filter((document) => (prefix ? document.file.toLowerCase().startsWith(prefix) : true))
    .map((document) => ({ document, score: scoreDocument(document, queryTerms) }))
    .filter((entry) => entry.score > 0)
    .sort((a, b) => b.score - a.score || a.document.file.localeCompare(b.document.file))
    .slice(0, input.limit ?? 3)
    .map((entry) => ({
      title: entry.document.title,
      score: entry.score,
      excerpt: excerptFor(entry.document, queryTerms),
      citation: {
        file: entry.document.file,
        url: sourceUrl(entry.document.file),
        package: version.package,
        version: version.version,
        channel: version.channel,
      },
    }));

  return jsonText({
    available: true,
    query: input.query,
    release: version,
    corpus: { file: CORPUS_FILE, documents: documents.length },
    results,
    ...(results.length === 0
      ? {
          guidance:
            "No indexed document matched. Try fewer or more specific terms, or drop pathPrefix. An empty result means the corpus has no matching text, not that the capability is missing.",
        }
      : {}),
  });
}
