#!/usr/bin/env node

// Generate the zero-install playground page (#958).
//
// Playground links are derived from packages/create-honua-app/templates.manifest.json
// rather than hand-maintained, so a renamed template, a moved directory, or a
// new provider cannot leave a stale "open in a browser" link behind. `write`
// regenerates docs/playgrounds.md; `check` fails when the committed page has
// drifted from the manifest.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { loadTemplateManifest, playgroundLinks } from "../packages/create-honua-app/lib/templates.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PACKAGE_ROOT = path.join(ROOT, "packages/create-honua-app");
const OUTPUT_PATH = "docs/playgrounds.md";
const GENERATED_NOTICE = "<!-- Generated by scripts/playgrounds.mjs. Run `npm run playgrounds:generate` to update. -->";

/** Render the generated playground page for the starters and the qualifying gallery samples. */
export function renderPlaygroundPage(manifest, samples = []) {
  const lines = [
    GENERATED_NOTICE,
    "",
    "# Zero-install playgrounds",
    "",
    `Every \`create-honua-app\` starter runs in a browser playground straight from this repository — no clone, no`,
    "install, no account. Each project is self-contained: it depends on the published",
    `\`${manifest.sdk.package}@${manifest.sdk.version}\` package and serves its own committed fixture, so the green path`,
    "never depends on a third-party endpoint. Point `VITE_HONUA_ENDPOINT` at an anonymous public service to run the same",
    "code against live data.",
    "",
    "| Starter | Playground | Scaffold locally |",
    "| --- | --- | --- |",
  ];
  for (const template of manifest.templates) {
    const links = playgroundLinks(manifest, template).map((link) => `[${link.title}](${link.url})`);
    lines.push(`| ${template.title} (\`${template.id}\`) | ${links.join(" · ")} | \`npm create honua-app@latest my-map -- --template ${template.id}\` |`);
  }
  lines.push("");
  for (const template of manifest.templates) {
    lines.push(`## ${template.title}`, "", template.summary, "");
    lines.push(`- Project directory: \`${template.path}\``);
    lines.push(`- Entry file: \`${template.entryFile}\``);
    lines.push(`- Data lane: committed fixture (\`${template.dataLane}\`)`);
    lines.push(`- Pinned SDK: \`${manifest.sdk.package}@${manifest.sdk.version}\``);
    for (const link of playgroundLinks(manifest, template)) lines.push(`- ${link.title}: <${link.url}>`);
    lines.push("");
  }
  lines.push(
    "## Gallery samples",
    "",
    "A gallery sample cannot be opened from `examples/` directly: those projects build through the repository's Vite",
    "configs, which alias `@honua/sdk-js` onto this repository's own `src/` tree. `scripts/sample-playgrounds.mjs`",
    "therefore generates a standalone project — the sample's committed source, a plain Vite config, and a package.json",
    "pinned to the published packages — under `playgrounds/<id>/` for every sample that qualifies, and derives these",
    "links from it. Every other catalog sample carries a machine-readable exclusion category instead of a broken link;",
    "run `npm run samples:playgrounds:check` to see the full decision list.",
    "",
    "A sample whose data comes from a Node fixture server the repository runs beside it gets that origin generated too:",
    "its project carries byte-identical copies of the reviewed fixture pack under `fixtures/` and a Vite plugin that",
    "answers the sample's audited same-origin routes in `dev`, `preview` and `build` alike — the same move the starters",
    "above make. `samples/dist/sample-playgrounds.v1.json` records each playground's `dataOrigin`, so whether a project",
    "serves its own committed source or a generated fixture service is published, not inferred.",
    "",
    "| Sample | Playground | Source |",
    "| --- | --- | --- |",
  );
  for (const sample of samples) {
    const links = sample.playground.providers.map((provider) => `[${provider.title}](${provider.url})`);
    lines.push(
      `| ${sample.title} (\`${sample.id}\`) | ${links.join(" · ")} | \`${sample.sourcePath}\` → \`${sample.playground.projectPath}\` |`,
    );
  }
  lines.push(
    "",
    "## How the links stay honest",
    "",
    "The starter table is generated from `packages/create-honua-app/templates.manifest.json` and the sample table from",
    "`samples/catalog.v2.json`; CI regenerates both and fails on drift (`npm run playgrounds:check`,",
    "`npm run samples:playgrounds:check`). Each playground boots the project directory it names, installs its pinned",
    "dependencies, and runs `npm run dev` — the same command the project uses locally.",
    "",
    "A generated sample playground is a copy, not a fork: editing it directly fails the drift check. Change the sample",
    "under `examples/` and regenerate with `npm run samples:playgrounds:generate`.",
    "",
  );
  return `${lines.join("\n")}`;
}

function main() {
  const mode = process.argv[2] ?? "check";
  if (mode !== "write" && mode !== "check") {
    process.stderr.write("Usage: node scripts/playgrounds.mjs [write|check]\n");
    process.exit(1);
  }
  const manifest = loadTemplateManifest(PACKAGE_ROOT);
  const catalog = JSON.parse(fs.readFileSync(path.join(ROOT, "samples/catalog.v2.json"), "utf8"));
  const samples = catalog.samples.filter((sample) => sample.playground);
  const rendered = renderPlaygroundPage(manifest, samples);
  const outputFile = path.join(ROOT, OUTPUT_PATH);
  if (mode === "write") {
    fs.writeFileSync(outputFile, rendered);
    process.stdout.write(
      `playgroundsWritten=${OUTPUT_PATH} templates=${manifest.templates.length} samples=${samples.length}\n`,
    );
    return;
  }
  const committed = fs.existsSync(outputFile) ? fs.readFileSync(outputFile, "utf8") : "";
  if (committed !== rendered) {
    process.stderr.write(`${OUTPUT_PATH} has drifted; run npm run playgrounds:generate\n`);
    process.exit(1);
  }
  process.stdout.write(`playgrounds=ok templates=${manifest.templates.length} samples=${samples.length}\n`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
