#!/usr/bin/env node

// Generate the zero-install playground page (#958).
//
// Playground links are derived from packages/create-honua-app/templates.manifest.json
// rather than hand-maintained, so a renamed template, a moved directory, or a
// new provider cannot leave a stale "open in a browser" link behind. `write`
// regenerates docs/playgrounds.md; `check` fails when the committed page has
// drifted from the manifest.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { loadTemplateManifest, playgroundLinks } from "../packages/create-honua-app/lib/templates.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PACKAGE_ROOT = path.join(ROOT, "packages/create-honua-app");
const OUTPUT_PATH = "docs/playgrounds.md";
const GENERATED_NOTICE = "<!-- Generated by scripts/playgrounds.mjs. Run `npm run playgrounds:generate` to update. -->";

/** Render the generated playground page for one template manifest. */
export function renderPlaygroundPage(manifest) {
  const lines = [
    GENERATED_NOTICE,
    "",
    "# Zero-install playgrounds",
    "",
    `Every \`create-honua-app\` starter runs in a browser playground straight from this repository — no clone, no`,
    "install, no account. Each project is self-contained: it depends on the published",
    `\`${manifest.sdk.package}@${manifest.sdk.version}\` package and serves its own committed fixture, so the green path`,
    "never depends on a third-party endpoint. Point `VITE_HONUA_ENDPOINT` at an anonymous public service to run the same",
    "code against live data.",
    "",
    "| Starter | Playground | Scaffold locally |",
    "| --- | --- | --- |",
  ];
  for (const template of manifest.templates) {
    const links = playgroundLinks(manifest, template).map((link) => `[${link.title}](${link.url})`);
    lines.push(`| ${template.title} (\`${template.id}\`) | ${links.join(" · ")} | \`npm create honua-app@latest my-map -- --template ${template.id}\` |`);
  }
  lines.push("");
  for (const template of manifest.templates) {
    lines.push(`## ${template.title}`, "", template.summary, "");
    lines.push(`- Project directory: \`${template.path}\``);
    lines.push(`- Entry file: \`${template.entryFile}\``);
    lines.push(`- Data lane: committed fixture (\`${template.dataLane}\`)`);
    lines.push(`- Pinned SDK: \`${manifest.sdk.package}@${manifest.sdk.version}\``);
    for (const link of playgroundLinks(manifest, template)) lines.push(`- ${link.title}: <${link.url}>`);
    lines.push("");
  }
  lines.push(
    "## How the links stay honest",
    "",
    "The table above is generated from `packages/create-honua-app/templates.manifest.json`; CI regenerates it and fails",
    "on drift (`npm run playgrounds:check`). Each playground boots the project directory it names, installs its pinned",
    "dependencies, and runs `npm run dev` — the same command a scaffolded project uses locally.",
    "",
    "Gallery sample playgrounds are tracked separately: the samples under `examples/` build through the repository's",
    "shared Vite kit and have no standalone project manifest yet, so they are not linkable playgrounds today.",
    "",
  );
  return `${lines.join("\n")}`;
}

function main() {
  const mode = process.argv[2] ?? "check";
  if (mode !== "write" && mode !== "check") {
    process.stderr.write("Usage: node scripts/playgrounds.mjs [write|check]\n");
    process.exit(1);
  }
  const manifest = loadTemplateManifest(PACKAGE_ROOT);
  const rendered = renderPlaygroundPage(manifest);
  const outputFile = path.join(ROOT, OUTPUT_PATH);
  if (mode === "write") {
    fs.writeFileSync(outputFile, rendered);
    process.stdout.write(`playgroundsWritten=${OUTPUT_PATH} templates=${manifest.templates.length}\n`);
    return;
  }
  const committed = fs.existsSync(outputFile) ? fs.readFileSync(outputFile, "utf8") : "";
  if (committed !== rendered) {
    process.stderr.write(`${OUTPUT_PATH} has drifted from the template manifest; run npm run playgrounds:generate\n`);
    process.exit(1);
  }
  process.stdout.write(`playgrounds=ok templates=${manifest.templates.length}\n`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
