#!/usr/bin/env node

// Release-tag sealing gate (honua-io/honua-sdk-js#768).
//
// A published release tag must be STRICTLY self-verifiable: a downstream
// consumer who checks the tag out on a pristine clone must be able to run
// `npm run samples:generate` and `npm run samples:verify` and re-derive the
// sample publication contract with no relaxation at all.
//
// Release Please's version-bump commit can never satisfy that on its own:
//  1. It edits content inside the evidence-neutral source digest
//     (`package.json` plus every version-stamped fixture in
//     release-please-config.json's `extra-files`; see
//     EVIDENCE_NEUTRAL_INCLUDED_ROOTS in scripts/sample-gate-receipt.mjs), so
//     every committed sample gate receipt's `sourceDigest` immediately
//     describes the *previous* tree -- the "gate receipt source digest
//     mismatch" a pristine checkout of js-sdk-v0.1.2-beta.0 reported.
//  2. The derived sample artifacts it carries were generated before the bump,
//     so they still self-report the previous release version (the
//     v0.1.2-beta.0 tag shipped artifacts stamped 0.1.1-beta.0).
//
// Both are repaired by the same event: regenerate-derived-artifacts.yml reseals
// evidence and regenerates the projections against the bumped tree and returns
// them as a generated-only descendant commit. Release Please therefore waits
// for that reseal and moves the js-sdk-* tag onto the resealed commit before
// anything publishes; this script is the gate that proves the commit a release
// actually publishes from is sealed, and fails with operator-facing
// remediation when it is not.
//
// This is deliberately a fast precondition, not a replacement for
// `samples:verify`: it re-checks exactly the two release-specific bindings
// above (receipt source digest + derived version stamps) so a stale tag is
// reported in seconds with release-specific guidance, instead of surfacing deep
// inside a long publish validation.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

export const RELEASE_TAG_PREFIX = "js-sdk-";

// Derived artifacts that stamp the SDK release version and are regenerated by
// `samples:generate`. The frozen v1/v2 projections and v1 consumer handoff are
// deliberately absent: requiring a current release stamp in compatibility
// artifacts would force their supposedly immutable bytes to change.
export const SEALED_VERSION_STAMPS = Object.freeze([
  { path: "samples/dist/honua-site-samples.v3.json", field: "catalog.version" },
  { path: "samples/dist/capability-sample-matrix.v1.json", field: "sdk.version" },
  { path: "samples/dist/honua-site-consumer-handoff.v2.json", field: "sdk.version" },
]);

const EVIDENCE_ROOT = "samples/evidence";
const RECEIPT_GLOB = `${EVIDENCE_ROOT}/*/receipts/*.json`;
const VERSION_PATTERN = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
const DIGEST_PATTERN = /^[a-f0-9]{64}$/;
const REVISION_PATTERN = /^[0-9a-f]{40}$/;

const REMEDIATION = [
  "Remediation: a release tag must name a commit whose derived sample artifacts are sealed to it.",
  "Release Please's version-bump commit never is -- it edits files inside the evidence-neutral",
  "source digest, which re-stales every gate receipt, and the sample artifacts it carries were",
  "generated before the bump. Wait for regenerate-derived-artifacts.yml's automation PR to merge,",
  "then move the js-sdk-* tag onto that generated-only descendant (release-please.yml's",
  '"Move the release tag onto the resealed commit" step does this automatically) and rerun.',
].join("\n");

function truthyEnvSignal(value) {
  return /^(1|true|yes|on)$/i.test(value ?? "");
}

function shortDigest(digest) {
  return typeof digest === "string" ? digest.slice(0, 12) : String(digest);
}

/**
 * Parse the SDK release version out of a `js-sdk-*` tag. Historic tags carry a
 * doubled `v` (`js-sdk-vv0.0.5-alpha.0`) because the component separator and
 * the version prefix were both applied, so every leading `v` is stripped.
 */
export function releaseTagVersion(tag) {
  if (typeof tag !== "string" || !tag.startsWith(RELEASE_TAG_PREFIX)) {
    throw new Error(`release tag must start with ${RELEASE_TAG_PREFIX}: ${String(tag)}`);
  }
  let version = tag.slice(RELEASE_TAG_PREFIX.length);
  while (version.startsWith("v")) version = version.slice(1);
  if (!VERSION_PATTERN.test(version)) throw new Error(`release tag does not name a version: ${tag}`);
  return version;
}

function readField(value, field) {
  let current = value;
  for (const key of field.split(".")) {
    if (current === null || typeof current !== "object" || Array.isArray(current)) return undefined;
    current = current[key];
  }
  return typeof current === "string" ? current : undefined;
}

/**
 * Pure evaluation of the release seal. Every failure is collected so an
 * operator sees the whole picture at once (stale receipts and skewed version
 * stamps share one root cause and always occur together) instead of one error
 * per rerun.
 */
export function evaluateReleaseSeal({
  packageVersion,
  expectVersion,
  tag,
  tagRevision,
  revision,
  sourceDigest,
  relaxSignal,
  checkoutProblem,
  versionStamps = [],
  receipts = [],
  receiptRevisions = [],
}) {
  const problems = [];
  if (truthyEnvSignal(relaxSignal)) {
    problems.push(
      `HONUA_DERIVED_ARTIFACTS_RELAX=${relaxSignal} is set; the release seal is the strict authority and must never run relaxed`,
    );
  }
  if (!VERSION_PATTERN.test(packageVersion ?? "")) {
    problems.push(`package.json version is not a release version: ${String(packageVersion)}`);
  }
  if (expectVersion !== undefined && expectVersion !== packageVersion) {
    problems.push(`expected release version ${expectVersion} but package.json declares ${String(packageVersion)}`);
  }
  if (tag !== undefined) {
    let tagVersion;
    try {
      tagVersion = releaseTagVersion(tag);
    } catch (error) {
      problems.push(error instanceof Error ? error.message : String(error));
    }
    if (tagVersion !== undefined && tagVersion !== packageVersion) {
      problems.push(`tag ${tag} names version ${tagVersion} but package.json declares ${String(packageVersion)}`);
    }
    if (tagRevision === null) {
      problems.push(`tag ${tag} does not resolve to a commit in this checkout`);
    } else if (tagRevision !== undefined && revision !== undefined && tagRevision !== revision) {
      problems.push(`tag ${tag} points at ${tagRevision} instead of the verified commit ${revision}`);
    }
  }
  if (checkoutProblem) problems.push(checkoutProblem);
  if (!DIGEST_PATTERN.test(sourceDigest ?? "")) {
    problems.push(`evidence-neutral source digest is unavailable: ${String(sourceDigest)}`);
  }
  for (const stamp of versionStamps) {
    if (stamp.problem) {
      problems.push(`${stamp.path}: ${stamp.problem}`);
      continue;
    }
    if (stamp.version === undefined) {
      problems.push(`${stamp.path}: ${stamp.field} is missing`);
      continue;
    }
    if (stamp.version !== packageVersion) {
      problems.push(
        `${stamp.path}: ${stamp.field} is ${stamp.version} but the release is ${String(packageVersion)} (derived sample artifacts were not regenerated after the version bump)`,
      );
    }
  }
  if (receipts.length === 0) {
    problems.push(`no sample gate receipts were found under ${RECEIPT_GLOB}`);
  }
  const stale = receipts.filter((receipt) => receipt.sourceDigest !== sourceDigest);
  if (stale.length > 0 && DIGEST_PATTERN.test(sourceDigest ?? "")) {
    problems.push(
      `${stale.length} of ${receipts.length} sample gate receipts are sealed to another tree (${stale[0].path} declares ${shortDigest(stale[0].sourceDigest)}, this commit is ${shortDigest(sourceDigest)})`,
    );
  }
  for (const receipt of receipts) {
    if (receipt.problem) problems.push(`${receipt.path}: ${receipt.problem}`);
  }
  // A digest-matching receipt with no full-commit sourceRevision has no
  // resolvable sealing commit, and the revision verifier skips silently when
  // handed undefined — treat it as a seal failure, never a success.
  for (const receipt of receipts) {
    if (receipt.problem !== undefined || receipt.sourceDigest !== sourceDigest) continue;
    if (typeof receipt.sourceRevision !== "string" || !REVISION_PATTERN.test(receipt.sourceRevision)) {
      problems.push(
        `${receipt.path}: sourceRevision ${JSON.stringify(receipt.sourceRevision)} is not a full commit SHA, so its sealing commit cannot be verified`,
      );
    }
  }
  // One message per sealing revision rather than per receipt: every receipt a
  // reseal writes shares that reseal's revision, so a per-receipt report would
  // repeat one failure dozens of times.
  for (const entry of receiptRevisions) {
    if (entry.problem) problems.push(`sample gate receipts sealed by ${entry.revision}: ${entry.problem}`);
  }
  return { ok: problems.length === 0, problems };
}

function gitRevision(reference, root) {
  try {
    return execFileSync("git", ["rev-parse", "--verify", "--quiet", `${reference}^{commit}`], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    }).trim();
  } catch {
    return null;
  }
}

function readVersionStamps(root) {
  return SEALED_VERSION_STAMPS.map((stamp) => {
    const absolute = path.join(root, stamp.path);
    if (!fs.existsSync(absolute)) return { ...stamp, problem: "derived artifact is missing" };
    try {
      return { ...stamp, version: readField(JSON.parse(fs.readFileSync(absolute, "utf8")), stamp.field) };
    } catch (error) {
      return { ...stamp, problem: `is not readable JSON: ${error instanceof Error ? error.message : String(error)}` };
    }
  });
}

// `fs.globSync` is Node 22+ and this repository runs Node 20.19.0, so the
// receipt set is enumerated with an explicit two-level directory read.
export function receiptFiles(root = ROOT) {
  const evidenceRoot = path.join(root, EVIDENCE_ROOT);
  if (!fs.existsSync(evidenceRoot)) return [];
  const files = [];
  for (const sample of fs.readdirSync(evidenceRoot, { withFileTypes: true })) {
    if (!sample.isDirectory()) continue;
    const receiptsRoot = path.join(evidenceRoot, sample.name, "receipts");
    if (!fs.existsSync(receiptsRoot)) continue;
    for (const receipt of fs.readdirSync(receiptsRoot, { withFileTypes: true })) {
      if (!receipt.isFile() || !receipt.name.endsWith(".json")) continue;
      files.push(`${EVIDENCE_ROOT}/${sample.name}/receipts/${receipt.name}`);
    }
  }
  return files.sort();
}

function readReceipts(root) {
  return receiptFiles(root).map((relative) => {
    try {
      const receipt = JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
      return { path: relative, sourceDigest: receipt.sourceDigest, sourceRevision: receipt.sourceRevision };
    } catch (error) {
      return {
        path: relative,
        problem: `is not readable JSON: ${error instanceof Error ? error.message : String(error)}`,
      };
    }
  });
}

/**
 * Read every release-seal input from a real checkout. The gate-receipt module
 * is imported lazily so the pure evaluator above stays cheap to load (that
 * module compiles JSON schemas and reads the sample catalog at import time).
 */
export async function collectReleaseSealInputs({ root = ROOT, tag, expectVersion } = {}) {
  const { evidenceNeutralSourceDigest, verifyEvidenceNeutralCheckout } = await import("./sample-gate-receipt.mjs");
  const packageJson = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
  const receipts = readReceipts(root);
  let sourceDigest;
  let checkoutProblem;
  try {
    sourceDigest = evidenceNeutralSourceDigest(root);
    // Verify the checkout binding once (clean evidence-neutral tree, index
    // bound to HEAD) so a dirty tree is not reported against every receipt.
    verifyEvidenceNeutralCheckout(sourceDigest, root);
  } catch (error) {
    checkoutProblem = `evidence-neutral checkout is not release-clean: ${error instanceof Error ? error.message : String(error)}`;
  }
  // One verification per distinct sealing revision: this is what proves a
  // receipt's sourceRevision names a real commit whose evidence-neutral tree
  // matches, and therefore also catches a shallow release checkout that cannot
  // see the regeneration-chain commit its receipts were sealed by.
  const receiptRevisions = [];
  if (checkoutProblem === undefined) {
    const revisions = new Set();
    for (const receipt of receipts) {
      if (receipt.problem !== undefined || receipt.sourceDigest !== sourceDigest) continue;
      // A receipt without a resolvable sealing commit must fail the gate:
      // verifyEvidenceNeutralCheckout skips revision verification entirely
      // when the revision argument is undefined, so an absent or malformed
      // sourceRevision would otherwise be recorded as verified.
      if (typeof receipt.sourceRevision !== "string" || !REVISION_PATTERN.test(receipt.sourceRevision)) {
        receiptRevisions.push({
          revision: String(receipt.sourceRevision),
          problem: `${receipt.path} declares no full-commit sourceRevision, so its sealing commit cannot be verified`,
        });
        continue;
      }
      revisions.add(receipt.sourceRevision);
    }
    for (const revision of revisions) {
      try {
        verifyEvidenceNeutralCheckout(sourceDigest, root, revision);
        receiptRevisions.push({ revision: String(revision) });
      } catch (error) {
        receiptRevisions.push({
          revision: String(revision),
          problem: error instanceof Error ? error.message : String(error),
        });
      }
    }
  }
  return {
    packageVersion: packageJson.version,
    expectVersion,
    tag,
    tagRevision: tag === undefined ? undefined : gitRevision(`refs/tags/${tag}`, root),
    revision: gitRevision("HEAD", root) ?? undefined,
    sourceDigest,
    relaxSignal: process.env.HONUA_DERIVED_ARTIFACTS_RELAX,
    checkoutProblem,
    versionStamps: readVersionStamps(root),
    receipts,
    receiptRevisions,
  };
}

export function parseReleaseSealArgs(argv) {
  const [command, ...rest] = argv;
  const options = {};
  for (let index = 0; index < rest.length; index += 1) {
    const flag = rest[index];
    const value = rest[index + 1];
    if (flag !== "--tag" && flag !== "--expect-version" && flag !== "--root") {
      throw new Error(`Unknown release-seal argument: ${flag}`);
    }
    if (value === undefined || value.startsWith("--")) throw new Error(`${flag} requires a value`);
    options[flag === "--expect-version" ? "expectVersion" : flag.slice(2)] = value;
    index += 1;
  }
  return { command, options };
}

async function main(argv) {
  const { command, options } = parseReleaseSealArgs(argv);
  if (command !== "check") {
    throw new Error("Usage: node scripts/release-seal.mjs check [--tag <js-sdk-tag>] [--expect-version <x.y.z>]");
  }
  const root = options.root === undefined ? ROOT : path.resolve(options.root);
  const inputs = await collectReleaseSealInputs({ root, tag: options.tag, expectVersion: options.expectVersion });
  const result = evaluateReleaseSeal(inputs);
  if (!result.ok) {
    process.stderr.write(
      `release seal failed for ${inputs.revision ?? "the current checkout"}:\n${result.problems
        .map((problem) => `  - ${problem}\n`)
        .join("")}${REMEDIATION}\n`,
    );
    process.exitCode = 1;
    return;
  }
  process.stdout.write(
    `releaseSeal=ok version=${inputs.packageVersion} tag=${inputs.tag ?? "(none)"} revision=${inputs.revision} sourceDigest=${shortDigest(inputs.sourceDigest)} receipts=${inputs.receipts.length}\n`,
  );
}

if (path.resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) {
  await main(process.argv.slice(2)).catch((error) => {
    process.stderr.write(`release seal failed: ${error instanceof Error ? error.stack : String(error)}\n`);
    process.exitCode = 1;
  });
}
