#!/usr/bin/env node

// Generate the release-scoped skill table in skills/README.md (#1425).
//
// The table used to be hand-maintained, so a new, renamed, or re-scoped skill
// silently left a stale row behind. It is now derived from each
// skills/<name>/SKILL.md frontmatter (`name`, `description`, `release`,
// `stages`) and from the release journey's stage titles, and lives inside a
// managed block. Everything outside the block stays hand-written prose.
//
//   write  — regenerate the managed block (npm run skills:readme)
//   check  — fail when the committed block has drifted (npm run skills:readme:check,
//            also run as part of npm run verify:skills)

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS_DIR = path.join(ROOT, "skills");
const README_PATH = path.join(SKILLS_DIR, "README.md");
const JOURNEY_PATH = path.join(ROOT, "mcp", "release", "zero-to-map", "journey.v1.json");

export const README_START = "<!-- skills-table:start -->";
export const README_END = "<!-- skills-table:end -->";
const GENERATED_NOTICE =
  "<!-- Generated by scripts/skills-readme.mjs. Do not edit by hand; run `npm run skills:readme`. -->";

/** Parse the SKILL.md frontmatter subset this generator needs. */
export function parseSkillFrontmatter(source) {
  if (!source.startsWith("---")) throw new Error("SKILL.md is missing YAML frontmatter");
  const end = source.indexOf("\n---", 3);
  if (end === -1) throw new Error("SKILL.md has unterminated YAML frontmatter");
  const fields = {};
  for (const line of source.slice(3, end).split("\n")) {
    const match = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line);
    if (!match) continue;
    const raw = match[2].trim();
    if (raw.startsWith("[") && raw.endsWith("]")) {
      const inner = raw.slice(1, -1).trim();
      fields[match[1]] = inner === "" ? [] : inner.split(",").map((entry) => unquote(entry.trim()));
      continue;
    }
    fields[match[1]] = unquote(raw);
  }
  return fields;
}

function unquote(value) {
  if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
    return value.slice(1, -1);
  }
  return value;
}

/**
 * The first sentence of a `description`, which by convention states WHEN the
 * skill applies. The full description stays in the skill itself.
 */
export function useItWhen(description) {
  const trimmed = description.replace(/^Use when\s+/i, "").trim();
  const stop = trimmed.search(/\.\s/);
  const first = stop === -1 ? trimmed.replace(/\.$/, "") : trimmed.slice(0, stop);
  return `${first.charAt(0).toUpperCase()}${first.slice(1)}.`;
}

export function loadSkills(skillsDir = SKILLS_DIR) {
  return fs
    .readdirSync(skillsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
    .map((dir) => {
      const source = fs.readFileSync(path.join(skillsDir, dir, "SKILL.md"), "utf8");
      const fields = parseSkillFrontmatter(source);
      return {
        dir,
        name: fields.name ?? dir,
        description: fields.description ?? "",
        release: fields.release ?? "",
        stages: Array.isArray(fields.stages) ? fields.stages : [],
      };
    });
}

export function loadJourney(journeyPath = JOURNEY_PATH) {
  const journey = JSON.parse(fs.readFileSync(journeyPath, "utf8"));
  const release = /^(\d{4}\.\d+)-/.exec(String(journey.journeyId ?? ""))?.[1];
  if (!release) throw new Error(`journeyId "${journey.journeyId}" does not start with a <year>.<n> release`);
  return { release, stages: (journey.stages ?? []).map((stage) => ({ id: stage.id, title: stage.title })) };
}

/** Render the managed block: the skill table plus the per-stage coverage table. */
export function renderSkillsBlock(skills, journey) {
  const terminal = skills.filter((skill) => skill.stages.length > 0);
  const supporting = skills.filter((skill) => skill.stages.length === 0);

  const lines = [
    README_START,
    GENERATED_NOTICE,
    "",
    `## Available skills (release ${journey.release})`,
    "",
    "Every skill declares the release it was written for and the zero-to-map journey",
    "stage(s) it serves. `npm run verify:skills` fails when a skill drifts from the",
    "release, cites a tool or file that does not exist, pins a package version this",
    "repository does not publish, or leaves a journey stage with no skill.",
    "",
    "### Terminal-journey skills",
    "",
    "| Skill | Stage(s) | Use it when |",
    "| --- | --- | --- |",
  ];
  for (const skill of terminal) {
    const stages = skill.stages.map((stage) => `\`${stage}\``).join(", ");
    lines.push(`| [\`${skill.name}\`](./${skill.dir}/SKILL.md) | ${stages} | ${useItWhen(skill.description)} |`);
  }

  lines.push("", "### Supporting skills", "", "| Skill | Use it when |", "| --- | --- |");
  for (const skill of supporting) {
    lines.push(`| [\`${skill.name}\`](./${skill.dir}/SKILL.md) | ${useItWhen(skill.description)} |`);
  }

  lines.push(
    "",
    `### ${journey.release} terminal-stage coverage`,
    "",
    "Stages come from [`mcp/release/zero-to-map/journey.v1.json`](../mcp/release/zero-to-map/journey.v1.json)",
    "(see [the journey overview](../docs/zero-to-map-release-journey.md)). A stage with",
    "no skill fails `npm run verify:skills`.",
    "",
    "| # | Stage | Skill(s) |",
    "| --- | --- | --- |",
  );
  journey.stages.forEach((stage, index) => {
    const owners = terminal
      .filter((skill) => skill.stages.includes(stage.id))
      .map((skill) => `[\`${skill.name}\`](./${skill.dir}/SKILL.md)`);
    lines.push(`| ${index + 1} | \`${stage.id}\` — ${stage.title} | ${owners.join(" · ") || "**none**"} |`);
  });

  lines.push("", README_END);
  return lines.join("\n");
}

export function replaceManagedBlock(readme, block) {
  const start = readme.indexOf(README_START);
  const end = readme.indexOf(README_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`skills/README.md is missing the ${README_START} / ${README_END} managed block`);
  }
  return readme.slice(0, start) + block + readme.slice(end + README_END.length);
}

function main() {
  const mode = process.argv[2] ?? "check";
  if (mode !== "write" && mode !== "check") {
    process.stderr.write("Usage: node scripts/skills-readme.mjs [write|check]\n");
    process.exitCode = 1;
    return;
  }

  const readme = fs.readFileSync(README_PATH, "utf8");
  const expected = replaceManagedBlock(readme, renderSkillsBlock(loadSkills(), loadJourney()));

  if (mode === "write") {
    if (expected !== readme) {
      fs.writeFileSync(README_PATH, expected);
      process.stdout.write("wrote skills/README.md\n");
      return;
    }
    process.stdout.write("skills/README.md already current\n");
    return;
  }

  if (expected !== readme) {
    process.stderr.write("skills/README.md is stale. Run `npm run skills:readme` and commit the result.\n");
    process.exitCode = 1;
    return;
  }
  process.stdout.write("skills/README.md is current\n");
}

if (path.resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) main();
