/**
 * `@honua/sdk-js/honua` — the Honua-first SDK entrypoint.
 *
 * Re-exports the core {@link HonuaClient}, the cross-protocol typing primitives,
 * the filter / cache / runtime helpers, and the Honua-native client wrappers
 * (`HonuaFeatureLayer`, `HonuaMapService`, `HonuaOgcFeatures`, `HonuaWfs`, ...).
 *
 * Use this entrypoint for new code. For migration code that talks the legacy
 * Esri shape, import from `@honua/sdk-js/esri-compat`. For protocol-neutral
 * cross-protocol code, import from `@honua/sdk-js/contract`.
 *
 * @example
 * ```ts
 * import { HonuaClient } from "@honua/sdk-js/honua";
 *
 * const client = new HonuaClient({ baseUrl: "https://your-honua-server.example" });
 * const { features } = await client.queryFeatures({ serviceId: "parcels", layerId: 0, where: "1=1" });
 * ```
 *
 * @packageDocumentation
 */
export { HonuaClient, HONUA_MINIMUM_SUPPORTED_SERVER_VERSION } from "./core/client.js";
export {
  HONUA_CONNECT_ADAPTER_VERSION,
  HONUA_CONNECT_DISCOVERY_SNAPSHOT_VERSION,
  HONUA_CONNECT_PROJECTION_VERSION,
  connect,
  discoverOgcProcesses,
} from "./connect.js";
export type {
  ConnectCacheStatus,
  ConnectDiscoveryCache,
  ConnectDiscoveryCacheContext,
  ConnectDiscoverySnapshot,
  ConnectDiscoverySourceSnapshot,
  ConnectOptions,
  ConnectProtocolHint,
  ConnectResolvedProtocol,
  GeoParquetSourceProfiler,
  HonuaConnection,
  HonuaConnectionInspection,
  OgcProcessDiscoverySummary,
  OgcProcessesDiscoveryOptions,
  OgcProcessesDiscoveryResult,
  StacAssetCandidate,
  StacAssetCandidateMetadata,
  StacAssetCandidateState,
  StacAssetClassificationEvidence,
  StacAssetConfidence,
  StacAssetKind,
  StacAssetSourceCandidate,
  StacStaticDiagnostic,
  StacStaticDiagnosticCode,
  StacStaticDiscoveryInspection,
  StacStaticObjectSummary,
  StacStaticObjectType,
  StacStaticTraversalOptions,
  StacStaticTraversalPolicy,
} from "./connect.js";
export { discoverGeoServices } from "./geoservices-discovery.js";
export type {
  GeoServicesAuthenticationDescriptor,
  GeoServicesAuthenticationRequirement,
  GeoServicesCrsDescriptor,
  GeoServicesDiscoveryDiagnostic,
  GeoServicesDiscoveryDiagnosticCode,
  GeoServicesDiscoveryOptions,
  GeoServicesDiscoveryResult,
  GeoServicesDiscoveryState,
  GeoServicesFormatDescriptor,
  GeoServicesLimitDescriptor,
  GeoServicesOperationAvailability,
  GeoServicesOperationDescriptor,
  GeoServicesOperationExecution,
  GeoServicesServiceDescriptor,
} from "./geoservices-discovery.js";
export type { GeoServicesServiceKind, GeoServicesServiceProtocol } from "./geoservices-endpoint.js";
export { HONUA_GEOSERVICES_METADATA_MAX_BYTES } from "./geoservices-metadata.js";
export type { GeoServicesMetadataRequestOptions } from "./geoservices-metadata.js";
export { createHonua } from "./kernel/index.js";
export type {
  ConnectLocator,
  ConnectionInspection,
  HonuaKernel,
  HonuaKernelConnectOptions,
  HonuaKernelConnection,
  HonuaKernelOptions,
  InspectOptions,
  MountOptions,
  MountedMap,
  MountedMapRefreshOptions,
  RendererAdapter,
  RendererDiagnostic,
  RendererEnvironment,
  RendererKind,
  RendererMountRequest,
  RendererOwnership,
  RendererSession,
  RendererTarget,
} from "./kernel/index.js";
export {
  MIGRATION_EVIDENCE_STATES,
  MIGRATION_MANIFEST_ARTIFACT_KIND,
  MIGRATION_MANIFEST_ARTIFACT_VERSION,
  MIGRATION_PARITY_EVIDENCE_ARTIFACT_KIND,
  MIGRATION_PARITY_EVIDENCE_ARTIFACT_VERSION,
  MIGRATION_SOURCE_INVENTORY_ARTIFACT_KIND,
  MIGRATION_SOURCE_INVENTORY_ARTIFACT_VERSION,
} from "./core/types.js";
export {
  createHonuaCacheState,
  honuaCacheValidatorFromHeaders,
  honuaMetadataRequestHeaders,
  isHonuaCacheStatus,
  normalizeHonuaMetadataRequestOptions,
} from "./core/cache-state.js";
export {
  compileRuntimeStyleFilter,
  createFilterRegistry,
  parseFilterRegistry,
  projectFilterRegistryToLinkedView,
  projectFilterRegistryToQuery,
  projectFilterRegistryToWidgetProjection,
  selectActiveFilterClauses,
  serializeFilterRegistry,
} from "./filter-registry/index.js";
export type {
  CreateFilterRegistryOptions,
  FilterClause as RegistryFilterClause,
  FilterEffect,
  FilterLifecycle,
  FilterRegistry,
  FilterRegistryChangeEvent,
  FilterRegistryListener,
  FilterRegistryOwner,
  FilterRegistryProjectionOptions,
  FilterRegistryQueryProjection,
  FilterRegistryQueryProjectionOptions,
  FilterRegistrySelector,
  FilterRegistrySelectorListener,
  FilterRegistrySelectorOptions,
  FilterRegistrySnapshot,
  FilterRegistryUnsubscribe,
  FilterRuntimeApplyMode,
  FilterSourceScope,
  FilterValuePolicy,
  RegistrySpatialScope,
  RuntimeStyleFilterExpression,
  ShareableFilterRegistryState,
} from "./filter-registry/index.js";
export type {
  HonuaCacheReadMode,
  HonuaCacheScope,
  HonuaCacheState,
  HonuaCacheStateInit,
  HonuaCacheStatus,
  HonuaCacheValidator,
  HonuaMetadataRequestOptions,
  NormalizedHonuaMetadataRequestOptions,
} from "./core/cache-state.js";
// Experimental collaboration surface is subpath-only:
//   import { HonuaSavedMapCollaborationClient } from "@honua/sdk-js/collaboration";
export { parseWebMap } from "./webmap/index.js";
export type { ParseWebMapOptions, ParseWebMapResult } from "./webmap/index.js";
export {
  createWarningCollector,
  CONTRACT,
  getContractSummary,
  convertSymbol,
  esriColorToCss,
  convertRenderer,
  convertPopupInfo,
  convertLabelingInfo,
  convertBasemap,
  convertExtent,
  convertInitialViewpoint,
  convertOperationalLayer,
} from "./webmap/index.js";
export type {
  WebMapWarning,
  WarningCollector,
  ContractEntry,
  ContractSupport,
  ContractSummary,
  SymbolConversionResult,
  RendererConversionResult,
  HonuaPopupConfig,
  HonuaPopupFieldInfo,
  HonuaPopupMediaInfo,
  BasemapConversionResult,
  ExtentConversionResult,
  LayerConversionResult,
  WebMapJson,
  WebMapOperationalLayer,
  WebMapRenderer,
  WebMapSymbol,
  WebMapBaseMap,
  WebMapPopupInfo,
  WebMapExtent,
  WebMapPoint,
  WebMapViewpoint,
  WebMapBookmark,
  EsriColor,
} from "./webmap/index.js";
export {
  expr,
  Expr,
  format,
  numberFormat,
  collator,
  resolvedLocale,
  hsl,
  hsla,
  toRgba,
  lineProgress,
  heatmapDensity,
  pitch,
  accumulated,
  distanceFromCenter,
} from "./expr/index.js";
export {
  isHonuaSource,
  isFeatureServiceSource,
  isMapServiceSource,
  isOgcFeaturesSource,
  parseOgcFeaturesUrl,
  validateHonuaStyle,
  createSources,
} from "./style/index.js";
export type {
  HonuaSourceBase,
  HonuaFeatureServiceSourceSpecification,
  HonuaMapServiceSourceSpecification,
  HonuaOgcFeaturesSourceSpecification,
  HonuaSourceSpecification,
  HonuaLayerSpecification,
  HonuaStyleSpecification,
  ParsedOgcFeaturesUrl,
  StyleValidationError,
  ResolvedSource,
} from "./style/index.js";
export type {
  ExprColor,
  ExprFormatted,
  ExprImage,
  ExprValue,
  NumberInput,
  StringInput,
  BooleanInput,
  ColorInput,
  Resolvable,
  InterpolationMethod,
  GeoJsonPoint,
  GeoJsonMultiPoint,
  GeoJsonLineString,
  GeoJsonMultiLineString,
  GeoJsonPolygon,
  GeoJsonMultiPolygon,
  GeoJsonGeometry,
  FormatSegmentOptions,
  NumberFormatOptions,
  CollatorOptions,
  ExprCollator,
} from "./expr/index.js";
export {
  setFeatureState,
  getFeatureState,
  removeFeatureState,
  createHoverHandler,
  createSelectionHandler,
  bindDetailToSelection,
  bindChartToExploration,
  bindFilterControlsToExploration,
  bindMapExtentToExploration,
  bindMapSelectionToExploration,
  bindQueryProjectionToExploration,
  extentToSpatialFilter,
  selectLinkedViewQueryProjection,
  subscribeExplorationSelector,
  bindTableSelectionToExploration,
  interactionQueryParamNames,
  parseInteractionQueryState,
  parseSelection,
  preparePrimaryDetailModel,
  prepareSelectionDetailModels,
  serializeInteractionQueryState,
  serializeSelection,
  syncMapLayerFilterToExploration,
  syncFeatureStateSelection,
} from "./interactions/index.js";
export type {
  FeatureStateMap,
  MapEventTarget,
  InteractiveMap,
  FeatureTarget,
  HoverHandlerOptions,
  HoverHandle,
  SelectionHandlerOptions,
  SelectionHandle,
  ChartBucketSelection,
  ChartBucketSelectionOptions,
  ChartExplorationBinding,
  ExplorationSelector,
  ExplorationSelectorListener,
  ExplorationSelectorSubscribeOptions,
  FeatureStateSelectionSyncOptions,
  FilterControlsExplorationBinding,
  InteractionBindingHandle,
  LinkedViewQueryBindingOptions,
  LinkedViewQueryProjection,
  LinkedViewQueryProjectionOptions,
  LinkedViewSpatialMode,
  MapExtentExplorationBindingOptions,
  MapExtentExplorationSource,
  MapLayerFilterExplorationBindingOptions,
  MapLayerFilterTarget,
  MapSelectionExplorationBindingOptions,
  SelectionDetailListener,
  TableSelectionExplorationBinding,
  DetailFeatureLike,
  DetailFieldDefinition,
  DetailFieldModel,
  DetailModel,
  DetailModelOptions,
  DetailSelectionStatus,
  ShareableInteractionQueryParams,
  ShareableInteractionQueryState,
} from "./interactions/index.js";
// Experimental scene-workspace surface is subpath-only:
//   import { createSceneWorkspace } from "@honua/sdk-js/scene-workspace";
export { HonuaMap } from "./map/index.js";
export type {
  HonuaMapOptions,
  HonuaMapEvent,
  HonuaMapEventListener,
  LayerSnapshot,
  ResolvedMapSource,
} from "./map/index.js";
export {
  HonuaHttpError,
  HonuaTimeoutError,
  HonuaNetworkError,
  HonuaAbortError,
  HonuaGrpcError,
  HonuaGeometryError,
  HonuaAuthError,
  HonuaCapabilityNotSupportedError,
  HonuaExplorationContextError,
  HonuaWfsExceptionError,
  isHonuaError,
} from "./core/errors.js";
export type {
  HonuaError,
  HonuaAuthErrorCode,
  HonuaGeometryErrorCode,
  HonuaGrpcErrorOptions,
  HonuaHttpErrorOptions,
} from "./core/errors.js";
export {
  HONUA_ERROR_KIND,
  HonuaSdkError,
  isHonuaErrorCode,
  sanitizeHonuaErrorContext,
  serializeHonuaError,
} from "./core/error-envelope.js";
export { HONUA_ERROR_CODE_REGISTRY } from "./core/error-code-registry.js";
export type {
  HonuaErrorEnvelopeContext,
  HonuaErrorEnvelopeContextValue,
  HonuaErrorMetadata,
  HonuaErrorOptions,
  HonuaFailureKind,
  HonuaFieldFailure,
  HonuaProtocolMetadata,
  HonuaTerminalFailureReceipt,
  SerializedHonuaError,
  SerializedHonuaErrorCause,
} from "./core/error-envelope.js";
export type {
  HonuaErrorCategory,
  HonuaErrorCode,
  HonuaErrorCodeDescriptor,
  HonuaErrorDomain,
} from "./core/error-code-registry.js";
export { QueryBuilder, MapLayerQueryBuilder, OgcQueryBuilder } from "./core/query-builder.js";
export {
  envelope,
  point,
  polygon,
  bufferEnvelope,
  spatialIntersects,
  spatialContains,
  spatialWithin,
} from "./core/spatial-filter.js";
export type { SpatialFilter } from "./core/spatial-filter.js";
export { batchQuery } from "./core/batch.js";
export type { BatchQueryItem, BatchQueryOptions, BatchQueryResult } from "./core/batch.js";
export { decodePbfQueryResponse, isPbfResponse } from "./core/pbf-decoder.js";
export { esriFeatureToGeoJSON, esriGeometryToGeoJSON } from "./core/esri-geojson.js";
export {
  decodeElevationPixel,
  decodeTerrainRgbElevation,
  decodeTerrariumElevation,
  haversineMeters,
  sampleElevationProfile,
} from "./core/terrain-elevation.js";
export type {
  ElevationCoordinate,
  ElevationProfile,
  ElevationProfileSample,
  ElevationSampler,
  SampleElevationProfileOptions,
  TerrainElevationEncoding,
} from "./core/terrain-elevation.js";
export {
  createHonuaOgcFeatures,
  createHonuaService,
  HonuaFeatureLayer,
  HonuaGeometryService,
  HonuaGeoprocessingJobRun,
  HonuaGeoprocessingService,
  HonuaImageService,
  HonuaMapLayer,
  HonuaMapService,
  HonuaOgcFeatureCollection,
  HonuaOgcFeatures,
  HonuaService,
} from "./core/surfaces.js";
export {
  createHonuaOgcTiles,
  DEFAULT_OGC_TILE_MATRIX_SET,
  HonuaOgcTiles,
  HonuaOgcTileset,
} from "./core/ogc-tiles.js";
export type {
  HonuaMapLibreTilesConfig,
  HonuaMapLibreVectorSourceOptions,
  HonuaOgcCollectionTileRequest,
  HonuaOgcCollectionTilesetRequest,
  HonuaOgcCollectionTilesetsRequest,
  HonuaOgcTilesOptions,
  HonuaOgcTilesetOptions,
  MapLibreVectorSourceSpec,
} from "./core/ogc-tiles.js";
export {
  createHonuaOgcMaps,
  HonuaOgcCollectionMap,
  HonuaOgcMaps,
} from "./core/ogc-maps.js";
export type {
  HonuaOgcCollectionMapImageRequest,
  HonuaOgcCollectionMapOptions,
  HonuaOgcMapsOptions,
} from "./core/ogc-maps.js";
export {
  createHonuaOgcRecords,
  HonuaOgcRecordCollection,
  HonuaOgcRecords,
} from "./core/ogc-records.js";
export type {
  HonuaOgcRecordCollectionItemRequest,
  HonuaOgcRecordCollectionOptions,
  HonuaOgcRecordCollectionRawItemRequest,
  HonuaOgcRecordCollectionRawSearchRequest,
  HonuaOgcRecordCollectionSearchAllRequest,
  HonuaOgcRecordCollectionSearchRequest,
  HonuaOgcRecordsOptions,
  HonuaOgcRecordsSearchAllRequest,
} from "./core/ogc-records.js";
export {
  createGeoServicesGpAdapter,
  createGeospatialGrpcProcessAdapter,
  createHonuaProcessRunner,
  createOgcProcessesAdapter,
  HonuaProcessRunner,
} from "./core/process-runner.js";
export type {
  GeospatialGrpcCancelJobResponse,
  GeospatialGrpcErrorDetail,
  GeospatialGrpcGetJobResponse,
  GeospatialGrpcGetJobResultResponse,
  GeospatialGrpcJobProgress,
  GeospatialGrpcProcessClient,
  GeospatialGrpcSubmitJobResponse,
  HonuaProcessAdapter,
  HonuaProcessExecuteRequest,
  HonuaProcessJobOptions,
  HonuaProcessProtocol,
} from "./core/process-runner.js";
export {
  createHonuaOgcProcesses,
  HonuaJobFailedError,
  HonuaOgcProcessJobRun,
  HonuaOgcProcesses,
} from "./core/ogc-processes.js";
export type {
  HonuaOgcProcessJobOptions,
  HonuaOgcProcessesConformanceInput,
  HonuaOgcProcessesOptions,
} from "./core/ogc-processes.js";
export {
  createHonuaStacSearch,
  HonuaStacSearch,
} from "./core/stac.js";
export type {
  HonuaStacSearchAllRequest,
  HonuaStacSearchOptions,
} from "./core/stac.js";
export {
  HonuaOdataEntitySet,
  buildOdataSpatialFilter,
  odataFieldSchema,
  parseOdataMetadata,
  rewriteWhereToOdataFilter,
} from "./core/odata.js";
export type {
  HonuaOdataAdvertisedCapabilities,
  HonuaOdataAggregateResult,
  HonuaOdataBatchOperation,
  HonuaOdataBatchOptions,
  HonuaOdataBatchOutcome,
  HonuaOdataBatchResult,
  HonuaOdataDeltaPage,
  HonuaOdataEntitySetOptions,
  HonuaOdataFieldInfo,
  HonuaOdataMetadata,
  HonuaOdataPage,
  HonuaOdataQueryParams,
  HonuaOdataWriteRequestOptions,
  OdataSpatialFilterContext,
} from "./core/odata.js";
export {
  HonuaOdataEdmEncodingError,
  encodeOdataEntityKey,
  encodeOdataWriteBody,
} from "./core/odata-write-codec.js";
export type {
  HonuaOdataEdmEncodingErrorCode,
  HonuaOdataEdmEncodingOptions,
  HonuaOdataEncodedEntityKey,
  HonuaOdataEncodedWriteBody,
  HonuaOdataEntityKeyEncodingOptions,
} from "./core/odata-write-codec.js";
export {
  HonuaWfs,
  HonuaWfsFeatureType,
  HonuaWfsStoredQuery,
  rethrowAsWfsExceptionIfPossible,
} from "./core/wfs.js";
export type {
  HonuaWfsOptions,
  OutputFormatChoice,
} from "./core/wfs.js";
export { createHonuaWms, HonuaWms, HonuaWmsLayer } from "./core/wms.js";
export type { HonuaWmsLayerOptions, HonuaWmsOptions } from "./core/wms.js";
export { createHonuaWmts, HonuaWmts, HonuaWmtsLayer, HonuaWmtsTileset } from "./core/wmts.js";
export type { HonuaWmtsLayerOptions, HonuaWmtsOptions, HonuaWmtsTilesetOptions } from "./core/wmts.js";
export {
  HonuaWmsCapabilitiesParseError,
  findWmsLayer,
  iterateWmsLayers,
  parseWmsCapabilities,
} from "./core/wms-capabilities.js";
export type {
  WmsCapabilities,
  WmsCapabilitiesFormats,
  WmsCapabilitiesRequestSupport,
  WmsCapabilitiesService,
  WmsCapabilityBoundingBox,
  WmsCapabilityDimension,
  WmsCapabilityLayer,
  WmsCapabilityOperation,
  WmsCapabilityStyle,
  WmsOperationName,
} from "./core/wms-capabilities.js";
export {
  HonuaWmtsCapabilitiesParseError,
  findWmtsLayer,
  findWmtsTileMatrixSet,
  parseWmtsCapabilities,
} from "./core/wmts-capabilities.js";
export type {
  WmtsCapabilities,
  WmtsCapabilitiesService,
  WmtsCapabilityDimension,
  WmtsCapabilityLayer,
  WmtsCapabilityOperation,
  WmtsCapabilityResourceUrl,
  WmtsCapabilityStyle,
  WmtsCapabilityTileMatrix,
  WmtsCapabilityTileMatrixSet,
} from "./core/wmts-capabilities.js";
export type {
  HonuaWmsFeatureInfoResponse,
  HonuaWmsImageResponse,
  HonuaWmtsFeatureInfoResponse,
  HonuaWmtsTileResponse,
  WmsCrs,
  WmsFeatureInfoRequest,
  WmsLegendRequest,
  WmsMapRequest,
  WmtsFeatureInfoRequest,
  WmtsTileMode,
  WmtsTileRequest,
} from "./core/wms-types.js";
export {
  hasOgcConformanceClass,
  negotiateOgcCapabilities,
} from "./core/ogc-conformance.js";
export type { OgcConformanceProtocol } from "./core/ogc-conformance.js";
export type {
  ApplyEditsRequest,
  ExportMapRequest,
  HonuaApplyEditsResponse,
  HonuaAttachmentEditResult,
  HonuaAttachmentGroup,
  HonuaAttachmentInfo,
  HonuaAttachmentListResponse,
  HonuaApiEnvelope,
  HonuaAuthCredentials,
  HonuaAuthCredentialsProvider,
  HonuaAuthProvider,
  HonuaAuthProviderContext,
  HonuaAuthProviderResult,
  HonuaAuthRefreshReason,
  HonuaAuthRevocationContext,
  HonuaCompatibilityRequest,
  HonuaClientOptions,
  HonuaCountResponse,
  HonuaEditResult,
  HonuaExportMapResponse,
  HonuaExtent,
  HonuaExtentResponse,
  HonuaFeature,
  HonuaFieldInfo,
  HonuaFindResponse,
  HonuaFindResult,
  HonuaIdentifyResponse,
  HonuaIdentifyResult,
  HonuaLayerMetadata,
  HonuaLegendEntry,
  HonuaLegendLayer,
  HonuaLegendResponse,
  HonuaObjectIdsResponse,
  HonuaOgcFeatureCollectionResponse,
  HonuaOgcFeatureResponse,
  HonuaOgcLink,
  HonuaOgcMapImageResponse,
  HonuaOgcProcessDescription,
  HonuaOgcProcessJobAccepted,
  HonuaOgcProcessJobResults,
  HonuaOgcProcessJobStatus,
  HonuaOgcProcessSummary,
  HonuaOgcProcessesResponse,
  HonuaOgcTileMatrix,
  HonuaOgcTileMatrixSet,
  HonuaOgcTileMatrixSetsResponse,
  HonuaOgcTileResponse,
  HonuaOgcTilesetMetadata,
  HonuaOgcTilesetsResponse,
  HonuaQueryAttachmentsResponse,
  HonuaQueryResponse,
  HonuaRawRequest,
  HonuaRelatedRecordGroup,
  HonuaRelatedRecordsResponse,
  HonuaRelationshipInfo,
  HonuaAddAttachmentResponse,
  HonuaUpdateAttachmentResponse,
  HonuaDeleteAttachmentsResponse,
  HonuaOgcLandingResponse,
  HonuaOgcConformanceResponse,
  HonuaOgcCollectionSummary,
  HonuaOgcCollectionsResponse,
  HonuaOgcCollectionMetadata,
  HonuaOgcQueryableProperty,
  HonuaOgcQueryablesResponse,
  HonuaOgcRecordProperties,
  HonuaOgcRecordResponse,
  HonuaOgcRecordsResponse,
  HonuaStacItemCollectionResponse,
  HonuaStacItemResponse,
  HonuaStacLandingResponse,
  HonuaStacAsset,
  HonuaStacRasterBand,
  HonuaErrorContext,
  HonuaRequestContext,
  HonuaRequestInterceptor,
  HonuaRequestMutation,
  HonuaRetryOptions,
  HonuaResponseContext,
  HonuaServerCapabilitiesResponse,
  HonuaServerCompatibility,
  HonuaServerCompatibilityControlPlaneApi,
  HonuaServerCompatibilityFeature,
  HonuaServerCompatibilityFeatures,
  HonuaServerCompatibilityMetadataSchema,
  HonuaServerCompatibilityStatus,
  HonuaServiceMetadata,
  HonuaSpatialReference,
  HonuaTransport,
  HonuaTypedFeature,
  HonuaTypedQueryResponse,
  MapFindRequest,
  MapIdentifyRequest,
  MapLayerQueryRequest,
  MapLegendRequest,
  MapRelatedRecordsRequest,
  MigrationCompatibilityAssessment,
  MigrationCutoverReadinessItem,
  MigrationCutoverReadinessSummary,
  MigrationEvidenceState,
  MigrationExternalDependency,
  MigrationInventoryAuthPosture,
  MigrationInventoryCodedValue,
  MigrationInventoryCompleteness,
  MigrationInventoryContainer,
  MigrationInventoryField,
  MigrationInventoryResource,
  MigrationInventoryScanRequest,
  MigrationInventorySourceKind,
  MigrationInventoryStyle,
  MigrationInventorySummary,
  MigrationManifestArtifact,
  MigrationManifestReviewItem,
  MigrationManifestStyleAction,
  MigrationManifestSummary,
  MigrationManifestTargetResource,
  MigrationParityEvidenceArtifact,
  MigrationParityEvidenceItem,
  MigrationParityEvidenceSection,
  MigrationReadinessAttestation,
  MigrationReadinessAttestationItem,
  MigrationSourceIdentity,
  MigrationSourceInventoryArtifact,
  MigrationSpatialReferenceInfo,
  OgcCollectionRequest,
  OgcCreateItemRequest,
  OgcDeleteItemRequest,
  OgcItemRequest,
  OgcItemsRequest,
  OgcMapImageRequest,
  OgcMapFormat,
  OgcMetadataRequest,
  OgcPatchItemRequest,
  OgcProcessExecuteRequest,
  OgcProcessIoValue,
  OgcProcessInputs,
  OgcProcessJobRequest,
  OgcProcessStatus,
  OgcReplaceItemRequest,
  OgcResponseFormat,
  OgcTileDataType,
  OgcTileMatrixSetId,
  OgcTileRequest,
  OgcTilesetRequest,
  OgcTilesetsRequest,
  QueryFeaturesRequest,
  QueryMethod,
  QueryRelatedRecordsRequest,
  EsriGeometryType,
  EsriSpatialRel,
  EsriFieldType,
  EsriPoint,
  EsriPolyline,
  EsriPolygon,
  EsriEnvelope,
  EsriMultipoint,
  EsriGeometry,
  GeoJsonFeature,
  HonuaServicesResponse,
  OgcRecordItemRequest,
  OgcRecordRawItemRequest,
  OgcRecordsRawSearchRequest,
  OgcRecordsSearchRequest,
  StacSearchRequest,
} from "./core/types.js";
export type {
  HonuaFeatureLayerAddAttachmentRequest,
  HonuaFeatureLayerAttachmentData,
  HonuaFeatureLayerApplyEditsRequest,
  HonuaFeatureLayerDeleteAttachmentsRequest,
  HonuaFeatureLayerListAttachmentsRequest,
  HonuaFeatureLayerOptions,
  HonuaFeatureLayerQueryAllRequest,
  HonuaFeatureLayerQueryAttachmentsRequest,
  HonuaFeatureLayerQueryCountRequest,
  HonuaFeatureLayerQueryExtentRequest,
  HonuaFeatureLayerQueryExtentResponse,
  HonuaFeatureLayerQueryObjectIdsRequest,
  HonuaFeatureLayerQueryRelatedRecordsRequest,
  HonuaFeatureLayerQueryRequest,
  HonuaFeatureLayerRequest,
  HonuaFeatureLayerSpatialAggregationRequest,
  HonuaFeatureLayerUpdateAttachmentRequest,
  HonuaGeometryBinaryOperationRequest,
  HonuaGeometryBufferRequest,
  HonuaGeometryClipRequest,
  HonuaGeometryDifferenceRequest,
  HonuaGeometryIntersectRequest,
  HonuaGeometryOperationResponse,
  HonuaGeometryProjectRequest,
  HonuaGeometryServiceOptions,
  HonuaGeometrySimplifyRequest,
  HonuaGeometryUnionRequest,
  HonuaGeoprocessingJob,
  HonuaGeoprocessingJobRunOptions,
  HonuaGeoprocessingJobRunRequestOptions,
  HonuaGeoprocessingServiceOptions,
  HonuaGeoprocessingSubmitRequest,
  HonuaImageServiceExportRequest,
  HonuaImageServiceIdentifyRequest,
  HonuaImageServiceOptions,
  HonuaImageServiceQueryRequest,
  HonuaMapServiceExportMapRequest,
  HonuaMapServiceFindRequest,
  HonuaMapServiceIdentifyRequest,
  HonuaMapServiceLegendRequest,
  HonuaMapServiceRequest,
  HonuaMapLayerOptions,
  HonuaMapLayerQueryAllRequest,
  HonuaMapLayerQueryCountRequest,
  HonuaMapLayerQueryExtentRequest,
  HonuaMapLayerQueryExtentResponse,
  HonuaMapLayerQueryObjectIdsRequest,
  HonuaMapLayerQueryRelatedRecordsRequest,
  HonuaMapLayerQueryRequest,
  HonuaMapLayerRequest,
  HonuaMapServiceQueryLayerAllRequest,
  HonuaMapServiceQueryLayerCountRequest,
  HonuaMapServiceQueryLayerExtentRequest,
  HonuaMapServiceQueryLayerExtentResponse,
  HonuaMapServiceQueryLayerObjectIdsRequest,
  HonuaMapServiceQueryLayerRelatedRecordsRequest,
  HonuaMapServiceQueryLayerRequest,
  HonuaMapServiceOptions,
  HonuaOgcCollectionCreateItemRequest,
  HonuaOgcCollectionDeleteItemRequest,
  HonuaOgcCollectionItemRequest,
  HonuaOgcCollectionItemsAllRequest,
  HonuaOgcCollectionItemsRequest,
  HonuaOgcCollectionPatchItemRequest,
  HonuaOgcCollectionReplaceItemRequest,
  HonuaOgcCollectionRequest,
  HonuaOgcCreateItemRequest,
  HonuaOgcDeleteItemRequest,
  HonuaOgcFeatureCollectionOptions,
  HonuaOgcFeaturesOptions,
  HonuaOgcItemRequest,
  HonuaOgcItemsAllRequest,
  HonuaOgcItemsRequest,
  HonuaOgcMetadataRequest,
  HonuaOgcPatchItemRequest,
  HonuaOgcReplaceItemRequest,
  HonuaServiceOptions,
} from "./core/surfaces.js";
export { HonuaGeocodingClient } from "./geocoding/index.js";
export type {
  GeocodingClientOptions,
  ForwardGeocodeOptions,
  ReverseGeocodeOptions,
  SuggestOptions,
  GeocodeResult,
  ReverseGeocodeResult,
  GeocodeSuggestion,
} from "./geocoding/index.js";

export {
  ANALYTICS_SOURCE_SCHEMA_VERSION,
  CAPABILITIES,
  FEATURE_SERVER_H3_SPATIAL_AGGREGATION_INDEX_MODEL_ID,
  PROTOCOL_DEFAULT_CAPABILITIES,
  PROTOCOLS,
  SPATIAL_AGGREGATION_CAPABILITY,
  SPATIAL_AGGREGATION_METADATA_SCHEMA_VERSION,
  SPATIAL_AGGREGATION_SCHEMA_VERSION,
  WIDGET_SOURCE_SCHEMA_VERSION,
  ALL_CAPABILITIES,
  FIRST_PARTY_PROTOCOLS,
  QUERY_TILE_SERVER_CONTRACT_VERSION,
  QUERY_TILE_SERVER_FEATURE_DETAIL_ROUTE_TEMPLATE,
  QUERY_TILE_SERVER_RESPONSE_HEADERS,
  QUERY_TILE_SERVER_ROUTE_PREFIX,
  QUERY_TILE_SERVER_SOURCE_ROUTE_TEMPLATE,
  QUERY_TILE_SERVER_TILEJSON_ROUTE_TEMPLATE,
  QUERY_TILE_SERVER_TILE_ROUTE_TEMPLATE,
  assertFeatureServerH3SpatialAggregationRequest,
  assertValidSpatialAggregationRequest,
  analyticsSourceDegradedReason,
  analyticsSourceId,
  assessAnalyticsSourcePushdown,
  buildAnalyticsSourceCacheKey,
  buildQueryTileCacheKey,
  buildQueryTileFeatureDetailQuery,
  buildQueryTileServerPath,
  buildQueryTileServerUrl,
  capabilities,
  createDiscoveryCacheIdentity,
  createEditSession,
  createDataset,
  createEditSketchWorkflow,
  createWidgetSource,
  defineIndexedSpatialSource,
  defineQueryTileSource,
  defineWarehouseQuerySource,
  defineWarehouseTableSource,
  defineWarehouseTilesetSource,
  EditSketchWorkflowModel,
  EditWorkflowSession,
  geoServicesFeatureSource,
  geoServicesGPServiceSource,
  geoServicesGeometryServiceSource,
  geoServicesImageSource,
  geoServicesMapServiceSource,
  HonuaJobPollTimeoutError,
  intersectCapabilities,
  inspectDiscoveredSource,
  isAnalyticsSourceDescriptor,
  isJobTerminal,
  isSpatialAggregationComplete,
  loadQueryTileFeatureDetail,
  mapQueryTileFeatureIdentity,
  normalizeQueryTileKey,
  normalizeDiscoveryEndpoint,
  normalizeQueryTileSourceDescriptor,
  normalizeAnalyticsSourceDescriptor,
  normalizeEditWorkflowFailures,
  odataSource,
  ogcFeaturesSource,
  ogcMapsSource,
  ogcRecordsSource,
  ogcTilesSource,
  parseQueryTileFeatureDetailResponse,
  parseQueryTileJson,
  parseQueryTileServerErrorResponse,
  queryTileKeyString,
  queryTileServerRequestParamsFromDescriptor,
  resolveSpatialAggregationWidgetSummary,
  resolveDiscoveryCapabilities,
  spatialAggregationProgress,
  spatialAggregationSummaryKindSupportedByFeatureServerH3,
  spatialAggregationSummaryKindRequiresField,
  spatialAggregationWidgets,
  stableJson,
  stacSearchSource,
  TEMPORAL_CAPABILITY,
  TEMPORAL_ROUTE_PREFIX,
  TEMPORAL_ROUTES,
  TEMPORAL_SCHEMA_VERSION,
  assertValidTemporalRollbackPlanRequest,
  createTemporalClient,
  isReadOnlyTemporalHistory,
  temporalModeSupports,
  validateTemporalRollbackPlanRequest,
  unionCapabilities,
  validateFeatureServerH3SpatialAggregationRequest,
  validateSpatialAggregationRequest,
  widgetSource,
  wfsSource,
  wmsSource,
  wmtsSource,
  HonuaDiscoveryError,
} from "./contract/index.js";
export type {
  AdapterFor,
  AdapterKind,
  AdapterTypeMap,
  AggregationFn,
  AggregationHistogramBucketAliases,
  AggregationHistogramBucketSpec,
  AggregationMetric,
  AggregationSpec,
  AggregationTimeIntervalSpec,
  AggregationTimeIntervalUnit,
  AggregationTimeSeriesAliases,
  AggregationTimeSeriesSpec,
  AnalyticsIndexCoverageDescriptor,
  AnalyticsIndexCoverageKind,
  AnalyticsIndexDescriptor,
  AnalyticsIndexHierarchy,
  AnalyticsSourceCacheIdentity,
  AnalyticsSourceCacheKeyOptions,
  AnalyticsSourceCachePolicy,
  AnalyticsSourceCapabilityMetadata,
  AnalyticsSourceDescriptor,
  AnalyticsSourceDescriptorBase,
  DiscoveryCacheIdentityOptions,
  DiscoveryAxisOrderMetadata,
  DiscoveryCapabilityEvidence,
  DiscoveryCapabilityPolicy,
  DiscoveryCapabilityResolution,
  DiscoveryDimensionMetadata,
  DiscoveryOperationMetadata,
  DiscoverySourceMetadata,
  DiscoveryStyleMetadata,
  DiscoveryTileMatrixMetadata,
  DiscoveryTileMatrixSetMetadata,
  AnalyticsSourceFallbackMode,
  AnalyticsSourceFallbackPolicy,
  AnalyticsSourceKind,
  AnalyticsSourceProtocolEscapeHatch,
  AnalyticsSourcePushdownAssessment,
  AnalyticsSourcePushdownCapability,
  AnalyticsSourceRelationDescriptor,
  AnalyticsSourceSchemaVersion,
  AnalyticsSourceSqlDescriptor,
  AnalyticsSourceTilesetDescriptor,
  AnalyticsWarehouseProvider,
  AttachmentAdd,
  AttachmentApi,
  AttachmentDelete,
  AttachmentEditOutcome,
  AttachmentGroup,
  AttachmentInfo,
  AttachmentQuery,
  AttachmentUpdate,
  CanonicalFeature,
  Capabilities,
  Capability,
  CapabilityPolicy,
  CreateDatasetOptions,
  CreateEditSessionOptions,
  Dataset,
  DatasetId,
  DegradedReason,
  EditAttachmentMutation,
  EditAttachmentMutationOutcome,
  EditEnvelope,
  EditOutcome,
  EditResult,
  EditFieldDomain,
  EditFieldDomainCodedValue,
  EditWorkflowCapabilityState,
  EditWorkflowCapabilitySummary,
  EditWorkflowConflictInfo,
  EditWorkflowConflictState,
  EditWorkflowFailure,
  EditWorkflowFailureKind,
  EditWorkflowField,
  EditWorkflowKind,
  EditWorkflowMetadata,
  EditWorkflowMetadataOptions,
  EditWorkflowOperation,
  EditWorkflowOptimisticHooks,
  EditWorkflowRelationship,
  EditWorkflowSnapshot,
  EditWorkflowStatus,
  EditWorkflowSubmitResult,
  EditWorkflowValidationError,
  EditWorkflowValidationResult,
  EditAnnotationPersistenceHook,
  EditAnnotationPersistenceSnapshot,
  EditAnnotationPersistenceState,
  EditSketchCapabilityState,
  EditSketchStatus,
  EditSketchTool,
  EditSketchToolCapability,
  EditSketchToolCapabilityInput,
  EditSketchUndoSnapshot,
  EditSketchWorkflowOptions,
  EditSketchWorkflowSnapshot,
  FeatureId,
  FeatureInfoRequestBinding,
  IndexedSpatialSourceDescriptor,
  IJobRun,
  JobError,
  JobProgress,
  JobResult,
  JobResultsOptions,
  JobSnapshot,
  JobSnapshotListener,
  JobStatus,
  MapBinding,
  OdataSourceOptions,
  OdataWriteEncoding,
  PaginationSpec,
  Protocol,
  Query,
  RasterRequestBinding,
  QueryTileCacheIdentityDescriptor,
  QueryTileCacheKeyOptions,
  QueryTileCachePolicy,
  QueryTileEndpointDescriptor,
  QueryTileFallbackMode,
  QueryTileFallbackPolicy,
  QueryTileFeatureDetailOptions,
  QueryTileFeatureIdentityContext,
  QueryTileFeatureIdentityDescriptor,
  QueryTileFeatureIdentityMapper,
  QueryTileFeatureIdentityTarget,
  QueryTileFormat,
  QueryTileFeatureDetailResponse,
  QueryTileJson,
  QueryTileJsonVectorLayer,
  QueryTileKey,
  QueryTileKeyInput,
  QueryTileProjectionDescriptor,
  QueryTileScheme,
  QueryTileServerCachePolicyDescriptor,
  QueryTileServerCacheValidators,
  QueryTileServerContractFixture,
  QueryTileServerDegradation,
  QueryTileServerDegradationCode,
  QueryTileServerDegradationSeverity,
  QueryTileServerError,
  QueryTileServerErrorCode,
  QueryTileServerErrorResponse,
  QueryTileServerFeatureIdentityDescriptor,
  QueryTileServerLimitDescriptor,
  QueryTileServerRequestParameters,
  QueryTileServerRouteKind,
  QueryTileServerRouteOptions,
  QueryTileServerTileJsonMetadata,
  QueryTileSpatialReference,
  QueryTileSpatialReferenceDescriptor,
  QueryTileExtentDescriptor,
  QueryTileSourceDescriptor,
  DefineQueryTileSourceOptions,
  RelatedGroup,
  RelatedQuery,
  RelatedResult,
  ResolveSourceContext,
  Result,
  NormalizeEditWorkflowFailuresOptions,
  SortSpec,
  Source,
  SourceAnalyticsCapabilities,
  SourceDescriptor,
  SourceFreshnessContract,
  SourceHistogramCapabilityMetadata,
  SourceId,
  SourceLocator,
  SourceResolver,
  SourceSchema,
  SourceTimeSeriesCapabilityMetadata,
  SpatialAggregationCacheMetadata,
  SpatialAggregationCategoryBucket,
  SpatialAggregationCategorySummarySpec,
  SpatialAggregationCategoryValue,
  SpatialAggregationCell,
  SpatialAggregationCellGeometry,
  SpatialAggregationContractFixture,
  SpatialAggregationCountSummarySpec,
  SpatialAggregationCountValue,
  SpatialAggregationDomainValue,
  SpatialAggregationGroupByMetadata,
  SpatialAggregationGroupBySpec,
  SpatialAggregationGroupedSummary,
  SpatialAggregationHistogramBucket,
  SpatialAggregationHistogramSummarySpec,
  SpatialAggregationHistogramValue,
  SpatialAggregationInclude,
  SpatialAggregationIndexModelMetadata,
  SpatialAggregationIndexCoverageMetadata,
  SpatialAggregationIndexSelection,
  SpatialAggregationIndexState,
  SpatialAggregationMetadata,
  SpatialAggregationMetricKind,
  SpatialAggregationMetricSummarySpec,
  SpatialAggregationMetricValue,
  SpatialAggregationPageInfo,
  SpatialAggregationPageRequest,
  SpatialAggregationProgressRefinement,
  SpatialAggregationProgressStatus,
  SpatialAggregationProgressiveState,
  SpatialAggregationRangeBucketSpec,
  SpatialAggregationRangeBucketValue,
  SpatialAggregationRangeSummarySpec,
  SpatialAggregationRangeValue,
  SpatialAggregationRequest,
  SpatialAggregationResolutionInput,
  SpatialAggregationResult,
  SpatialAggregationSummaryBag,
  SpatialAggregationSummaryBase,
  SpatialAggregationSummaryKind,
  SpatialAggregationSummaryMetadata,
  SpatialAggregationSummarySpec,
  SpatialAggregationSummaryValue,
  SpatialAggregationValidationIssue,
  SpatialAggregationValueType,
  SpatialAggregationViewport,
  SpatialAggregationWidgetKind,
  SpatialAggregationWidgetMetadata,
  WidgetCategoriesRequest,
  WidgetCategoriesResult,
  WidgetCategoryBucket,
  WidgetCountRequest,
  WidgetCountResult,
  WidgetFormulaRequest,
  WidgetFormulaResult,
  WidgetHistogramBin,
  WidgetHistogramRequest,
  WidgetHistogramResult,
  WidgetRangeRequest,
  WidgetRangeResult,
  WidgetSource,
  WidgetSourceCacheHints,
  WidgetSourceCacheMetadata,
  WidgetSourceExecutionMode,
  WidgetSourceFilterClause,
  WidgetSourceFreshnessContract,
  WidgetSourceModelKind,
  WidgetSourceOptions,
  WidgetSourceOrderBy,
  WidgetSourceProjection,
  WidgetSourceRequestBase,
  WidgetSourceResponseBase,
  WidgetSourceSchemaVersion,
  WidgetSourceValue,
  WidgetTimeSeriesBucket,
  WidgetTimeSeriesInterval,
  WidgetTimeSeriesIntervalUnit,
  WidgetTimeSeriesRequest,
  WidgetTimeSeriesResult,
  WidgetTopValueBucket,
  WidgetTopValuesRequest,
  WidgetTopValuesResult,
  WarehouseQuerySourceDescriptor,
  WarehouseTableSourceDescriptor,
  WarehouseTilesetSourceDescriptor,
  TemporalAsOfRequest,
  TemporalAttributeChange,
  TemporalCheckpoint,
  TemporalChangeSet,
  TemporalChangeSetOperationKind,
  TemporalClient,
  TemporalClientCallOptions,
  TemporalContractFixture,
  TemporalCursor,
  TemporalCursorType,
  TemporalDiff,
  TemporalDiffRequest,
  TemporalDiffStatus,
  TemporalDiffSummary,
  TemporalError,
  TemporalErrorCode,
  TemporalFeatureChangeType,
  TemporalFeatureDiff,
  TemporalFeatureTimeline,
  TemporalFeatureTimelineRequest,
  TemporalFilter,
  TemporalGeometryChange,
  TemporalHistoryModel,
  TemporalJobRef,
  TemporalMode,
  TemporalRequestClient,
  TemporalRevision,
  TemporalRevisionOperation,
  TemporalRiskLevel,
  TemporalRollbackExecuteRequest,
  TemporalRollbackMode,
  TemporalRollbackOperation,
  TemporalRollbackPlan,
  TemporalRollbackPlanRequest,
  TemporalRollbackScope,
  TemporalRollbackStatus,
  TemporalSourceCapability,
  TemporalValidationIssue,
} from "./contract/index.js";

export {
  EMPTY_STATE,
  EMPTY_STATE as EXPLORATION_EMPTY_STATE,
  LINKED_VIEW_PRESETS,
  SLICES,
  SLICES as EXPLORATION_SLICES,
  createExplorationContext,
  featureSelectionKey,
  isSourceQualifiedSelectionTarget,
  propagationFor,
  reduce,
  reduce as reduceExplorationState,
  sourceFeatureSelectionTarget,
} from "./exploration/index.js";
export type {
  ApplyPresetIntent,
  ChangeEvent,
  ClearFilterIntent,
  CreateExplorationContextOptions,
  DeselectIntent,
  ExplorationContext,
  ExplorationIntent,
  ExplorationSlice,
  ExplorationState,
  ExplorationStateSnapshot,
  ExplorationViewChangeEvent,
  ExplorationViewController,
  ExplorationViewIntent,
  ExplorationViewListener,
  ExplorationViewSubscribeOptions,
  ExplorationViewSubscription,
  FeatureSelectionTarget,
  FilterClause,
  FilterOperator,
  LinkedViewPolicy,
  LinkedViewPresetName,
  LinkedViewRule,
  Listener as ExplorationListener,
  ReducerResult,
  SelectIntent,
  SetAggregationIntent,
  SetExtentIntent,
  SetFilterIntent,
  SetGroupingIntent,
  SetPageIntent,
  SetSortIntent,
  SetSpatialFilterIntent,
  SetVisibleFieldsIntent,
  SnapshotRestoreIntent,
  SourceQualifiedFeatureSelectionTarget,
  Unsubscribe as ExplorationUnsubscribe,
  ViewBinding,
  ViewHandle,
  ViewRole,
} from "./exploration/index.js";

// Experimental app-controller / app-workspace / agent-tools / control-plane
// surfaces are subpath-only — import them from their named subpaths:
//   import { HonuaController } from "@honua/sdk-js/app-controller";
//   import { HonuaAppWorkspace } from "@honua/sdk-js/app-workspace";
//   import { HONUA_AGENT_TOOL_DEFINITIONS } from "@honua/sdk-js/agent-tools";
//   import { HonuaControlPlaneClient } from "@honua/sdk-js/control-plane";
