export { HonuaClient, HONUA_MINIMUM_SUPPORTED_SERVER_VERSION } from "./core/client.js";
export { parseWebMap } from "./webmap/index.js";
export type { ParseWebMapOptions, ParseWebMapResult } from "./webmap/index.js";
export {
  createWarningCollector,
  CONTRACT,
  getContractSummary,
  convertSymbol,
  esriColorToCss,
  convertRenderer,
  convertPopupInfo,
  convertLabelingInfo,
  convertBasemap,
  convertExtent,
  convertInitialViewpoint,
  convertOperationalLayer,
} from "./webmap/index.js";
export type {
  WebMapWarning,
  WarningCollector,
  ContractEntry,
  ContractSupport,
  ContractSummary,
  SymbolConversionResult,
  RendererConversionResult,
  HonuaPopupConfig,
  HonuaPopupFieldInfo,
  HonuaPopupMediaInfo,
  BasemapConversionResult,
  ExtentConversionResult,
  LayerConversionResult,
  WebMapJson,
  WebMapOperationalLayer,
  WebMapRenderer,
  WebMapSymbol,
  WebMapBaseMap,
  WebMapPopupInfo,
  WebMapExtent,
  WebMapPoint,
  WebMapViewpoint,
  WebMapBookmark,
  EsriColor,
} from "./webmap/index.js";
export {
  expr,
  Expr,
  format,
  numberFormat,
  collator,
  resolvedLocale,
  hsl,
  hsla,
  toRgba,
  lineProgress,
  heatmapDensity,
  pitch,
  accumulated,
  distanceFromCenter,
} from "./expr/index.js";
export {
  isHonuaSource,
  isFeatureServiceSource,
  isMapServiceSource,
  isOgcFeaturesSource,
  parseOgcFeaturesUrl,
  validateHonuaStyle,
  createSources,
} from "./style/index.js";
export type {
  HonuaSourceBase,
  HonuaFeatureServiceSourceSpecification,
  HonuaMapServiceSourceSpecification,
  HonuaOgcFeaturesSourceSpecification,
  HonuaSourceSpecification,
  HonuaLayerSpecification,
  HonuaStyleSpecification,
  ParsedOgcFeaturesUrl,
  StyleValidationError,
  ResolvedSource,
} from "./style/index.js";
export type {
  ExprColor,
  ExprFormatted,
  ExprImage,
  ExprValue,
  NumberInput,
  StringInput,
  BooleanInput,
  ColorInput,
  Resolvable,
  InterpolationMethod,
  GeoJsonPoint,
  GeoJsonMultiPoint,
  GeoJsonLineString,
  GeoJsonMultiLineString,
  GeoJsonPolygon,
  GeoJsonMultiPolygon,
  GeoJsonGeometry,
  FormatSegmentOptions,
  NumberFormatOptions,
  CollatorOptions,
  ExprCollator,
} from "./expr/index.js";
export {
  setFeatureState,
  getFeatureState,
  removeFeatureState,
  createHoverHandler,
  createSelectionHandler,
} from "./interactions/index.js";
export type {
  FeatureStateMap,
  MapEventTarget,
  InteractiveMap,
  FeatureTarget,
  HoverHandlerOptions,
  HoverHandle,
  SelectionHandlerOptions,
  SelectionHandle,
} from "./interactions/index.js";
export { HonuaMap } from "./map/index.js";
export type {
  HonuaMapOptions,
  HonuaMapEvent,
  HonuaMapEventListener,
  LayerSnapshot,
  ResolvedMapSource,
} from "./map/index.js";
export {
  HonuaHttpError,
  HonuaTimeoutError,
  HonuaNetworkError,
  HonuaAbortError,
  HonuaGrpcError,
  HonuaCapabilityNotSupportedError,
  HonuaExplorationContextError,
  HonuaWfsExceptionError,
  isHonuaError,
} from "./core/errors.js";
export type { HonuaError } from "./core/errors.js";
export { QueryBuilder, MapLayerQueryBuilder, OgcQueryBuilder } from "./core/query-builder.js";
export {
  envelope,
  point,
  polygon,
  buffer,
  spatialIntersects,
  spatialContains,
  spatialWithin,
} from "./core/spatial-filter.js";
export type { SpatialFilter } from "./core/spatial-filter.js";
export { batchQuery } from "./core/batch.js";
export type { BatchQueryItem, BatchQueryOptions, BatchQueryResult } from "./core/batch.js";
export { decodePbfQueryResponse, isPbfResponse } from "./core/pbf-decoder.js";
export {
  createHonuaOgcFeatures,
  createHonuaService,
  HonuaFeatureLayer,
  HonuaGeometryService,
  HonuaGeoprocessingService,
  HonuaImageService,
  HonuaMapLayer,
  HonuaMapService,
  HonuaOgcFeatureCollection,
  HonuaOgcFeatures,
  HonuaService,
} from "./core/surfaces.js";
export {
  createHonuaOgcTiles,
  HonuaOgcTiles,
  HonuaOgcTileset,
} from "./core/ogc-tiles.js";
export type {
  HonuaOgcCollectionTileRequest,
  HonuaOgcCollectionTilesetRequest,
  HonuaOgcCollectionTilesetsRequest,
  HonuaOgcTilesOptions,
  HonuaOgcTilesetOptions,
} from "./core/ogc-tiles.js";
export {
  createHonuaOgcMaps,
  HonuaOgcCollectionMap,
  HonuaOgcMaps,
} from "./core/ogc-maps.js";
export type {
  HonuaOgcCollectionMapImageRequest,
  HonuaOgcCollectionMapOptions,
  HonuaOgcMapsOptions,
} from "./core/ogc-maps.js";
export {
  createHonuaOgcProcesses,
  HonuaJobFailedError,
  HonuaOgcProcessJobRun,
  HonuaOgcProcesses,
} from "./core/ogc-processes.js";
export type {
  HonuaOgcProcessJobOptions,
  HonuaOgcProcessesOptions,
} from "./core/ogc-processes.js";
export {
  createHonuaStacSearch,
  HonuaStacSearch,
} from "./core/stac.js";
export type {
  HonuaStacSearchAllRequest,
  HonuaStacSearchOptions,
} from "./core/stac.js";
export {
  hasOgcConformanceClass,
  negotiateOgcCapabilities,
} from "./core/ogc-conformance.js";
export type { OgcConformanceProtocol } from "./core/ogc-conformance.js";
export type {
  ApplyEditsRequest,
  ExportMapRequest,
  HonuaApplyEditsResponse,
  HonuaAttachmentEditResult,
  HonuaAttachmentGroup,
  HonuaAttachmentInfo,
  HonuaAttachmentListResponse,
  HonuaApiEnvelope,
  HonuaCompatibilityRequest,
  HonuaClientOptions,
  HonuaCountResponse,
  HonuaEditResult,
  HonuaExportMapResponse,
  HonuaExtent,
  HonuaExtentResponse,
  HonuaFeature,
  HonuaFieldInfo,
  HonuaFindResponse,
  HonuaFindResult,
  HonuaIdentifyResponse,
  HonuaIdentifyResult,
  HonuaLayerMetadata,
  HonuaLegendEntry,
  HonuaLegendLayer,
  HonuaLegendResponse,
  HonuaObjectIdsResponse,
  HonuaOgcFeatureCollectionResponse,
  HonuaOgcFeatureResponse,
  HonuaOgcLink,
  HonuaOgcMapImageResponse,
  HonuaOgcProcessDescription,
  HonuaOgcProcessJobAccepted,
  HonuaOgcProcessJobResults,
  HonuaOgcProcessJobStatus,
  HonuaOgcProcessSummary,
  HonuaOgcProcessesResponse,
  HonuaOgcTileMatrix,
  HonuaOgcTileMatrixSet,
  HonuaOgcTileMatrixSetsResponse,
  HonuaOgcTileResponse,
  HonuaOgcTilesetMetadata,
  HonuaOgcTilesetsResponse,
  HonuaQueryAttachmentsResponse,
  HonuaQueryResponse,
  HonuaRawRequest,
  HonuaRelatedRecordGroup,
  HonuaRelatedRecordsResponse,
  HonuaRelationshipInfo,
  HonuaAddAttachmentResponse,
  HonuaUpdateAttachmentResponse,
  HonuaDeleteAttachmentsResponse,
  HonuaOgcLandingResponse,
  HonuaOgcConformanceResponse,
  HonuaOgcCollectionSummary,
  HonuaOgcCollectionsResponse,
  HonuaOgcCollectionMetadata,
  HonuaOgcQueryableProperty,
  HonuaOgcQueryablesResponse,
  HonuaStacItemCollectionResponse,
  HonuaStacItemResponse,
  HonuaStacLandingResponse,
  HonuaErrorContext,
  HonuaRequestContext,
  HonuaRequestInterceptor,
  HonuaRequestMutation,
  HonuaRetryOptions,
  HonuaResponseContext,
  HonuaServerCapabilitiesResponse,
  HonuaServerCompatibility,
  HonuaServerCompatibilityControlPlaneApi,
  HonuaServerCompatibilityFeature,
  HonuaServerCompatibilityFeatures,
  HonuaServerCompatibilityMetadataSchema,
  HonuaServerCompatibilityStatus,
  HonuaServiceMetadata,
  HonuaSpatialReference,
  HonuaTransport,
  HonuaTypedFeature,
  HonuaTypedQueryResponse,
  MapFindRequest,
  MapIdentifyRequest,
  MapLayerQueryRequest,
  MapLegendRequest,
  MapRelatedRecordsRequest,
  OgcCollectionRequest,
  OgcCreateItemRequest,
  OgcDeleteItemRequest,
  OgcItemRequest,
  OgcItemsRequest,
  OgcMapImageRequest,
  OgcMapFormat,
  OgcMetadataRequest,
  OgcPatchItemRequest,
  OgcProcessExecuteRequest,
  OgcProcessIoValue,
  OgcProcessInputs,
  OgcProcessStatus,
  OgcReplaceItemRequest,
  OgcResponseFormat,
  OgcTileDataType,
  OgcTileMatrixSetId,
  OgcTileRequest,
  OgcTilesetRequest,
  OgcTilesetsRequest,
  QueryFeaturesRequest,
  QueryMethod,
  QueryRelatedRecordsRequest,
  EsriGeometryType,
  EsriSpatialRel,
  EsriFieldType,
  EsriPoint,
  EsriPolyline,
  EsriPolygon,
  EsriEnvelope,
  EsriMultipoint,
  EsriGeometry,
  GeoJsonFeature,
  HonuaServicesResponse,
  StacSearchRequest,
} from "./core/types.js";
export type {
  HonuaFeatureLayerAddAttachmentRequest,
  HonuaFeatureLayerAttachmentData,
  HonuaFeatureLayerApplyEditsRequest,
  HonuaFeatureLayerDeleteAttachmentsRequest,
  HonuaFeatureLayerListAttachmentsRequest,
  HonuaFeatureLayerOptions,
  HonuaFeatureLayerQueryAllRequest,
  HonuaFeatureLayerQueryAttachmentsRequest,
  HonuaFeatureLayerQueryCountRequest,
  HonuaFeatureLayerQueryExtentRequest,
  HonuaFeatureLayerQueryExtentResponse,
  HonuaFeatureLayerQueryObjectIdsRequest,
  HonuaFeatureLayerQueryRelatedRecordsRequest,
  HonuaFeatureLayerQueryRequest,
  HonuaFeatureLayerRequest,
  HonuaFeatureLayerUpdateAttachmentRequest,
  HonuaGeometryBinaryOperationRequest,
  HonuaGeometryBufferRequest,
  HonuaGeometryClipRequest,
  HonuaGeometryDifferenceRequest,
  HonuaGeometryIntersectRequest,
  HonuaGeometryOperationResponse,
  HonuaGeometryProjectRequest,
  HonuaGeometryServiceOptions,
  HonuaGeometrySimplifyRequest,
  HonuaGeometryUnionRequest,
  HonuaGeoprocessingJob,
  HonuaGeoprocessingServiceOptions,
  HonuaGeoprocessingSubmitRequest,
  HonuaImageServiceExportRequest,
  HonuaImageServiceIdentifyRequest,
  HonuaImageServiceOptions,
  HonuaImageServiceQueryRequest,
  HonuaMapServiceExportMapRequest,
  HonuaMapServiceFindRequest,
  HonuaMapServiceIdentifyRequest,
  HonuaMapServiceLegendRequest,
  HonuaMapServiceRequest,
  HonuaMapLayerOptions,
  HonuaMapLayerQueryAllRequest,
  HonuaMapLayerQueryCountRequest,
  HonuaMapLayerQueryExtentRequest,
  HonuaMapLayerQueryExtentResponse,
  HonuaMapLayerQueryObjectIdsRequest,
  HonuaMapLayerQueryRelatedRecordsRequest,
  HonuaMapLayerQueryRequest,
  HonuaMapLayerRequest,
  HonuaMapServiceQueryLayerAllRequest,
  HonuaMapServiceQueryLayerCountRequest,
  HonuaMapServiceQueryLayerExtentRequest,
  HonuaMapServiceQueryLayerExtentResponse,
  HonuaMapServiceQueryLayerObjectIdsRequest,
  HonuaMapServiceQueryLayerRelatedRecordsRequest,
  HonuaMapServiceQueryLayerRequest,
  HonuaMapServiceOptions,
  HonuaOgcCollectionCreateItemRequest,
  HonuaOgcCollectionDeleteItemRequest,
  HonuaOgcCollectionItemRequest,
  HonuaOgcCollectionItemsAllRequest,
  HonuaOgcCollectionItemsRequest,
  HonuaOgcCollectionPatchItemRequest,
  HonuaOgcCollectionReplaceItemRequest,
  HonuaOgcCollectionRequest,
  HonuaOgcCreateItemRequest,
  HonuaOgcDeleteItemRequest,
  HonuaOgcFeatureCollectionOptions,
  HonuaOgcFeaturesOptions,
  HonuaOgcItemRequest,
  HonuaOgcItemsAllRequest,
  HonuaOgcItemsRequest,
  HonuaOgcMetadataRequest,
  HonuaOgcPatchItemRequest,
  HonuaOgcReplaceItemRequest,
  HonuaServiceOptions,
} from "./core/surfaces.js";
export { HonuaGeocodingClient } from "./geocoding/index.js";
export type {
  GeocodingClientOptions,
  ForwardGeocodeOptions,
  ReverseGeocodeOptions,
  SuggestOptions,
  GeocodeResult,
  ReverseGeocodeResult,
  GeocodeSuggestion,
} from "./geocoding/index.js";

export {
  CAPABILITIES,
  PROTOCOL_DEFAULT_CAPABILITIES,
  PROTOCOLS,
  ALL_CAPABILITIES,
  FIRST_PARTY_PROTOCOLS,
  capabilities,
  createDataset,
  geoServicesFeatureSource,
  geoServicesGPServiceSource,
  geoServicesGeometryServiceSource,
  geoServicesImageSource,
  geoServicesMapServiceSource,
  isJobTerminal,
  ogcFeaturesSource,
  ogcMapsSource,
  ogcTilesSource,
  stacSearchSource,
} from "./contract/index.js";
export type {
  AdapterFor,
  AdapterKind,
  AdapterTypeMap,
  AggregationFn,
  AggregationMetric,
  AggregationSpec,
  AttachmentAdd,
  AttachmentApi,
  AttachmentDelete,
  AttachmentEditOutcome,
  AttachmentGroup,
  AttachmentInfo,
  AttachmentQuery,
  AttachmentUpdate,
  CanonicalFeature,
  Capabilities,
  Capability,
  CapabilityPolicy,
  CreateDatasetOptions,
  Dataset,
  DatasetId,
  DegradedReason,
  EditEnvelope,
  EditOutcome,
  EditResult,
  FeatureId,
  IJobRun,
  JobError,
  JobProgress,
  JobResult,
  JobSnapshot,
  JobSnapshotListener,
  JobStatus,
  MapBinding,
  PaginationSpec,
  Protocol,
  Query,
  RelatedGroup,
  RelatedQuery,
  RelatedResult,
  ResolveSourceContext,
  Result,
  SortSpec,
  Source,
  SourceDescriptor,
  SourceId,
  SourceLocator,
  SourceResolver,
  SourceSchema,
} from "./contract/index.js";

export {
  EMPTY_STATE,
  LINKED_VIEW_PRESETS,
  SLICES,
  createExplorationContext,
  propagationFor,
  reduce,
} from "./exploration/index.js";
export type {
  ApplyPresetIntent,
  ChangeEvent,
  ClearFilterIntent,
  CreateExplorationContextOptions,
  DeselectIntent,
  ExplorationContext,
  ExplorationIntent,
  ExplorationSlice,
  ExplorationState,
  ExplorationStateSnapshot,
  FilterClause,
  FilterOperator,
  LinkedViewPolicy,
  LinkedViewPresetName,
  LinkedViewRule,
  Listener as ExplorationListener,
  ReducerResult,
  SelectIntent,
  SetAggregationIntent,
  SetExtentIntent,
  SetFilterIntent,
  SetGroupingIntent,
  SetPageIntent,
  SetSortIntent,
  SetSpatialFilterIntent,
  SetVisibleFieldsIntent,
  SnapshotRestoreIntent,
  Unsubscribe as ExplorationUnsubscribe,
  ViewBinding,
  ViewHandle,
  ViewRole,
} from "./exploration/index.js";
