/**
 * `@honua/sdk-js` — root barrel.
 *
 * The root entrypoint re-exports the most commonly used symbols from across the
 * SDK so newcomers can `import { HonuaClient, createDataset, ... } from "@honua/sdk-js"`
 * without learning the subpath table first. For production code, prefer the named
 * subpaths documented in [`INSTALL.md`](../../INSTALL.md):
 *
 * - `@honua/sdk-js/honua` — core client + Honua-native wrappers
 * - `@honua/sdk-js/contract` — protocol-neutral `Dataset` / `Source` / `Query` / `Result`
 * - `@honua/sdk-js/esri-compat` — Esri ArcGIS JS-API compatibility wrappers
 * - `@honua/sdk-js/migration` — codemod + scanner used by `honua-migrate`
 * - `@honua/sdk-js/expr` — Honua expression builder
 * - `@honua/sdk-js/webmap` — WebMap JSON parsing / serialization
 * - `@honua/sdk-js/runtime` — MapLibre runtime for Honua `MapPackage`
 *
 * Stability: the symbols re-exported here are covered by the SDK's semver
 * contract. Anything marked `@experimental` in JSDoc may change in any minor
 * release until the SDK reaches `1.0.0`.
 *
 * @packageDocumentation
 */
export { HonuaClient, HONUA_MINIMUM_SUPPORTED_SERVER_VERSION } from "./core/client.js";
export {
  HonuaHttpError,
  HonuaTimeoutError,
  HonuaNetworkError,
  HonuaAbortError,
  HonuaGrpcError,
  HonuaCapabilityNotSupportedError,
  HonuaExplorationContextError,
  HonuaWfsExceptionError,
  isHonuaError,
} from "./core/errors.js";
export type { HonuaError } from "./core/errors.js";
export { QueryBuilder, MapLayerQueryBuilder, OgcQueryBuilder } from "./core/query-builder.js";
export {
  envelope,
  point,
  polygon,
  buffer,
  spatialIntersects,
  spatialContains,
  spatialWithin,
} from "./core/spatial-filter.js";
export type { SpatialFilter } from "./core/spatial-filter.js";
export { batchQuery } from "./core/batch.js";
export type { BatchQueryItem, BatchQueryOptions, BatchQueryResult } from "./core/batch.js";
export { decodePbfQueryResponse, isPbfResponse } from "./core/pbf-decoder.js";
export { esriFeatureToGeoJSON, esriGeometryToGeoJSON } from "./core/esri-geojson.js";
export {
  compileRuntimeStyleFilter,
  createFilterRegistry,
  parseFilterRegistry,
  projectFilterRegistryToLinkedView,
  projectFilterRegistryToQuery,
  projectFilterRegistryToWidgetProjection,
  selectActiveFilterClauses,
  serializeFilterRegistry,
} from "./filter-registry/index.js";
export type {
  CreateFilterRegistryOptions,
  FilterClause as RegistryFilterClause,
  FilterEffect,
  FilterLifecycle,
  FilterRegistry,
  FilterRegistryChangeEvent,
  FilterRegistryListener,
  FilterRegistryOwner,
  FilterRegistryProjectionOptions,
  FilterRegistryQueryProjection,
  FilterRegistryQueryProjectionOptions,
  FilterRegistrySelector,
  FilterRegistrySelectorListener,
  FilterRegistrySelectorOptions,
  FilterRegistrySnapshot,
  FilterRegistryUnsubscribe,
  FilterRuntimeApplyMode,
  FilterSourceScope,
  FilterValuePolicy,
  RegistrySpatialScope,
  RuntimeStyleFilterExpression,
  ShareableFilterRegistryState,
} from "./filter-registry/index.js";
export {
  MIGRATION_EVIDENCE_STATES,
  MIGRATION_MANIFEST_ARTIFACT_KIND,
  MIGRATION_MANIFEST_ARTIFACT_VERSION,
  MIGRATION_PARITY_EVIDENCE_ARTIFACT_KIND,
  MIGRATION_PARITY_EVIDENCE_ARTIFACT_VERSION,
  MIGRATION_SOURCE_INVENTORY_ARTIFACT_KIND,
  MIGRATION_SOURCE_INVENTORY_ARTIFACT_VERSION,
} from "./core/types.js";
export {
  createHonuaCacheState,
  honuaCacheValidatorFromHeaders,
  honuaMetadataRequestHeaders,
  isHonuaCacheStatus,
  normalizeHonuaMetadataRequestOptions,
} from "./core/cache-state.js";
export type {
  HonuaCacheReadMode,
  HonuaCacheScope,
  HonuaCacheState,
  HonuaCacheStateInit,
  HonuaCacheStatus,
  HonuaCacheValidator,
  HonuaMetadataRequestOptions,
  NormalizedHonuaMetadataRequestOptions,
} from "./core/cache-state.js";
// Experimental subpaths previously re-exported here (collaboration, control-plane)
// must now be imported from their named subpaths so the stable / experimental
// tier is bundler-visible:
//   import { HonuaControlPlaneClient } from "@honua/sdk-js/control-plane";
//   import { HonuaSavedMapCollaborationClient } from "@honua/sdk-js/collaboration";
export {
  isHonuaSource,
  isFeatureServiceSource,
  isMapServiceSource,
  isOgcFeaturesSource,
  isWmsSource,
  isWmtsSource,
  parseOgcFeaturesUrl,
  validateHonuaStyle,
  createSources,
} from "./style/index.js";
export type {
  HonuaSourceBase,
  HonuaFeatureServiceSourceSpecification,
  HonuaMapServiceSourceSpecification,
  HonuaOgcFeaturesSourceSpecification,
  HonuaWmsSourceSpecification,
  HonuaWmtsSourceSpecification,
  HonuaSourceSpecification,
  HonuaLayerSpecification,
  HonuaStyleSpecification,
  ParsedOgcFeaturesUrl,
  StyleValidationError,
  ResolvedSource,
} from "./style/index.js";

// Expression DSL is subpath-only: import { get, eq, all, interpolate, ... } from "@honua/sdk-js/expr";
export {
  createQueryTileDetailLoader,
  hitTestMap,
  normalizeHitFeature,
  normalizeHitTestFeatures,
  normalizePointerEvent,
  setFeatureState,
  getFeatureState,
  removeFeatureState,
  createHoverHandler,
  createSelectionHandler,
  bindDetailToSelection,
  bindChartToExploration,
  bindFilterControlsToExploration,
  bindMapExtentToExploration,
  bindMapSelectionToExploration,
  bindQueryProjectionToExploration,
  extentToSpatialFilter,
  selectLinkedViewQueryProjection,
  subscribeExplorationSelector,
  bindTableSelectionToExploration,
  interactionQueryParamNames,
  parseInteractionQueryState,
  parseSelection,
  preparePrimaryDetailModel,
  prepareSelectionDetailModels,
  serializeInteractionQueryState,
  serializeSelection,
  syncMapLayerFilterToExploration,
  syncFeatureStateSelection,
} from "./interactions/index.js";
export type {
  HonuaHitFeature,
  HonuaHitTestDegradedReason,
  HonuaHitTestDegradedState,
  HonuaHitTestDetailContext,
  HonuaHitTestDetailLoader,
  HonuaHitTestFeatureOptions,
  HonuaHitTestMap,
  HonuaHitTestOptions,
  HonuaHitTestRasterSample,
  HonuaHitTestResult,
  HonuaLngLat,
  HonuaNormalizeHitTestOptions,
  HonuaPointerEvent,
  HonuaPointerEventType,
  HonuaPointerInput,
  HonuaRenderedFeatureContext,
  HonuaScreenPoint,
  FeatureStateMap,
  MapEventTarget,
  InteractiveMap,
  FeatureTarget,
  HoverHandlerOptions,
  HoverHandle,
  SelectionHandlerOptions,
  SelectionHandle,
  ChartBucketSelection,
  ChartBucketSelectionOptions,
  ChartExplorationBinding,
  ExplorationSelector,
  ExplorationSelectorListener,
  ExplorationSelectorSubscribeOptions,
  FeatureStateSelectionSyncOptions,
  FilterControlsExplorationBinding,
  InteractionBindingHandle,
  LinkedViewQueryBindingOptions,
  LinkedViewQueryProjection,
  LinkedViewQueryProjectionOptions,
  LinkedViewSpatialMode,
  MapExtentExplorationBindingOptions,
  MapExtentExplorationSource,
  MapLayerFilterExplorationBindingOptions,
  MapLayerFilterTarget,
  MapSelectionExplorationBindingOptions,
  SelectionDetailListener,
  TableSelectionExplorationBinding,
  DetailFeatureLike,
  DetailFieldDefinition,
  DetailFieldModel,
  DetailModel,
  DetailModelOptions,
  DetailSelectionStatus,
  ShareableInteractionQueryParams,
  ShareableInteractionQueryState,
} from "./interactions/index.js";
// Experimental scene-workspace surface is subpath-only:
//   import { createSceneWorkspace } from "@honua/sdk-js/scene-workspace";
export { HonuaMap } from "./map/index.js";
export type {
  HonuaMapOptions,
  HonuaMapEvent,
  HonuaMapEventListener,
  LayerSnapshot,
  ResolvedMapSource,
} from "./map/index.js";
export { parseWebMap } from "./webmap/index.js";
export type { ParseWebMapOptions, ParseWebMapResult } from "./webmap/index.js";
export { webmapJsonToMapLibreStyle } from "./map/index.js";
export type {
  WebMapJsonToMapLibreStyleOptions,
  WebMapJsonToMapLibreStyleResult,
  WebMapMapLibreGapKind,
  WebMapMapLibreManualGap,
} from "./map/index.js";
export type {
  ApplyEditsRequest,
  ExportMapRequest,
  HonuaApplyEditsResponse,
  HonuaAttachmentEditResult,
  HonuaAttachmentGroup,
  HonuaAttachmentInfo,
  HonuaAttachmentListResponse,
  HonuaApiEnvelope,
  HonuaAuthCredentials,
  HonuaAuthCredentialsProvider,
  HonuaAuthProvider,
  HonuaAuthProviderContext,
  HonuaAuthProviderResult,
  HonuaAuthRefreshReason,
  HonuaAuthRevocationContext,
  HonuaCompatibilityRequest,
  HonuaClientOptions,
  HonuaCountResponse,
  HonuaEditResult,
  HonuaExportMapResponse,
  HonuaExtent,
  HonuaExtentResponse,
  HonuaFeature,
  HonuaFieldInfo,
  HonuaFindResponse,
  HonuaFindResult,
  HonuaIdentifyResponse,
  HonuaIdentifyResult,
  HonuaLayerMetadata,
  HonuaLegendEntry,
  HonuaLegendLayer,
  HonuaLegendResponse,
  HonuaObjectIdsResponse,
  HonuaOgcFeatureCollectionResponse,
  HonuaOgcFeatureResponse,
  HonuaOgcLink,
  HonuaQueryAttachmentsResponse,
  HonuaQueryResponse,
  HonuaRawRequest,
  HonuaRelatedRecordGroup,
  HonuaRelatedRecordsResponse,
  HonuaRelationshipInfo,
  HonuaAddAttachmentResponse,
  HonuaUpdateAttachmentResponse,
  HonuaDeleteAttachmentsResponse,
  HonuaOgcLandingResponse,
  HonuaOgcConformanceResponse,
  HonuaOgcCollectionSummary,
  HonuaOgcCollectionsResponse,
  HonuaOgcCollectionMetadata,
  HonuaOgcQueryableProperty,
  HonuaOgcQueryablesResponse,
  HonuaOgcRecordProperties,
  HonuaOgcRecordResponse,
  HonuaOgcRecordsResponse,
  HonuaErrorContext,
  HonuaRequestContext,
  HonuaRequestInterceptor,
  HonuaRequestMutation,
  HonuaRetryOptions,
  HonuaResponseContext,
  HonuaServerCapabilitiesResponse,
  HonuaServerCompatibility,
  HonuaServerCompatibilityControlPlaneApi,
  HonuaServerCompatibilityFeature,
  HonuaServerCompatibilityFeatures,
  HonuaServerCompatibilityMetadataSchema,
  HonuaServerCompatibilityStatus,
  HonuaServiceMetadata,
  HonuaSpatialReference,
  HonuaTransport,
  HonuaTypedFeature,
  HonuaTypedQueryResponse,
  MapFindRequest,
  MapIdentifyRequest,
  MapLayerQueryRequest,
  MapLegendRequest,
  MapRelatedRecordsRequest,
  MigrationCompatibilityAssessment,
  MigrationCutoverReadinessItem,
  MigrationCutoverReadinessSummary,
  MigrationEvidenceState,
  MigrationExternalDependency,
  MigrationInventoryAuthPosture,
  MigrationInventoryCodedValue,
  MigrationInventoryCompleteness,
  MigrationInventoryContainer,
  MigrationInventoryField,
  MigrationInventoryResource,
  MigrationInventoryScanRequest,
  MigrationInventorySourceKind,
  MigrationInventoryStyle,
  MigrationInventorySummary,
  MigrationManifestArtifact,
  MigrationManifestReviewItem,
  MigrationManifestStyleAction,
  MigrationManifestSummary,
  MigrationManifestTargetResource,
  MigrationParityEvidenceArtifact,
  MigrationParityEvidenceItem,
  MigrationParityEvidenceSection,
  MigrationReadinessAttestation,
  MigrationReadinessAttestationItem,
  MigrationSourceIdentity,
  MigrationSourceInventoryArtifact,
  MigrationSpatialReferenceInfo,
  OgcCollectionRequest,
  OgcCreateItemRequest,
  OgcDeleteItemRequest,
  OgcItemRequest,
  OgcItemsRequest,
  OgcMetadataRequest,
  OgcPatchItemRequest,
  OgcReplaceItemRequest,
  OgcResponseFormat,
  QueryFeaturesRequest,
  QueryMethod,
  QueryRelatedRecordsRequest,
  EsriGeometryType,
  EsriSpatialRel,
  EsriFieldType,
  EsriPoint,
  EsriPolyline,
  EsriPolygon,
  EsriEnvelope,
  EsriMultipoint,
  EsriGeometry,
  GeoJsonFeature,
  HonuaServicesResponse,
} from "./core/types.js";

// ─────────────────────────────────────────────────────────────
// Esri compatibility wrappers are subpath-only:
//   import { FeatureLayerCompat, MapViewCompat, ... } from "@honua/sdk-js/esri-compat";
// Keeping them out of the root barrel keeps tree-shaking honest and
// makes the canonical contract dominant in IDE autocomplete.
// ─────────────────────────────────────────────────────────────

export {
  createHonuaOgcFeatures,
  createHonuaService,
  HonuaFeatureLayer,
  HonuaGeometryService,
  HonuaGeoprocessingJobRun,
  HonuaGeoprocessingService,
  HonuaImageService,
  HonuaMapLayer,
  HonuaMapService,
  HonuaOgcFeatureCollection,
  HonuaOgcFeatures,
  HonuaService,
} from "./core/surfaces.js";
export {
  createHonuaOgcTiles,
  HonuaOgcTiles,
  HonuaOgcTileset,
} from "./core/ogc-tiles.js";
export type {
  HonuaOgcCollectionTileRequest,
  HonuaOgcCollectionTilesetRequest,
  HonuaOgcCollectionTilesetsRequest,
  HonuaOgcTilesOptions,
  HonuaOgcTilesetOptions,
} from "./core/ogc-tiles.js";
export {
  createHonuaOgcMaps,
  HonuaOgcCollectionMap,
  HonuaOgcMaps,
} from "./core/ogc-maps.js";
export type {
  HonuaOgcCollectionMapImageRequest,
  HonuaOgcCollectionMapOptions,
  HonuaOgcMapsOptions,
} from "./core/ogc-maps.js";
export {
  createHonuaOgcRecords,
  HonuaOgcRecordCollection,
  HonuaOgcRecords,
} from "./core/ogc-records.js";
export type {
  HonuaOgcRecordCollectionItemRequest,
  HonuaOgcRecordCollectionOptions,
  HonuaOgcRecordCollectionRawItemRequest,
  HonuaOgcRecordCollectionRawSearchRequest,
  HonuaOgcRecordCollectionSearchAllRequest,
  HonuaOgcRecordCollectionSearchRequest,
  HonuaOgcRecordsOptions,
  HonuaOgcRecordsSearchAllRequest,
} from "./core/ogc-records.js";
export {
  createGeoServicesGpAdapter,
  createGeospatialGrpcProcessAdapter,
  createHonuaProcessRunner,
  createOgcProcessesAdapter,
  HonuaProcessRunner,
} from "./core/process-runner.js";
export type {
  GeospatialGrpcCancelJobResponse,
  GeospatialGrpcErrorDetail,
  GeospatialGrpcGetJobResponse,
  GeospatialGrpcGetJobResultResponse,
  GeospatialGrpcJobProgress,
  GeospatialGrpcProcessClient,
  GeospatialGrpcSubmitJobResponse,
  HonuaProcessAdapter,
  HonuaProcessExecuteRequest,
  HonuaProcessJobOptions,
  HonuaProcessProtocol,
} from "./core/process-runner.js";
export {
  createHonuaWms,
  HonuaWms,
  HonuaWmsLayer,
} from "./core/wms.js";
export type {
  HonuaWmsLayerOptions,
  HonuaWmsOptions,
} from "./core/wms.js";
export {
  createHonuaWmts,
  HonuaWmts,
  HonuaWmtsLayer,
  HonuaWmtsTileset,
} from "./core/wmts.js";
export type {
  HonuaWmtsLayerOptions,
  HonuaWmtsOptions,
  HonuaWmtsTilesetOptions,
} from "./core/wmts.js";
export {
  HonuaWmsCapabilitiesParseError,
  findWmsLayer,
  iterateWmsLayers,
  parseWmsCapabilities,
} from "./core/wms-capabilities.js";
export type {
  WmsCapabilities,
  WmsCapabilitiesFormats,
  WmsCapabilitiesRequestSupport,
  WmsCapabilitiesService,
  WmsCapabilityBoundingBox,
  WmsCapabilityDimension,
  WmsCapabilityLayer,
  WmsCapabilityStyle,
} from "./core/wms-capabilities.js";
export {
  HonuaWmtsCapabilitiesParseError,
  findWmtsLayer,
  findWmtsTileMatrixSet,
  parseWmtsCapabilities,
} from "./core/wmts-capabilities.js";
export type {
  WmtsCapabilities,
  WmtsCapabilitiesService,
  WmtsCapabilityLayer,
  WmtsCapabilityResourceUrl,
  WmtsCapabilityStyle,
  WmtsCapabilityTileMatrix,
  WmtsCapabilityTileMatrixSet,
} from "./core/wmts-capabilities.js";
export type {
  HonuaWmsFeatureInfoResponse,
  HonuaWmsImageResponse,
  HonuaWmtsFeatureInfoResponse,
  HonuaWmtsTileResponse,
  WmsCrs,
  WmsFeatureInfoRequest,
  WmsLegendRequest,
  WmsMapRequest,
  WmtsFeatureInfoRequest,
  WmtsTileMode,
  WmtsTileRequest,
} from "./core/wms-types.js";
export {
  createHonuaOgcProcesses,
  HonuaJobFailedError,
  HonuaOgcProcessJobRun,
  HonuaOgcProcesses,
} from "./core/ogc-processes.js";
export type {
  HonuaOgcProcessJobOptions,
  HonuaOgcProcessesOptions,
} from "./core/ogc-processes.js";
export {
  createHonuaStacSearch,
  HonuaStacSearch,
} from "./core/stac.js";
export type {
  HonuaStacSearchAllRequest,
  HonuaStacSearchOptions,
} from "./core/stac.js";
export {
  HonuaOdataEntitySet,
  buildOdataSpatialFilter,
  odataFieldSchema,
  parseOdataMetadata,
  rewriteWhereToOdataFilter,
} from "./core/odata.js";
export type {
  HonuaOdataAdvertisedCapabilities,
  HonuaOdataAggregateResult,
  HonuaOdataBatchOperation,
  HonuaOdataBatchOptions,
  HonuaOdataBatchOutcome,
  HonuaOdataBatchResult,
  HonuaOdataDeltaPage,
  HonuaOdataEntitySetOptions,
  HonuaOdataFieldInfo,
  HonuaOdataMetadata,
  HonuaOdataPage,
  HonuaOdataQueryParams,
  OdataSpatialFilterContext,
} from "./core/odata.js";
export {
  HonuaWfs,
  HonuaWfsFeatureType,
  HonuaWfsStoredQuery,
  rethrowAsWfsExceptionIfPossible,
} from "./core/wfs.js";
export type {
  HonuaWfsOptions,
  OutputFormatChoice,
} from "./core/wfs.js";
export {
  hasOgcConformanceClass,
  negotiateOgcCapabilities,
} from "./core/ogc-conformance.js";
export type { OgcConformanceProtocol } from "./core/ogc-conformance.js";
export type {
  HonuaOgcMapImageResponse,
  HonuaOgcProcessDescription,
  HonuaOgcProcessJobAccepted,
  HonuaOgcProcessJobResults,
  HonuaOgcProcessJobStatus,
  HonuaOgcProcessSummary,
  HonuaOgcProcessesResponse,
  HonuaOgcTileMatrix,
  HonuaOgcTileMatrixSet,
  HonuaOgcTileMatrixSetsResponse,
  HonuaOgcTileResponse,
  HonuaOgcTilesetMetadata,
  HonuaOgcTilesetsResponse,
  HonuaStacItemCollectionResponse,
  HonuaStacItemResponse,
  HonuaStacLandingResponse,
  OgcRecordItemRequest,
  OgcRecordRawItemRequest,
  OgcRecordsRawSearchRequest,
  OgcRecordsSearchRequest,
  OgcMapImageRequest,
  OgcMapFormat,
  OgcProcessExecuteRequest,
  OgcProcessIoValue,
  OgcProcessInputs,
  OgcProcessStatus,
  OgcTileDataType,
  OgcTileMatrixSetId,
  OgcTileRequest,
  OgcTilesetRequest,
  OgcTilesetsRequest,
  StacSearchRequest,
} from "./core/types.js";
export type {
  HonuaFeatureLayerAddAttachmentRequest,
  HonuaFeatureLayerAttachmentData,
  HonuaFeatureLayerApplyEditsRequest,
  HonuaFeatureLayerDeleteAttachmentsRequest,
  HonuaFeatureLayerListAttachmentsRequest,
  HonuaFeatureLayerOptions,
  HonuaFeatureLayerQueryAllRequest,
  HonuaFeatureLayerQueryAttachmentsRequest,
  HonuaFeatureLayerQueryCountRequest,
  HonuaFeatureLayerQueryExtentRequest,
  HonuaFeatureLayerQueryExtentResponse,
  HonuaFeatureLayerQueryObjectIdsRequest,
  HonuaFeatureLayerQueryRelatedRecordsRequest,
  HonuaFeatureLayerQueryRequest,
  HonuaFeatureLayerRequest,
  HonuaFeatureLayerSpatialAggregationRequest,
  HonuaFeatureLayerUpdateAttachmentRequest,
  HonuaGeometryBinaryOperationRequest,
  HonuaGeometryBufferRequest,
  HonuaGeometryClipRequest,
  HonuaGeometryDifferenceRequest,
  HonuaGeometryIntersectRequest,
  HonuaGeometryOperationResponse,
  HonuaGeometryProjectRequest,
  HonuaGeometryServiceOptions,
  HonuaGeometrySimplifyRequest,
  HonuaGeometryUnionRequest,
  HonuaGeoprocessingJob,
  HonuaGeoprocessingJobRunOptions,
  HonuaGeoprocessingJobRunRequestOptions,
  HonuaGeoprocessingServiceOptions,
  HonuaGeoprocessingSubmitRequest,
  HonuaImageServiceExportRequest,
  HonuaImageServiceIdentifyRequest,
  HonuaImageServiceOptions,
  HonuaImageServiceQueryRequest,
  HonuaMapServiceExportMapRequest,
  HonuaMapServiceFindRequest,
  HonuaMapServiceIdentifyRequest,
  HonuaMapServiceLegendRequest,
  HonuaMapServiceRequest,
  HonuaMapLayerOptions,
  HonuaMapLayerQueryAllRequest,
  HonuaMapLayerQueryCountRequest,
  HonuaMapLayerQueryExtentRequest,
  HonuaMapLayerQueryExtentResponse,
  HonuaMapLayerQueryObjectIdsRequest,
  HonuaMapLayerQueryRelatedRecordsRequest,
  HonuaMapLayerQueryRequest,
  HonuaMapLayerRequest,
  HonuaMapServiceQueryLayerAllRequest,
  HonuaMapServiceQueryLayerCountRequest,
  HonuaMapServiceQueryLayerExtentRequest,
  HonuaMapServiceQueryLayerExtentResponse,
  HonuaMapServiceQueryLayerObjectIdsRequest,
  HonuaMapServiceQueryLayerRelatedRecordsRequest,
  HonuaMapServiceQueryLayerRequest,
  HonuaMapServiceOptions,
  HonuaOgcCollectionCreateItemRequest,
  HonuaOgcCollectionDeleteItemRequest,
  HonuaOgcCollectionItemRequest,
  HonuaOgcCollectionItemsAllRequest,
  HonuaOgcCollectionItemsRequest,
  HonuaOgcCollectionPatchItemRequest,
  HonuaOgcCollectionReplaceItemRequest,
  HonuaOgcCollectionRequest,
  HonuaOgcCreateItemRequest,
  HonuaOgcDeleteItemRequest,
  HonuaOgcFeatureCollectionOptions,
  HonuaOgcFeaturesOptions,
  HonuaOgcItemRequest,
  HonuaOgcItemsAllRequest,
  HonuaOgcItemsRequest,
  HonuaOgcMetadataRequest,
  HonuaOgcPatchItemRequest,
  HonuaOgcReplaceItemRequest,
  HonuaServiceOptions,
} from "./core/surfaces.js";

export { HonuaGeocodingClient } from "./geocoding/index.js";
export type {
  GeocodingClientOptions,
  ForwardGeocodeOptions,
  ReverseGeocodeOptions,
  SuggestOptions,
  GeocodeResult,
  ReverseGeocodeResult,
  GeocodeSuggestion,
} from "./geocoding/index.js";

export {
  ANALYTICS_SOURCE_SCHEMA_VERSION,
  CAPABILITIES,
  FEATURE_SERVER_H3_SPATIAL_AGGREGATION_INDEX_MODEL_ID,
  PROTOCOL_DEFAULT_CAPABILITIES,
  PROTOCOLS,
  SPATIAL_AGGREGATION_CAPABILITY,
  SPATIAL_AGGREGATION_METADATA_SCHEMA_VERSION,
  SPATIAL_AGGREGATION_SCHEMA_VERSION,
  WIDGET_SOURCE_SCHEMA_VERSION,
  ALL_CAPABILITIES,
  FIRST_PARTY_PROTOCOLS,
  QUERY_TILE_SERVER_CONTRACT_VERSION,
  QUERY_TILE_SERVER_FEATURE_DETAIL_ROUTE_TEMPLATE,
  QUERY_TILE_SERVER_RESPONSE_HEADERS,
  QUERY_TILE_SERVER_ROUTE_PREFIX,
  QUERY_TILE_SERVER_SOURCE_ROUTE_TEMPLATE,
  QUERY_TILE_SERVER_TILEJSON_ROUTE_TEMPLATE,
  QUERY_TILE_SERVER_TILE_ROUTE_TEMPLATE,
  assertFeatureServerH3SpatialAggregationRequest,
  assertValidSpatialAggregationRequest,
  analyticsSourceDegradedReason,
  analyticsSourceId,
  assessAnalyticsSourcePushdown,
  buildAnalyticsSourceCacheKey,
  buildQueryTileCacheKey,
  buildQueryTileFeatureDetailQuery,
  buildQueryTileServerPath,
  buildQueryTileServerUrl,
  capabilities,
  createEditSession,
  createDataset,
  createEditSketchWorkflow,
  createWidgetSource,
  defineIndexedSpatialSource,
  defineQueryTileSource,
  defineWarehouseQuerySource,
  defineWarehouseTableSource,
  defineWarehouseTilesetSource,
  EditSketchWorkflowModel,
  EditWorkflowSession,
  geoServicesFeatureSource,
  geoServicesGPServiceSource,
  geoServicesGeometryServiceSource,
  geoServicesImageSource,
  geoServicesMapServiceSource,
  intersectCapabilities,
  isAnalyticsSourceDescriptor,
  isJobTerminal,
  isSpatialAggregationComplete,
  loadQueryTileFeatureDetail,
  mapQueryTileFeatureIdentity,
  normalizeQueryTileKey,
  normalizeQueryTileSourceDescriptor,
  normalizeAnalyticsSourceDescriptor,
  normalizeEditWorkflowFailures,
  odataSource,
  ogcFeaturesSource,
  ogcMapsSource,
  ogcRecordsSource,
  ogcTilesSource,
  parseQueryTileFeatureDetailResponse,
  parseQueryTileJson,
  parseQueryTileServerErrorResponse,
  queryTileKeyString,
  queryTileServerRequestParamsFromDescriptor,
  resolveSpatialAggregationWidgetSummary,
  spatialAggregationProgress,
  spatialAggregationSummaryKindSupportedByFeatureServerH3,
  spatialAggregationSummaryKindRequiresField,
  spatialAggregationWidgets,
  stableJson,
  stacSearchSource,
  TEMPORAL_CAPABILITY,
  TEMPORAL_ROUTE_PREFIX,
  TEMPORAL_ROUTES,
  TEMPORAL_SCHEMA_VERSION,
  assertValidTemporalRollbackPlanRequest,
  createTemporalClient,
  isReadOnlyTemporalHistory,
  temporalModeSupports,
  validateTemporalRollbackPlanRequest,
  unionCapabilities,
  validateFeatureServerH3SpatialAggregationRequest,
  validateSpatialAggregationRequest,
  widgetSource,
  wfsSource,
  wmsSource,
  wmtsSource,
} from "./contract/index.js";
export type {
  AdapterFor,
  AdapterKind,
  AdapterTypeMap,
  AggregationFn,
  AggregationHistogramBucketAliases,
  AggregationHistogramBucketSpec,
  AggregationMetric,
  AggregationSpec,
  AggregationTimeIntervalSpec,
  AggregationTimeIntervalUnit,
  AggregationTimeSeriesAliases,
  AggregationTimeSeriesSpec,
  AnalyticsIndexCoverageDescriptor,
  AnalyticsIndexCoverageKind,
  AnalyticsIndexDescriptor,
  AnalyticsIndexHierarchy,
  AnalyticsSourceCacheIdentity,
  AnalyticsSourceCacheKeyOptions,
  AnalyticsSourceCachePolicy,
  AnalyticsSourceCapabilityMetadata,
  AnalyticsSourceDescriptor,
  AnalyticsSourceDescriptorBase,
  AnalyticsSourceFallbackMode,
  AnalyticsSourceFallbackPolicy,
  AnalyticsSourceKind,
  AnalyticsSourceProtocolEscapeHatch,
  AnalyticsSourcePushdownAssessment,
  AnalyticsSourcePushdownCapability,
  AnalyticsSourceRelationDescriptor,
  AnalyticsSourceSchemaVersion,
  AnalyticsSourceSqlDescriptor,
  AnalyticsSourceTilesetDescriptor,
  AnalyticsWarehouseProvider,
  AttachmentAdd,
  AttachmentApi,
  AttachmentDelete,
  AttachmentEditOutcome,
  AttachmentGroup,
  AttachmentInfo,
  AttachmentQuery,
  AttachmentUpdate,
  CanonicalFeature,
  Capabilities,
  Capability,
  CapabilityPolicy,
  CreateDatasetOptions,
  CreateEditSessionOptions,
  Dataset,
  DatasetId,
  DegradedReason,
  EditAttachmentMutation,
  EditAttachmentMutationOutcome,
  EditEnvelope,
  EditOutcome,
  EditResult,
  EditFieldDomain,
  EditFieldDomainCodedValue,
  EditWorkflowCapabilityState,
  EditWorkflowCapabilitySummary,
  EditWorkflowConflictInfo,
  EditWorkflowConflictState,
  EditWorkflowFailure,
  EditWorkflowFailureKind,
  EditWorkflowField,
  EditWorkflowKind,
  EditWorkflowMetadata,
  EditWorkflowMetadataOptions,
  EditWorkflowOperation,
  EditWorkflowOptimisticHooks,
  EditWorkflowRelationship,
  EditWorkflowSnapshot,
  EditWorkflowStatus,
  EditWorkflowSubmitResult,
  EditWorkflowValidationError,
  EditWorkflowValidationResult,
  EditAnnotationPersistenceHook,
  EditAnnotationPersistenceSnapshot,
  EditAnnotationPersistenceState,
  EditSketchCapabilityState,
  EditSketchStatus,
  EditSketchTool,
  EditSketchToolCapability,
  EditSketchToolCapabilityInput,
  EditSketchUndoSnapshot,
  EditSketchWorkflowOptions,
  EditSketchWorkflowSnapshot,
  FeatureId,
  IndexedSpatialSourceDescriptor,
  IJobRun,
  JobError,
  JobProgress,
  JobResult,
  JobSnapshot,
  JobSnapshotListener,
  JobStatus,
  MapBinding,
  PaginationSpec,
  Protocol,
  Query,
  QueryTileCacheIdentityDescriptor,
  QueryTileCacheKeyOptions,
  QueryTileCachePolicy,
  QueryTileEndpointDescriptor,
  QueryTileFallbackMode,
  QueryTileFallbackPolicy,
  QueryTileFeatureDetailOptions,
  QueryTileFeatureIdentityContext,
  QueryTileFeatureIdentityDescriptor,
  QueryTileFeatureIdentityMapper,
  QueryTileFeatureIdentityTarget,
  QueryTileFormat,
  QueryTileFeatureDetailResponse,
  QueryTileJson,
  QueryTileJsonVectorLayer,
  QueryTileKey,
  QueryTileKeyInput,
  QueryTileProjectionDescriptor,
  QueryTileScheme,
  QueryTileServerCachePolicyDescriptor,
  QueryTileServerCacheValidators,
  QueryTileServerContractFixture,
  QueryTileServerDegradation,
  QueryTileServerDegradationCode,
  QueryTileServerDegradationSeverity,
  QueryTileServerError,
  QueryTileServerErrorCode,
  QueryTileServerErrorResponse,
  QueryTileServerFeatureIdentityDescriptor,
  QueryTileServerLimitDescriptor,
  QueryTileServerRequestParameters,
  QueryTileServerRouteKind,
  QueryTileServerRouteOptions,
  QueryTileServerTileJsonMetadata,
  QueryTileSpatialReference,
  QueryTileSpatialReferenceDescriptor,
  QueryTileExtentDescriptor,
  QueryTileSourceDescriptor,
  DefineQueryTileSourceOptions,
  RelatedGroup,
  RelatedQuery,
  RelatedResult,
  ResolveSourceContext,
  Result,
  NormalizeEditWorkflowFailuresOptions,
  SortSpec,
  Source,
  SourceAnalyticsCapabilities,
  SourceDescriptor,
  SourceFreshnessContract,
  SourceHistogramCapabilityMetadata,
  SourceId,
  SourceLocator,
  SourceResolver,
  SourceSchema,
  SourceTimeSeriesCapabilityMetadata,
  SpatialAggregationCacheMetadata,
  SpatialAggregationCategoryBucket,
  SpatialAggregationCategorySummarySpec,
  SpatialAggregationCategoryValue,
  SpatialAggregationCell,
  SpatialAggregationCellGeometry,
  SpatialAggregationContractFixture,
  SpatialAggregationCountSummarySpec,
  SpatialAggregationCountValue,
  SpatialAggregationDomainValue,
  SpatialAggregationGroupByMetadata,
  SpatialAggregationGroupBySpec,
  SpatialAggregationGroupedSummary,
  SpatialAggregationHistogramBucket,
  SpatialAggregationHistogramSummarySpec,
  SpatialAggregationHistogramValue,
  SpatialAggregationInclude,
  SpatialAggregationIndexModelMetadata,
  SpatialAggregationIndexCoverageMetadata,
  SpatialAggregationIndexSelection,
  SpatialAggregationIndexState,
  SpatialAggregationMetadata,
  SpatialAggregationMetricKind,
  SpatialAggregationMetricSummarySpec,
  SpatialAggregationMetricValue,
  SpatialAggregationPageInfo,
  SpatialAggregationPageRequest,
  SpatialAggregationProgressRefinement,
  SpatialAggregationProgressStatus,
  SpatialAggregationProgressiveState,
  SpatialAggregationRangeBucketSpec,
  SpatialAggregationRangeBucketValue,
  SpatialAggregationRangeSummarySpec,
  SpatialAggregationRangeValue,
  SpatialAggregationRequest,
  SpatialAggregationResolutionInput,
  SpatialAggregationResult,
  SpatialAggregationSummaryBag,
  SpatialAggregationSummaryBase,
  SpatialAggregationSummaryKind,
  SpatialAggregationSummaryMetadata,
  SpatialAggregationSummarySpec,
  SpatialAggregationSummaryValue,
  SpatialAggregationValidationIssue,
  SpatialAggregationValueType,
  SpatialAggregationViewport,
  SpatialAggregationWidgetKind,
  SpatialAggregationWidgetMetadata,
  WidgetCategoriesRequest,
  WidgetCategoriesResult,
  WidgetCategoryBucket,
  WidgetCountRequest,
  WidgetCountResult,
  WidgetFormulaRequest,
  WidgetFormulaResult,
  WidgetHistogramBin,
  WidgetHistogramRequest,
  WidgetHistogramResult,
  WidgetRangeRequest,
  WidgetRangeResult,
  WidgetSource,
  WidgetSourceCacheHints,
  WidgetSourceCacheMetadata,
  WidgetSourceExecutionMode,
  WidgetSourceFilterClause,
  WidgetSourceFreshnessContract,
  WidgetSourceModelKind,
  WidgetSourceOptions,
  WidgetSourceOrderBy,
  WidgetSourceProjection,
  WidgetSourceRequestBase,
  WidgetSourceResponseBase,
  WidgetSourceSchemaVersion,
  WidgetSourceValue,
  WidgetTimeSeriesBucket,
  WidgetTimeSeriesInterval,
  WidgetTimeSeriesIntervalUnit,
  WidgetTimeSeriesRequest,
  WidgetTimeSeriesResult,
  WidgetTopValueBucket,
  WidgetTopValuesRequest,
  WidgetTopValuesResult,
  WarehouseQuerySourceDescriptor,
  WarehouseTableSourceDescriptor,
  WarehouseTilesetSourceDescriptor,
  TemporalAsOfRequest,
  TemporalAttributeChange,
  TemporalCheckpoint,
  TemporalChangeSet,
  TemporalChangeSetOperationKind,
  TemporalClient,
  TemporalClientCallOptions,
  TemporalContractFixture,
  TemporalCursor,
  TemporalCursorType,
  TemporalDiff,
  TemporalDiffRequest,
  TemporalDiffStatus,
  TemporalDiffSummary,
  TemporalError,
  TemporalErrorCode,
  TemporalFeatureChangeType,
  TemporalFeatureDiff,
  TemporalFeatureTimeline,
  TemporalFeatureTimelineRequest,
  TemporalFilter,
  TemporalGeometryChange,
  TemporalHistoryModel,
  TemporalJobRef,
  TemporalMode,
  TemporalRequestClient,
  TemporalRevision,
  TemporalRevisionOperation,
  TemporalRiskLevel,
  TemporalRollbackExecuteRequest,
  TemporalRollbackMode,
  TemporalRollbackOperation,
  TemporalRollbackPlan,
  TemporalRollbackPlanRequest,
  TemporalRollbackScope,
  TemporalRollbackStatus,
  TemporalSourceCapability,
  TemporalValidationIssue,
} from "./contract/index.js";

export {
  EMPTY_STATE,
  EMPTY_STATE as EXPLORATION_EMPTY_STATE,
  LINKED_VIEW_PRESETS,
  SLICES,
  SLICES as EXPLORATION_SLICES,
  createExplorationContext,
  featureSelectionKey,
  isSourceQualifiedSelectionTarget,
  propagationFor,
  reduce,
  reduce as reduceExplorationState,
  sourceFeatureSelectionTarget,
} from "./exploration/index.js";

// Experimental realtime / app-controller / app-workspace surfaces are subpath-only:
//   import { createRealtimeFeatureStore } from "@honua/sdk-js/realtime";
//   import { HonuaController } from "@honua/sdk-js/app-controller";
//   import { HonuaAppWorkspace } from "@honua/sdk-js/app-workspace";
export type {
  ApplyPresetIntent,
  ChangeEvent,
  ClearFilterIntent,
  CreateExplorationContextOptions,
  DeselectIntent,
  ExplorationContext,
  ExplorationIntent,
  ExplorationSlice,
  ExplorationState,
  ExplorationStateSnapshot,
  ExplorationViewChangeEvent,
  ExplorationViewController,
  ExplorationViewIntent,
  ExplorationViewListener,
  ExplorationViewSubscribeOptions,
  ExplorationViewSubscription,
  FeatureSelectionTarget,
  FilterClause,
  FilterOperator,
  LinkedViewPolicy,
  LinkedViewPresetName,
  LinkedViewRule,
  Listener as ExplorationListener,
  ReducerResult,
  SelectIntent,
  SetAggregationIntent,
  SetExtentIntent,
  SetFilterIntent,
  SetGroupingIntent,
  SetPageIntent,
  SetSortIntent,
  SetSpatialFilterIntent,
  SetVisibleFieldsIntent,
  SnapshotRestoreIntent,
  SourceQualifiedFeatureSelectionTarget,
  Unsubscribe as ExplorationUnsubscribe,
  ViewBinding,
  ViewHandle,
  ViewRole,
} from "./exploration/index.js";

// Experimental agent-tools surface is subpath-only:
//   import { HONUA_AGENT_TOOL_DEFINITIONS } from "@honua/sdk-js/agent-tools";
